enum aas2EdgeFlag_t : int
{
    AAS_EDGE_WALL = 1,
    AAS_EDGE_LEDGE = 2,
    AAS_EDGE_WALL_CORNER = 4,
    AAS_EDGE_LEDGE_CORNER = 8,
    AAS_EDGE_STEP_TOP = 16,
    AAS_EDGE_STEP_BOTTOM = 32,
    AAS_EDGE_VERTICAL = 64,
    AAS_EDGE_WATER = 128,
    AAS_EDGE_LADDER = 256,
    AAS_EDGE_STEP_SIDE = 512,
    AAS_EDGE_WALL_CORNER_V0 = 1024,
    AAS_EDGE_WALL_CORNER_V1 = 2048,
    AAS_EDGE_FAKE = 4096,
    AAS_EDGE_MAX = 4097
};
