enum actorPainFlags_t : int
{
    PAINFLAG_NONE = 0,
    PAINFLAG_USE_LOOP_STAGGER = 1,
    PAINFLAG_MOVING = 2,
    PAINFLAG_NO_ORIENT = 4,
    PAINFLAG_FORCE_FRONT = 8,
    PAINFLAG_IGNORE_TAGS = 16,
    PAINFLAG_IGNORE_TAGS_EXCEPT_SOURCE = 32,
    PAINFLAG_IGNORE_SOURCE_TAGS = 64,
    PAINFLAG_IGNORE_OPTIONAL_STRING = 128,
    PAINFLAG_IGNORE_INJURED_STATES = 256,
    PAINFLAG_REMOVE_FROM_HANGOUT = 512,
    PAINFLAG_IGNORE_CONTEXT_FLAGS = 1024,
    PAINFLAG_EVALUATE_POSSESSED_BY_SPIRIT_CONTEXT_FLAG = 2048,
    PAINFLAG_EVALUATE_BUFFED_BY_SCREECHER_CONTEXT_FLAG = 4096,
    PAINFLAG_GUARANTEED_PAIN_ONLY = 8192,
    PAINFLAG_SKIP_TRANSLATION_TEST = 16384,
    PAINFLAG_IGNORE_CONTEXT_FLAGS_GUARANTEED_PAIN_ONLY = 32768
};
