enum aiActionScriptFlags_t : int
{
    ACTIONSCRIPT_ABORT_FOR_COMBAT = 1,
    ACTIONSCRIPT_ABORT_FOR_SEARCH = 2,
    ACTIONSCRIPT_IGNORE_AI_EVENTS = 4,
    ACTIONSCRIPT_NO_COMBAT_CHATTER = 8,
    ACTIONSCRIPT_NO_TARGETS = 16,
    ACTIONSCRIPT_IGNORE_PLAYER_APPROACH = 32,
    ACTIONSCRIPT_NO_DAMAGE = 64,
    ACTIONSCRIPT_NO_TWITCH_PAIN = 128,
    ACTIONSCRIPT_ENABLE_STAGGER_PAIN = 256,
    ACTIONSCRIPT_ENABLE_AUTOFOCUS = 512,
    ACTIONSCRIPT_SKIP_SPAWN_OVERRIDE_ACTIONS = 1024
};
