enum aiActionValidatorCategoryFlags : unsigned int
{
    VALIDATE_NONE = 0,
    VALIDATE_DISTANCE = 1,
    VALIDATE_DIRECTION = 2,
    VALIDATE_ANIM_DELTA = 4,
    VALIDATE_ANIM_EVENTS = 8,
    VALIDATE_WALKSTATE = 16,
    VALIDATE_PRECONDITIONS = 32,
    VALIDATE_TIMERS = 64,
    VALIDATE_TOKENS = 128,
    VALIDATE_MEMORY_KEYS = 256,
    VALIDATE_AI_CONDITIONS = 512,
    VALIDATE_BEHAVIOR_KEYS = 1024
};
