enum aiAnimDCFlags_t : int
{
    DC_FLAGS_NONE = 0,
    DC_ROTATION_IGNORES_REMAINING_FRAMES = 1,
    DC_NO_REVERSE_ROTATION = 2,
    DC_NO_RESTRICT_ROTATION_DIRECTION_YAW = 4,
    DC_RESTRICT_ROTATION_DIRECTION_PITCH = 8,
    DC_RESTRICT_ROTATION_DIRECTION_ROLL = 16,
    DC_TRANSLATION_IGNORES_REMAINING_FRAMES = 32,
    DC_LERP_ONLY_MODEL_SPACE_X = 64,
    DC_LERP_ONLY_MODEL_SPACE_Y = 128,
    DC_LERP_ONLY_MODEL_SPACE_Z = 256,
    DC_CORRECT_TRANSLATED_ROTATION = 512,
    DC_NO_DELTA_REBUILD = 1024,
    DC_ALLOW_LARGE_CORRECTION = 2048,
    DC_RAMP_CORRECTION_BY_ALIGNMENT = 4096,
    DC_GROUND_TRACE_FROM_ORIGIN = 8192
};
