enum aiAnimDCIdealPoint_t : int
{
    IDEALPOINT_NONE = 0,
    IDEALPOINT_GOALPOINT = 1,
    IDEALPOINT_NEXTPOINT = 2,
    IDEALPOINT_CURRENT_ANIMNODE = 3,
    IDEALPOINT_CURRENT_REF_PT = 4,
    IDEALPOINT_ENEMYORIGIN = 5,
    IDEALPOINT_NEXTGROUNDPOINT = 6,
    IDEALPOINT_FLIGHT_ANIM = 7,
    IDEALPOINT_PATH_POINT = 8,
    IDEALPOINT_TRAVERSAL_ENDPOINT = 9,
    IDEALPOINT_JOINT_KEYFRAME_ON_OTHER = 10,
    IDEALPOINT_NEXT_TRAVERSAL_STARTPOINT = 11,
    IDEALPOINT_POUNCE_TARGET = 12,
    IDEALPOINT_ANIM = 13,
    IDEALPOINT_GROUND = 14,
    IDEALPOINT_X_SCALE_TO_ATTACK = 15,
    IDEALPOINT_NOOP = 16
};
