enum aiAnimDCIdealDir_t : int
{
    IDEALDIR_NONE = 0,
    IDEALDIR_BODYORIENTATION = 1,
    IDEALDIR_MOVEORIENTATION = 2,
    IDEALDIR_GOALORIENTATION = 3,
    IDEALDIR_TONEXTPOINT = 4,
    IDEALDIR_TOGOALPOINT = 5,
    IDEALDIR_TOENEMY = 6,
    IDEALDIR_TOENEMY_EXPLICIT_MISS = 7,
    IDEALDIR_CURRENT_ANIMNODE = 8,
    IDEALDIR_CURRENT_REF_AXIS = 9,
    IDEALDIR_DEPARTURE_PATH_DIRECTION = 10,
    IDEALDIR_JOINT_KEYFRAME_ON_OTHER = 11,
    IDEALDIR_NEXT_TRAVERSAL_STARTPOINT = 12,
    IDEALDIR_LOOK_FOCUS = 13,
    IDEALDIR_AIM_FOCUS = 14,
    IDEALDIR_ATTACK_TARGET = 15,
    IDEALDIR_CURRENT_TRAVERSAL_AXIS = 16,
    IDEALDIR_NOOP = 17
};
