enum aiBerserkBuffType_t : int
{
    AI_BERSERK_BUFF_NONE = 0,
    AI_BERSERK_BUFF_PAIN_TAKEN_SCALE = 1,
    AI_BERSERK_BUFF_PAIN_TAKEN_BOOST = 2,
    AI_BERSERK_BUFF_DAMAGE_TAKEN_SCALE = 4,
    AI_BERSERK_BUFF_DAMAGE_TAKEN_BOOST = 8,
    AI_BERSERK_BUFF_GORE_DAMAGE_SCALE = 16,
    AI_BERSERK_BUFF_GORE_DAMAGE_BOOST = 32,
    AI_BERSERK_BUFF_DISABLED_PAIN_TYPE = 64,
    AI_BERSERK_BUFF_DISABLED_WEAKPOINTS = 128
};
