enum aiCodeAction_t : int
{
    AICODE_ACTION_NONE = 0,
    AICODE_ACTION_MOVE = 1,
    AICODE_ACTION_IDLE = 2,
    AICODE_ACTION_ANIM = 3,
    AICODE_ACTION_FREEZE = 4,
    AICODE_ACTION_SYNC = 5,
    AICODE_ACTION_MEAT_HOOKED = 6,
    AICODE_ACTION_AUGER = 7,
    AICODE_ACTION_ICY_FREEZE = 8,
    AICODE_ACTION_MICROWAVE_FREEZE = 9,
    AICODE_ACTION_SACRIFICE_FREEZE = 10,
    AICODE_ACTION_BFG_ARC_FREEZE = 11
};
