enum aiCondition_t : int
{
    CONDITION_NONE = 0,
    CONDITION_UNAVAILABLE = 1,
    CONDITION_PINNED = 2,
    CONDITION_CANT_SEE = 4,
    CONDITION_INJURED = 8,
    CONDITION_INTIMIDATED = 16,
    CONDITION_FIRING = 32,
    CONDITION_RELOADING = 64,
    CONDITION_MOVING = 128,
    CONDITION_REQUEST_HOLD_FIRE = 256,
    CONDITION_REQUEST_COVER_FIRE = 512,
    CONDITION_REQUEST_GRENADE = 1024,
    CONDITION_FORCE_CHARGE = 2048,
    CONDITION_MUST_SEARCH = 4096,
    CONDITION_GW_PERFECT_AIM = 8192,
    CONDITION_GW_ALL_FIRE_FROM_COVER = 16384,
    CONDITION_GW_MAX_HOLD_TRIGGER = 32768,
    CONDITION_GW_INFINITE_AMMO = 65536,
    CONDITION_GW_DAMAGE_SCALE = 131072,
    CONDITION_LOCKED = 262144
};
