enum aiDamageStateTriggers_t : int
{
    DAMAGETRIGGER_NONE = 0,
    DAMAGETRIGGER_PAIN_FINISHED = 1,
    DAMAGETRIGGER_TWITCH_STARTED = 2,
    DAMAGETRIGGER_TWITCH_FINISHED = 3,
    DAMAGETRIGGER_PAIN_ERROR = 4,
    DAMAGETRIGGER_TWITCH_PLAYED = 5,
    DAMAGETRIGGER_ANIM_EVENT_DAMAGE_KEY = 6
};
