enum aiFireMode_t : int
{
    AIFIREMODE_HOLDFIRE = 0,
    AIFIREMODE_WEAPON_EXPLICIT_RELEASE = 1,
    AIFIREMODE_WEAPON = 2,
    AIFIREMODE_FIREWHENREADY = 3,
    AIFIREMODE_SPRAYWHENREADY = 4,
    AIFIREMODE_MAX = 5
};
