enum aiFocus_t : int
{
    AIFOCUS_NOTHING = 0,
    AIFOCUS_ENTITY = 1,
    AIFOCUS_CAMERA = 2,
    AIFOCUS_LAST_SEEN_POS = 3,
    AIFOCUS_POS_WHEN_LAST_SEEN = 4,
    AIFOCUS_LAST_SENSED_POS = 5,
    AIFOCUS_POS_WHEN_LAST_SENSED = 6,
    AIFOCUS_ENEMY_APPROACH_DIR = 7,
    AIFOCUS_PARTIAL_SENSE = 8,
    AIFOCUS_FRIENDLY = 9,
    AIFOCUS_FRIENDLY_FOCUS = 10,
    AIFOCUS_MOVE_DEST = 11,
    AIFOCUS_LOOK_AROUND = 12,
    AIFOCUS_SUPPRESSION_FIRE_POINT = 13,
    AIFOCUS_MISC = 14
};
