enum aiFXContext_t : int
{
    AIFX_NONE = 0,
    AIFX_JETPACK_MALFUNCTION = 1,
    AIFX_SLED_ATTACHED = 2,
    AIFX_SLED_DETACHED = 3,
    AIFX_PHASE_SHIFT_TRAVERSAL_CHECK = 4,
    AIFX_WOUND_LEFT = 5,
    AIFX_WOUND_RIGHT = 6,
    AIFX_IN_TARGET_FOV = 7,
    AIFX_POSSESSED_BY_SPIRIT = 8,
    AIFX_BUFFED_BY_SCREECHER = 9,
    AIFX_SUPPRESS_ANIM_BLEND_OUT = 10
};
