enum aiGraphDebugFlags_t : unsigned int
{
    DEBUGFLAG_NONE = 0,
    DEBUGFLAG_BREAK_ON_ENTER = 1,
    DEBUGFLAG_BREAK_ON_EXIT = 2,
    DEBUGFLAG_BREAK_ON_EVALUATE = 4,
    DEBUGFLAG_BREAK_ON_SUCCESS = 8,
    DEBUGFLAG_BREAK_ON_FAIL = 16,
    DEBUGFLAG_BREAK_ON_EXECUTE = 32,
    DEBUGFLAG_BREAK_ON_CLEAN = 64,
    DEBUGFLAG_DEBUG_EXECUTE = 128
};
