enum aiHintPrimitive_t : int
{
    AIHINT_PRIMITIVE_CIRCLE = 0,
    AIHINT_PRIMITIVE_CYLINDER = 1,
    AIHINT_PRIMITIVE_SPHERE = 2,
    AIHINT_PRIMITIVE_PLANE = 3,
    AIHINT_PRIMITIVE_VOLUME = 4,
    AIHINT_PRIMITIVE_MAX = 5
};
