enum aim_targetType_t : int
{
    AIMTARGET_TYPE_HOSTILE = 1,
    AIMTARGET_TYPE_FRIENDLY = 2,
    AIMTARGET_TYPE_USEABLE = 4,
    AIMTARGET_TYPE_INFO = 8,
    AIMTARGET_TYPE_PROJECTILE = 16,
    AIMTARGET_TYPE_BREAKABLE = 32,
    AIMTARGET_TYPE_TARGET_MELEE = 64,
    AIMTARGET_TYPE_ALL = 2147483647
};
