enum aim_Target_type_t : int
{
    AIM_TARGET_TYPE_NONE = 0,
    AIM_TARGET_TYPE_AUGMENTED_REALITY = 1,
    AIM_TARGET_TYPE_AIM_ASSIST = 2,
    AIM_TARGET_TYPE_SYNC_MELEE = 4,
    AIM_TARGET_TYPE_MELEE = 8,
    AIM_TARGET_TYPE_ANY = 2147483647
};
