enum aimAssistTargetStatus_t : int
{
    AIM_ASSIST_TARGET_STATUS_DENIED = 0,
    AIM_ASSIST_TARGET_STATUS_APPROVED = 1,
    AIM_ASSIST_TARGET_STATUS_PENDING = 2,
    AIM_ASSIST_TARGET_STATUS_MAX = 3
};
