enum aiMoveStatus_t : int
{
    AIMOVESTATUS_DONE = 0,
    AIMOVESTATUS_MOVING = 1,
    AIMOVESTATUS_MOVE_PENDING = 2,
    AIMOVESTATUS_OBSTRUCTED_BY_DOOR = 3,
    AIMOVESTATUS_NOT_IN_AAS = 4,
    AIMOVESTATUS_ERROR = 5,
    AIMOVESTATUS_NO_AAS = 6,
    AIMOVESTATUS_INVALID_ENTITY = 7,
    AIMOVESTATUS_UNREACHABLE = 8,
    AIMOVESTATUS_PATHING_FAILED = 9,
    AIMOVESTATUS_OBSTRUCTED = 10,
    AIMOVESTATUS_NO_PATH_GROUP = 11,
    AIMOVESTATUS_NO_PATH_POINT = 12,
    AIMOVESTATUS_STUCK = 13,
    AIMOVESTATUS_ERROR_DONE = 14,
    AIMOVESTATUS_MAX = 15
};
