enum aiMovementMode_t : int
{
    AIMOVEMODE_STATIC = 0,
    AIMOVEMODE_GROUND = 1,
    AIMOVEMODE_AIR = 2,
    AIMOVEMODE_DEAD = 3,
    AIMOVEMODE_ANIM = 4,
    AIMOVEMODE_ANIM_TURN = 5,
    AIMOVEMODE_ANIM_GRAVITY = 6,
    AIMOVEMODE_ANIM_DRIVEN = 7,
    AIMOVEMODE_PLAYER = 8,
    AIMOVEMODE_BOUND = 9,
    AIMOVEMODE_MAX = 10
};
