enum aimPoint_t : int
{
    AIMPOINT_ORIGIN = 0,
    AIMPOINT_HEAD = 1,
    AIMPOINT_TORSO = 2,
    AIMPOINT_CENTER = 3,
    AIMPOINT_LEGS = 4,
    AIMPOINT_FEET = 5,
    AIMPOINT_LEFT_SHOULDER = 6,
    AIMPOINT_RIGHT_SHOULDER = 7,
    AIMPOINT_LEFT_FOOT = 8,
    AIMPOINT_RIGHT_FOOT = 9,
    AIMPOINT_MEAT_HOOK = 10,
    AIMPOINT_BEST = 11,
    AIMPOINT_EYELEVEL = 12,
    AIMPOINT_LOOKAHEAD = 13,
    AIMPOINT_MAX = 14
};
