enum aimPriority_t : int
{
    AIM_PRIORITY_NULL = 0,
    AIM_PRIORITY_LOOK_AT_MOVE_POINT = 1,
    AIM_PRIORITY_LOOK_AT_POI = 2,
    AIM_PRIORITY_BEHAVIOR_DRIVEN = 3,
    AIM_PRIORITY_COMBAT_BEHAVIOR_DRIVEN = 4,
    AIM_PRIORITY_LOOK_AT_SPECIAL_MOVE_POINT = 5,
    AIM_PRIORITY_DEBUG_OVERRIDE = 6,
    AIM_PRIORITY_MAX = 7
};
