enum aiPlayerScoreEvent_t : int
{
    AI_PLAYER_SCORE_EVENT_CD_BFG_PUNCH = 0,
    AI_PLAYER_SCORE_EVENT_TALISMAN_COUNTER = 1,
    AI_PLAYER_SCORE_EVENT_SMM_COUNTER = 2,
    AI_PLAYER_SCORE_EVENT_ATTACK_CANCELED = 3,
    AI_PLAYER_SCORE_EVENT_MAX = 4
};
