enum aiPositionFlags_t : int
{
    AIPOSITION_NONE = 0,
    AIPOSITION_BOUNDS_CONFLICT_MAJOR = 1,
    AIPOSITION_BOUNDS_CONFLICT_MINOR = 2,
    AIPOSITION_MELEE_CONFLICT_MAJOR = 4,
    AIPOSITION_MELEE_CONFLICT_MINOR = 8,
    AIPOSITION_RANGED_CONFLICT_MAJOR = 16,
    AIPOSITION_RANGED_CONFLICT_MINOR = 32,
    AIPOSITION_PATH_CONFLICT_MAJOR = 64,
    AIPOSITION_PATH_CONFLICT_MINOR = 128,
    AIPOSITION_MAX_CERTAIN = 256,
    AIPOSITION_BOUNDS_CONFLICT_MAJOR_UNCERTAIN = 512,
    AIPOSITION_BOUNDS_CONFLICT_MINOR_UNCERTAIN = 1024,
    AIPOSITION_MELEE_CONFLICT_MAJOR_UNCERTAIN = 2048,
    AIPOSITION_MELEE_CONFLICT_MINOR_UNCERTAIN = 4096,
    AIPOSITION_RANGED_CONFLICT_MAJOR_UNCERTAIN = 8192,
    AIPOSITION_RANGED_CONFLICT_MINOR_UNCERTAIN = 16384,
    AIPOSITION_PATH_CONFLICT_MAJOR_UNCERTAIN = 32768,
    AIPOSITION_PATH_CONFLICT_MINOR_UNCERTAIN = 65536
};
