enum aiStateFlags_t : unsigned int
{
    FLAG_NONE = 0,
    FLAG_DISABLE_OFF_LIMITS_CURRENT = 2,
    FLAG_DISABLE_OFF_LIMITS_PENDING = 4,
    FLAG_SUPPRESS_ANIMWEB_FAILSAFE = 8,
    FLAG_NO_REENTRY = 16,
    FLAG_PIPE_IO_IN = 32,
    FLAG_PIPE_IO_IN_AFTER_SNIPPETS = 64,
    FLAG_PIPE_IO_OUT = 128,
    FLAG_UPDATE_IMMEDIATELY = 256,
    FLAG_OR_CONDITIONS = 512,
    FLAG_PIPE_IO_FULL = 1024,
    FLAG_FORCE_GROUP_STATE = 2048,
    FLAG_DISABLE_WORK = 4096
};
