enum aiStimulus_t : int
{
    AISTIMULUS_NONE = 0,
    AISTIMULUS_HEARING = 1,
    AISTIMULUS_TOUCH = 2,
    AISTIMULUS_DAMAGE = 3,
    AISTIMULUS_GUNFIRE = 4,
    AISTIMULUS_GROUP_SUSPECTED = 5,
    AISTIMULUS_GROUP_CONFIRMED = 6,
    AISTIMULUS_TRIGGER = 7,
    AISTIMULUS_SIGHT = 8,
    AISTIMULUS_SIGHT_COVER = 9,
    AISTIMULUS_DAMAGE_BLIND = 10,
    AISTIMULUS_TOUCH_BLIND = 11,
    AISTIMULUS_MAX = 12
};
