enum aiSummonType_t : unsigned int
{
    SUMMONTYPE_NONE = 0,
    SUMMONTYPE_ZOMBIE_1 = 1,
    SUMMONTYPE_FODDER = 2,
    SUMMONTYPE_SUPPORT = 4,
    SUMMONTYPE_HEAVY = 8,
    SUMMONTYPE_SUPERHEAVY = 16,
    SUMMONTYPE_RANGED = 32,
    SUMMONTYPE_MELEE = 64
};
