enum alertCycle_t : int
{
    ALERTCYCLE_RELAXED = 1,
    ALERTCYCLE_SEARCH = 2,
    ALERTCYCLE_COMBAT = 3,
    ALERTCYCLE_PAIN = 4,
    ALERTCYCLE_DYING = 5,
    ALERTCYCLE_DEAD = 6,
    ALERTCYCLE_ANIMATE = 7,
    ALERTCYCLE_AVOID = 8,
    ALERTCYCLE_CONTROLLED = 9,
    ALERTCYCLE_ERROR = 10,
    ALERTCYCLE_MAX = 11
};
