enum animQueryTestOptions_t : unsigned int
{
    TF_NONE = 0,
    TF_ACTION = 2,
    TF_INCLUDE_MOVEMENT_INTENTS = 4,
    TF_NAV_PATH_LENGTH = 8,
    TF_TEST_ON_PATH = 16,
    TF_NO_TRAVERSALS_ON_PATH = 32,
    TF_OR_TRACE_TO_ENEMY = 64,
    TF_TRACE_TO_ENEMY_HEAD = 128,
    TF_FOV_XY_ONLY = 256,
    TF_UPWARD_GROUND_CLAMP = 512,
    TF_FOV_SKIP_CROSS_WHEN_AIMED_AT = 1024,
    TF_DONT_FLUSH_PATHFINDS = 2048,
    TF_USE_NAV_HEIGHT_CHECKS = 4096,
    TF_IGNORE_ZERO_FRACTION_GROUND_CLAMP = 8192
};
