enum animSelectionCriteria_t : int
{
    ANIMSELECT_NONE = 0,
    ANIMSELECT_TARGET_DISTANCE = 1,
    ANIMSELECT_NAVIGATION = 2,
    ANIMSELECT_TIMERS = 4,
    ANIMSELECT_DAMAGE = 8,
    ANIMSELECT_COST = 16,
    ANIMSELECT_COLLISION = 32,
    ANIMSELECT_AI_INTENTS = 64,
    ANIMSELECT_VISIBILITY = 128,
    ANIMSELECT_PATH_DISTANCE = 256,
    ANIMSELECT_PATH_RATIO = 512,
    ANIMSELECT_DIRECTION = 1024,
    ANIMSELECT_BLOCKERS = 2048,
    ANIMSELECT_TETHER_RADIUS = 4096,
    ANIMSELECT_MIN_DISTANCE_FROM_CURRENT = 8192,
    ANIMSELECT_VALIDATE_ATTACK_MAPPINGS = 16384
};
