enum animEntityPerformanceLog_t : int
{
    ANIMENT_PERFLOG_START = 1,
    ANIMENT_PERFLOG_UPDATEANIMATION = 1,
    ANIMENT_PERFLOG_UPDATEATTACHMENTS = 2,
    ANIMENT_PERFLOG_UPDATEVISUALS = 3,
    ANIMENT_PERFLOG_ANIMATOR_UPDATEANIMATION = 4,
    ANIMENT_PERFLOG_ANIMATOR_CREATEFRAME = 5,
    ANIMENT_PERFLOG_UPDATEFRAMECOMMANDS = 6,
    ANIMENT_PERFLOG_COMPUTEJOINTS = 7,
    ANIMENT_PERFLOG_MAX = 8
};
