enum animWebEdgeCustomFlag_t : int
{
    AW_EDGE_INPUT_WIN1 = 1,
    AW_EDGE_INPUT_LOSE1 = 2,
    AW_EDGE_INPUT_WIN2 = 4,
    AW_EDGE_INPUT_LOSE2 = 8,
    AW_EDGE_INPUT_FORCE_ON_LOSE = 64,
    AW_EDGE_INPUT_FORCE_ON_DAMAGE = 128,
    AW_EDGE_INPUT_FORCE_ON_DEATH = 256
};
