enum animValidationSelectionType_t : int
{
    CHOOSE_ANGLE_DISTANCE_ERROR = 0,
    CHOOSE_CLOSEST_TO_DESTINATION = 1,
    CHOOSE_CLOSEST_TO_SEGMENT = 2,
    CHOOSE_CLOSEST_ANGLE_START = 3,
    CHOOSE_CLOSEST_TO_PATH_RELATIVE = 4
};
