enum animDeltaCorrectionCategory_t : int
{
    DELTA_CORRECTION_CATEGORY_NONE = 0,
    DELTA_CORRECTION_CATEGORY_LOCOMOTION = 1,
    DELTA_CORRECTION_CATEGORY_TRAVERSAL = 2,
    DELTA_CORRECTION_CATEGORY_ATTACKS = 4,
    DELTA_CORRECTION_CATEGORY_DODGE = 8,
    DELTA_CORRECTION_CATEGORY_CORRECT_TO_GROUND = 16,
    DELTA_CORRECTION_CATEGORY_ENTRANCE_ANIM = 32
};
