enum animatedPerformanceLog_t : int
{
    ANIMATED_PERFLOG_START = 1,
    ANIMATED_PERFLOG_SPAWN = 1,
    ANIMATED_PERFLOG_THINK = 2,
    ANIMATED_PERFLOG_BLENDTRACKER_UPDATE = 3,
    ANIMATED_PERFLOG_PHYSICS = 4,
    ANIMATED_PERFLOG_UPDATEANIMATION = 5,
    ANIMATED_PERFLOG_PRESENT = 6,
    ANIMATED_PERFLOG_LINKCOMBAT = 7,
    ANIMATED_PERFLOG_STARTNEXTANIM = 8,
    ANIMATED_PERFLOG_UPDATEATTACHMENTS = 9,
    ANIMATED_PERFLOG_UPDATEFRAMECOMMANDS = 10,
    ANIMATED_PERFLOG_MAX = 11
};
