enum animQueryRejectReason_t : unsigned int
{
    INVALID = 0,
    NONE = 1,
    UNALIGNED_SOURCE = 2,
    UNALIGNED_MOVE = 3,
    UNALIGNED_APEX = 4,
    OUTOFRANGE = 5,
    NEEDMORETURN = 6,
    NAVPROBEFAIL = 7,
    REQUIRED_FLAG_MISMATCH = 8,
    ALLOWED_FLAG_MISMATCH = 9,
    NAVPROBEFAIL_APEX = 10,
    NAVPROBEFAIL_TRANS = 11,
    NAVPROBEFAIL_END_TO_PATH = 12,
    WAITING_FOR_TRACE = 13,
    ANIM_OVERSHOOT = 14,
    LONGER_PATH = 15,
    WRONG_INJURY = 16,
    MAX = 17
};
