enum arGuiScreen_t : int
{
    ARGUI_SCREEN_INVALID = -1,
    ARGUI_SCREEN_ECHO_INDICATOR = 0,
    ARGUI_SCREEN_GENERIC_TEXT = 1,
    ARGUI_AR_LOOT_HEALTH = 2,
    ARGUI_AR_LOOT_ARMOR = 3,
    ARGUI_AR_LOOT_AMMO = 4,
    ARGUI_AR_LOOT_ENERGY = 5,
    ARGUI_LOOT_TIMER = 6,
    ARGUI_TURRET = 7,
    ARGUI_TUTORIAL = 8,
    ARGUI_SCREEN_CUSTOM = 9,
    MAX_ARGUI_SCREENS = 10
};
