enum assertCategory_t : int
{
    ASSERTCATEGORY_unskippable = 0,
    ASSERTCATEGORY_general = 1,
    ASSERTCATEGORY_clip = 2,
    ASSERTCATEGORY_ai = 3,
    ASSERTCATEGORY_inventory = 4,
    ASSERTCATEGORY_ui = 5,
    ASSERTCATEGORY_anim = 6,
    ASSERTCATEGORY_render = 7,
    ASSERTCATEGORY_resource = 8,
    ASSERTCATEGORY_jailed = 9,
    ASSERTCATEGORY_skippable = 10,
    ASSERTCATEGORY_weapon = 11,
    ASSERTCATEGORY_script = 12,
    ASSERTCATEGORY_sound = 13,
    ASSERTCATEGORY_syncmelee = 14,
    ASSERTCATEGORY_fx = 15,
    ASSERTCATEGORY_game = 16,
    ASSERTCATEGORY_backend = 17,
    ASSERTCATEGORY_physics = 18,
    ASSERTCATEGORY_player = 19,
    ASSERTCATEGORY_jobs = 20,
    ASSERTCATEGORY_cvar = 21,
    ASSERTCATEGORY_events = 22,
    ASSERTCATEGORY_typeinfo = 23,
    ASSERTCATEGORY_gore = 24,
    ASSERTCATEGORY_math = 25,
    ASSERTCATEGORY_tools = 26,
    ASSERTCATEGORY_do_not_check_in = 27
};
