enum asyncGPUContext_t : int
{
    ASYNC_CONTEXT_CULLING = 0,
    ASYNC_CONTEXT_DEFERRED_PASSES_PREPARE = 1,
    ASYNC_CONTEXT_GPU_PARTICLES = 2,
    ASYNC_CONTEXT_STREAMING = 3,
    ASYNC_CONTEXT_WATER = 4,
    ASYNC_CONTEXT_POST_PROCESSES = 5,
    ASYNC_CONTEXT_TSSAA = 6,
    ASYNC_CONTEXT_NUM = 7
};
