enum awCmdBlendEvent_t : int
{
    AWCMD_EVENT_NONE = 0,
    AWCMD_EVENT_DEST_BLEND_START = 1,
    AWCMD_EVENT_DEST_BLEND_END = 2,
    AWCMD_EVENT_DEST_CLAMPED = 3,
    AWCMD_EVENT_VIA_BLEND_IN_START = 4,
    AWCMD_EVENT_VIA_BLEND_IN_END = 5,
    AWCMD_EVENT_VIA_BLEND_OUT_START = 6,
    AWCMD_EVENT_VIA_BLEND_OUT_END = 7,
    AWCMD_EVENT_CLAMP_NEXT_FRAME = 8,
    AWCMD_EVENT_STICK_HANDLE = 9,
    AWCMD_EVENT_TRAVERSAL_CHAIN = 10
};
