enum awCmdStatus_t : int
{
    AWCMD_STATUS_INVALID = -1,
    AWCMD_STATUS_OK = 0,
    AWCMD_STATUS_IGNORED = 1,
    AWCMD_STATUS_DENIED = 2,
    AWCMD_STATUS_LOCKED = 3,
    AWCMD_STATUS_CMDERR = 4,
    AWCMD_STATUS_PATHERR = 5,
    AWCMD_STATUS_INVALID_DEST = 6,
    AWCMD_STATUS_INVALID_VIA = 7,
    AWCMD_STATUS_WAITING = 8,
    AWCMD_STATUS_INTERRUPTED = 9,
    AWCMD_STATUS_ABORTED = 10,
    AWCMD_STATUS_READY_TO_COMPLETE = 11,
    AWCMD_STATUS_DONE = 12
};
