enum battleArenaRoundUpgrades_screenID_t : int
{
    MENU_BATTLE_ARENA_ROUNDUPGRADES_MAIN = 0,
    MENU_BATTLE_ARENA_ROUNDUPGRADES_SETTINGS = 1,
    MENU_BATTLE_ARENA_ROUNDUPGRADES_SOCIAL = 2,
    BATTLE_ARENA_ROUNDUPGRADES_OVERLAY = 3
};
