enum battleArenaLobby_screenID_t : int
{
    MENU_BATTLE_ARENA_LOBBY_MAIN = 0,
    MENU_BATTLE_ARENA_LOBBY_SETTINGS = 1,
    MENU_BATTLE_ARENA_LOBBY_OPTIONS = 2,
    MENU_BATTLE_ARENA_LOBBY_PLAYER_SETUP = 3
};
