enum behaviorGoalTypes_t : int
{
    BEHAVIOR_GOAL_TYPE_ANY = 1,
    BEHAVIOR_GOAL_TYPE_ESCORT = 2,
    BEHAVIOR_GOAL_TYPE_ROAM = 4,
    BEHAVIOR_GOAL_TYPE_CAPTURE = 8,
    BEHAVIOR_GOAL_TYPE_DEFEND = 16,
    BEHAVIOR_GOAL_TYPE_PATROL = 32,
    BEHAVIOR_GOAL_TYPE_REVIVE = 64,
    BEHAVIOR_GOAL_TYPE_POSITION_BASED = 536870912,
    BEHAVIOR_GOAL_TYPE_ENTITY_BASED = 1073741824,
    BEHAVIOR_GOAL_TYPE_NULL = -2147483648
};
