enum bethnetSubScreenID_t : int
{
    BETHNET_SUBSCREEN_NONE = -1,
    BETHNET_SUBSCREEN_SIGN_IN = 0,
    BETHNET_SUBSCREEN_CREATE_ACCOUNT = 1,
    BETHNET_SUBSCREEN_UPDATED_AGREEMENTS = 2,
    NUM_BETHNET_SUBSCREENS = 3
};
