enum blendMode_t : int
{
    BLEND_SMOOTH = 0,
    BLEND_SMOOTH_SNAP_SMOOTH = 1,
    BLEND_SNAP_SNAP_SMOOTH = 2,
    BLEND_SNAP = 3,
    BLEND_FOLLOW_SNAP_LOOK_SMOOTH_SNAP_SMOOTH = 4,
    BLEND_FOLLOW_SNAP_LOOK_SMOOTH = 5,
    BLEND_MAX = 6
};
