enum bossKMAnimEvents_t : int
{
    BOSS_KM_AE_START_RAISE_SHIELD = 0,
    BOSS_KM_AE_START_DROP_SHIELD = 1,
    BOSS_KM_AE_START_PURIFYING_BEAM = 2,
    BOSS_KM_AE_ACTIVATE_BENEDICTION_SPAWNER = 3,
    BOSS_KM_AE_START_BENEDICTION_BUFF = 4,
    BOSS_KM_AE_ACTIVATE_MASS_SUMMON_SPAWNER = 5,
    BOSS_KM_AE_START_SACRIFICE_START = 6,
    BOSS_KM_AE_START_SACRIFICE_EXPLOSION = 7,
    BOSS_KM_AE_START_DIVINE_BANDS = 8,
    BOSS_KM_AE_STOP_DIVINE_BANDS = 9,
    BOSS_KM_AE_FIRE_HEAVY_SHOT = 10,
    BOSS_KM_AE_SECT_DESTROY_MINOR = 11,
    BOSS_KM_AE_SECT_DESTROY_MAJOR = 12,
    BOSS_KM_AE_AERIAL_BUILD_LEFT_DATA = 13,
    BOSS_KM_AE_AERIAL_BUILD_RIGHT_DATA = 14,
    BOSS_KM_AE_REPEL_PLAYER = 15,
    BOSS_KM_COUNT = 16
};
