enum bossDHunterAnimEvents_t : int
{
    BOSS_DH_AE_SPAWN_MINIONS = 0,
    BOSS_DH_AE_SHOW_CHAINSAW = 1,
    BOSS_DH_AE_HIDE_CHAINSAW = 2,
    BOSS_DH_AE_SPAWN_EXPLODING_CHAINSAW = 3,
    BOSS_DH_AE_LOCK_MINE_SCALE = 4,
    BOSS_DH_COUNT = 5
};
