enum bossSamuelAnimEvents_t : int
{
    BOSS_SAM_AE_RAPID_SHOT_LEFT = 0,
    BOSS_SAM_AE_RAPID_SHOT_RIGHT = 1,
    BOSS_SAM_AE_SPAWN_TENDRIL_EYE = 2,
    BOSS_SAM_AE_START_PHASE2 = 3,
    BOSS_SAM_AE_SPIRIT_SUMMON_COMPLETE = 4,
    BOSS_SAM_COUNT = 5
};
