enum botActionFlags_t : int
{
    BOT_ACTION_FLAG_NONE = 0,
    BOT_ACTION_FLAG_ATTACK = 1,
    BOT_ACTION_FLAG_ALT_ATTACK = 2,
    BOT_ACTION_FLAG_REVIVE = 4,
    BOT_ACTION_FLAG_CHANGE_WEAPON_MOD = 8,
    BOT_ACTION_FLAG_MELEE = 16,
    BOT_ACTION_FLAG_ZOOM = 32,
    BOT_ACTION_FLAG_QUICK_USE = 64,
    BOT_ACTION_FLAG_RELEASE_SPRINT_BUTTON = 128
};
