enum botActiveStatusEffectsType_t : int
{
    BOT_ACTIVE_STATUS_EFFECT_NONE = 0,
    BOT_ACTIVE_STATUS_EFFECT_QUAD_DAMAGE = 1,
    BOT_ACTIVE_STATUS_EFFECT_INVISIBILITY = 2,
    BOT_ACTIVE_STATUS_EFFECT_HASTE = 4,
    BOT_ACTIVE_STATUS_EFFECT_REGENERATION = 8
};
