enum botDebugGuiType_t : int
{
    BOT_DEBUG_GUI_TYPE_HUD = 0,
    BOT_DEBUG_GUI_TYPE_WORLD = 1,
    BOT_DEBUG_GUI_TYPE_BEHAVIOR = 2,
    BOT_DEBUG_GUI_TYPE_TARGETS = 3,
    BOT_DEBUG_GUI_TYPE_HIGH_LEVEL = 4,
    BOT_DEBUG_GUI_TYPE_MAX = 5
};
