enum botEntityType_t : int
{
    BOT_ENTITY_TYPE_NULL = 0,
    BOT_ENTITY_TYPE_PLAYER = 1,
    BOT_ENTITY_TYPE_LOOT_PICKUP = 2,
    BOT_ENTITY_TYPE_LOOT_DISPENSER = 4,
    BOT_ENTITY_TYPE_AI = 8,
    BOT_ENTITY_TYPE_TURRET = 16,
    BOT_ENTITY_TYPE_DEMON_PLAYER = 32,
    BOT_ENTITY_TYPE_MAX = 33
};
