enum botEntityFlags_t : int
{
    BOT_ENTITY_FLAGS_NULL = 0,
    BOT_ENTITY_FLAGS_HEALTH = 1,
    BOT_ENTITY_FLAGS_ARMOR = 2,
    BOT_ENTITY_FLAGS_AMMO = 4,
    BOT_ENTITY_FLAGS_WEAPON = 8,
    BOT_ENTITY_FLAGS_EXPLOSIVE = 16,
    BOT_ENTITY_FLAGS_TARGETABLE = 32,
    BOT_ENTITY_FLAGS_NAV_OBSTACLE = 64,
    BOT_ENTITY_FLAGS_OBJECTIVE = 128,
    BOT_ENTITY_FLAGS_AVOID = 256,
    BOT_ENTITY_FLAGS_TRACEABLE = 512,
    BOT_ENTITY_FLAGS_COVER_USER = 1024,
    BOT_ENTITY_FLAGS_NOT_WALKABLE = 2048,
    BOT_ENTITY_FLAGS_POWERUP = 4096,
    BOT_ENTITY_FLAGS_POWER_WEAPON = 8192,
    BOT_ENTITY_FLAGS_MAX = -2147483648
};
