enum botRegressionTypes_t : int
{
    BOT_REGRESSION_ISSUE_NO_AAS = 0,
    BOT_REGRESSION_ISSUE_NULL_INVENTORY = 1,
    BOT_REGRESSION_ISSUE_WEAPONS_NOT_SETUP = 2,
    BOT_REGRESSION_ISSUE_WEAPON_MISSING_DEF = 3,
    BOT_REGRESSION_ISSUE_INVENTORY_EMPTY = 4,
    BOT_REGRESSION_ISSUE_LOADOUT_ERROR = 5,
    BOT_REGRESSION_ISSUE_NULL_WEAPON_LOADOUT = 6,
    BOT_REGRESSION_ISSUE_NO_COVER_NODES_IN_AAS = 7,
    BOT_REGRESSION_ISSUE_INCORRECTLY_SETUP_COVER_NODES_IN_AAS = 8,
    BOT_REGRESSION_ISSUE_WEAPON_INTERVAL_NOT_SETUP = 9,
    BOT_REGRESSION_ISSUE_NO_WEAPONS_IN_INVENTORY = 10,
    BOT_REGRESSION_ISSUE_BOUNCE_PAD_CANT_HIT_BOT_DESTINATION = 11,
    BOT_REGRESSION_ISSUE_NO_SPAWN_NODES_EXIST = 12,
    BOT_REGRESSION_ISSUE_SPAWN_NODE_NOT_IN_AAS = 13,
    BOT_REGRESSION_ISSUE_LOOT_ITEM_NOT_IN_AAS = 14,
    BOT_REGRESSION_ISSUE_ROUTE_NODE_CANT_REACH_GOAL = 15,
    BOT_REGRESSION_ISSUE_ROUTE_NODE_GOAL_NOT_ON_AAS = 16,
    BOT_REGRESSION_ISSUE_PATH_NODE_NOT_ON_AAS = 17,
    BOT_REGRESSION_ISSUE_NON_ROUTE_PATH_NODE_IN_MAP = 18,
    BOT_REGRESSION_ISSUE_PRIMARY_NAVMESH_NOT_AVAILABLE_USING_FALLBACK = 19,
    BOT_REGRESSION_ISSUE_MAX = 20
};
