enum botWeaponPriority_t : int
{
    WEAPON_PRIORITY_NULL = 0,
    WEAPON_PRIORITY_LOW_LEVEL_DRIVEN = 1,
    WEAPON_PRIORITY_BEHAVIOR_DRIVEN = 2,
    WEAPON_PRIORITY_COMBAT_BEHAVIOR_DRIVEN = 3,
    WEAPON_PRIORITY_MAX = 4
};
