enum calloutIdentifierType_t : int
{
    CALLOUT_IDENTIFIER_GLOBAL = 0,
    CALLOUT_IDENTIFIER_ALLY = 1,
    CALLOUT_IDENTIFIER_ENEMY = 2,
    CALLOUT_IDENTIFIER_SELF = 3,
    CALLOUT_IDENTIFIER_SPECTATOR = 4
};
