enum campaignManagerEvent_t : int
{
    CAMPAIGN_MANAGER_EVENT_AVAILABILITY_REFRESH_START = 0,
    CAMPAIGN_MANAGER_EVENT_AVAILABILITY_REFRESH_COMPLETE = 1,
    CAMPAIGN_MANAGER_EVENT_AVAILABILITY_REFRESH_SKIPPED = 2
};
