enum chatVoiceIndicator_t : unsigned char
{
    CHAT_VOICE_INDICATOR_NO_INPUT_DEVICE = 0,
    CHAT_VOICE_INDICATOR_MUTED_LOCAL = 1,
    CHAT_VOICE_INDICATOR_MUTED_REMOTE = 2,
    CHAT_VOICE_INDICATOR_SILENT = 3,
    CHAT_VOICE_INDICATOR_TALKING = 4
};
