enum clockManagerEvent_t : int
{
    CLOCK_MANAGER_EVENT_INVALID = -1,
    CLOCK_MANAGER_EVENT_GAME_PLAY_TIME_RESET = 0,
    CLOCK_MANAGER_EVENT_RUN_TIME_SUSPENDED = 1,
    CLOCK_MANAGER_EVENT_IDLE_STARTED = 2,
    CLOCK_MANAGER_EVENT_IDLE_ENDED = 3,
    CLOCK_MANAGER_EVENT_MAX = 4
};
