enum codexDisplayStyle_t : int
{
    CODEX_DISPLAY_STYLE_NONE = -1,
    CODEX_DISPLAY_STYLE_UNDISCOVERED = 0,
    CODEX_DISPLAY_STYLE_TEXT_ONLY = 1,
    CODEX_DISPLAY_STYLE_IMAGE_ONLY = 2,
    CODEX_DISPLAY_STYLE_IMAGE_HORIZONTAL = 3,
    CODEX_DISPLAY_STYLE_IMAGE_VERTICAL = 4,
    CODEX_DISPLAY_STYLE_TUTORIAL = 5,
    CODEX_DISPLAY_STYLE_IMAGE_FULLSCREEN = 6,
    CODEX_DISPLAY_STYLE_IMAGE_DEMON = 7,
    CODEX_DISPLAY_STYLE_IMAGE_DEMON_TIPS_ONLY = 8,
    CODEX_DISPLAY_STYLE_TEXT_SCROLL = 9,
    NUM_CODEX_DISPLAY_STYLES = 10
};
