enum combinedProgramType_t : int
{
    COMBINED_PROGRAM_TYPE_VS = 0,
    COMBINED_PROGRAM_TYPE_VSPS = 1,
    COMBINED_PROGRAM_TYPE_VSGS = 2,
    COMBINED_PROGRAM_TYPE_VSGSPS = 3,
    COMBINED_PROGRAM_TYPE_NUM = 4
};
