enum commandBufferType_t : int
{
    COMMAND_BUFFER_TYPE_EXPIRATION = 0,
    COMMAND_BUFFER_TYPE_INITIALIZATION = 1,
    COMMAND_BUFFER_TYPE_SIMULATION = 2,
    COMMAND_BUFFER_TYPE_RENDERING = 3,
    COMMAND_BUFFER_TYPE_MAX = 4
};
