enum coopHazardDamage_t : int
{
    COOP_HAZARD_DAMAGE_FIRE = 0,
    COOP_HAZARD_DAMAGE_ELECTRICITY = 1,
    COOP_HAZARD_DAMAGE_RADIATION = 2,
    COOP_HAZARD_DAMAGE_POISON = 3,
    COOP_HAZARD_DAMAGE_MAX = 4
};
