enum coordVector_t : int
{
    COORD_VECTOR_X_NEGATIVE = -1,
    COORD_VECTOR_X_POSITIVE = 1,
    COORD_VECTOR_Y_NEGATIVE = -2,
    COORD_VECTOR_Y_POSITIVE = 2,
    COORD_VECTOR_Z_NEGATIVE = -3,
    COORD_VECTOR_Z_POSITIVE = 3
};
