enum corruptionType_t : int
{
    CORRUPTION_TYPE_INVALID = -1,
    CORRUPTION_TYPE_COMBAT = 0,
    CORRUPTION_TYPE_SLAYER_GATE = 1,
    CORRUPTION_TYPE_SECRET_ENCOUNTER = 2,
    CORRUPTION_TYPE_ESCALATION_ENCOUNTER = 3,
    CORRUPTION_TYPE_BOSS = 4,
    CORRUPTION_TYPE_COUNT = 5
};
