enum damageDirection_t : int
{
    DAMAGEDIR_NONE = 0,
    DAMAGEDIR_FRONT = 1,
    DAMAGEDIR_BACK = 2,
    DAMAGEDIR_LEFT = 3,
    DAMAGEDIR_RIGHT = 4,
    DAMAGEDIR_FRONTLEFT = 5,
    DAMAGEDIR_FRONTRIGHT = 6,
    DAMAGEDIR_BACKLEFT = 7,
    DAMAGEDIR_BACKRIGHT = 8,
    DAMAGEDIR_MAX = 9
};
