enum dataRateStat_t : int
{
    DATA_RATE_TOTAL_OUTGOING = 0,
    DATA_RATE_TOTAL_INCOMING = 1,
    DATA_RATE_RELIABLE_OUTGOING_C = 2,
    DATA_RATE_RELIABLE_OUTGOING_U = 3,
    DATA_RATE_RELIABLE_INCOMING_C = 4,
    DATA_RATE_RELIABLE_INCOMING_U = 5,
    DATA_RATE_MAX = 6
};
