enum declAFConstraintType_t : int
{
    DECLAF_CONSTRAINT_INVALID = 0,
    DECLAF_CONSTRAINT_FIXED = 1,
    DECLAF_CONSTRAINT_BALLANDSOCKETJOINT = 2,
    DECLAF_CONSTRAINT_UNIVERSALJOINT = 3,
    DECLAF_CONSTRAINT_HINGE = 4,
    DECLAF_CONSTRAINT_SLIDER = 5,
    DECLAF_CONSTRAINT_SPRING = 6,
    DECLAF_CONSTRAINT_MAX_EDITABLE = 7,
    DECLAF_CONSTRAINT_CONE_LIMIT = 8,
    DECLAF_CONSTRAINT_PYRAMID_LIMIT = 9,
    DECLAF_CONSTRAINT_BSJ_TWIST_LIMIT = 10,
    DECLAF_CONSTRAINT_BSJ_HINGE_LIMIT = 11,
    DECLAF_CONSTRAINT_HINGE_LIMIT = 12,
    DECLAF_CONSTRAINT_HINGE_STEERING = 13,
    DECLAF_CONSTRAINT_HINGE_FRICTION = 14
};
