enum deferredFakePathParmsType_t : int
{
    FAKEPATH_ADD = 0,
    FAKEPATH_STREAM = 1,
    FAKEPATH_UPDATE = 2,
    FAKEPATH_COLLAPSE = 3,
    FAKEPATH_END = 4,
    FAKEPATH_GOAL_FX_ENTITY_SPAWN_ON_PATH = 5,
    FAKEPATH_GOAL_FX_ENTITY_SPAWN_AT_POS = 6,
    FAKEPATH_MAX = 7
};
