enum demonHudColor_t : int
{
    DEMON_HUD_COLOR_NONE = 0,
    DEMON_HUD_COLOR_TEAL = 1,
    DEMON_HUD_COLOR_YELLOW = 2,
    DEMON_HUD_COLOR_ORANGE = 3,
    DEMON_HUD_COLOR_BLUE = 4,
    DEMON_HUD_COLOR_PURPLE = 5,
    DEMON_HUD_COLOR_RED = 6,
    DEMON_HUD_COLOR_GREEN = 7,
    DEMON_HUD_COLOR_SLAYER_GREEN = 8,
    DEMON_HUD_COLOR_MAX = 9
};
