enum demonScoringActionsPvp_t : int
{
    DSA_INVALID = -1,
    DSA_DAMAGE_SLAYER = 0,
    DSA_KILL_SLAYER = 1,
    DSA_HAZARD_SLAYER = 2,
    DSA_SPAWN_AI = 3,
    DSA_SUMMONED_DAMAGE_SLAYER = 4,
    DSA_HEAL_TEAMMATE = 5,
    DSA_NO_DEMON_PLAYER_DEATH_ROUND = 6,
    DSA_DAMAGE_SLAYER_FROM_DISGUISE = 7,
    DSA_FIRST_BLOOD_FROM_DISGUISE = 8,
    DSA_VANISHED_FROM_SLAYER = 9,
    DSA_MAX = 10
};
