enum descriptorSetBindPoint_t : int
{
    DSBP_VIEW_CONSTANT_BUFFER = 0,
    DSBP_INSTANCE_CONSTANT_BUFFER = 1,
    DSBP_SURFACE_CONSTANT_BUFFER = 2,
    DSBP_RENDER_LAYER_UNIFORM_VIEW = 3,
    DSBP_VIEW_BUFFER_VIEWS = 4,
    DSBP_VIEW_SAMPLERS = 5,
    DSBP_INSTANCE_BUFFER_VIEWS = 6,
    DSBP_SURFACE_BUFFER_VIEWS = 7,
    DSBP_ROOT_CONSTANTS = 8,
    DSBP_RENDER_LAYER_BUFFER_VIEWS = 9,
    DSBP_GLOBAL_TEXTURE_VIEWS = 10,
    DSBP_NUM = 11
};
