enum dialogFlag_t : int
{
    DIALOG_FLAG_PAUSE = 1,
    DIALOG_FLAG_LEAVE_ON_CLEAR = 2,
    DIALOG_FLAG_RENDER_DURING_LOAD = 4,
    DIALOG_FLAG_CLEAR_ON_CONNECT_TO_LOBBY = 8,
    DIALOG_FLAG_DEFERRED_CLEAR = 16
};
