enum dialogMenuNotificationIcon_t : int
{
    DIALOG_MENU_NOTIFICATION_ICON_SOCIAL = 0,
    DIALOG_MENU_NOTIFICATION_ICON_YOU_GOT_STUFF = 1,
    DIALOG_MENU_NOTIFICATION_ICON_NETWORK_DISCONNECT = 2,
    DIALOG_MENU_NOTIFICATION_ICON_PARTY_LEADER = 3,
    DIALOG_MENU_NOTIFICATION_ICON_BOOSTER = 4,
    MAX_DIALOG_MENU_NOTIFICATION_ICONS = 5
};
