enum dialogType_t : int
{
    DIALOG_INVALID = -1,
    DIALOG_ACCEPT = 0,
    DIALOG_CONTINUE = 1,
    DIALOG_REFRESH_CONTINUE = 2,
    DIALOG_RETRY_OFFLINE = 3,
    DIALOG_RETRY_CONTINUE = 4,
    DIALOG_ACCEPT_CANCEL = 5,
    DIALOG_ACCEPT_CANCEL_DELAY = 6,
    DIALOG_YES_NO = 7,
    DIALOG_CANCEL = 8,
    DIALOG_WAIT = 9,
    DIALOG_WAIT_BLACKOUT = 10,
    DIALOG_WAIT_CANCEL = 11,
    DIALOG_DYNAMIC = 12,
    DIALOG_TIMER_ACCEPT_REVERT = 13,
    DIALOG_CONTINUE_LARGE = 14,
    DIALOG_BENCHMARK = 15,
    DIALOG_APOLOGIZE = 16
};
