enum doomLevelDisplayStyle_t : int
{
    DOOM_LEVEL_DISPLAY_STYLE_INVALID = -1,
    DOOM_LEVEL_DISPLAY_STYLE_FULL = 0,
    DOOM_LEVEL_DISPLAY_STYLE_MINI = 1,
    DOOM_LEVEL_DISPLAY_STYLE_NONE = 2,
    NUM_DOOM_LEVEL_DISPLAY_STYLES = 3
};
