enum dossierPage_t : int
{
    DOSSIER_PAGE_MAP = 0,
    DOSSIER_PAGE_ARSENAL = 1,
    DOSSIER_PAGE_SUIT = 2,
    DOSSIER_PAGE_RUNES = 3,
    DOSSIER_PAGE_CODEX = 4,
    DOSSIER_PAGE_CHALLENGES = 5,
    NUM_DOSSIER_PAGES = 6,
    DOSSIER_OVERLAY = 7
};
