enum eCombatRatingScale_t : int
{
    COMBAT_RATING_SCALE_SMALL = 0,
    COMBAT_RATING_SCALE_MEDIUM = 1,
    COMBAT_RATING_SCALE_LARGE = 2,
    COMBAT_RATING_SCALE_IGNORE = 3,
    COMBAT_RATING_SCALE_SLAYER_GATE = 4,
    COMBAT_RATING_SCALE_SLAYER_GATE_ZERO_WEAPON_POINTS = 5,
    COMBAT_RATING_SCALE_SECRET_ENCOUNTER = 6,
    COMBAT_RATING_SCALE_SECRET_ENCOUNTER_ZERO_WEAPON_POINTS = 7,
    COMBAT_RATING_SCALE_EXTRA_LIFE_ENCOUNTER = 8,
    COMBAT_RATING_SCALE_ESCALATION_ENCOUNTER = 9,
    COMBAT_RATING_SCALE_CHALLENGE_ENCOUNTER = 10,
    COMBAT_RATING_SCALE_BOSS_DOOM_HUNTER = 11,
    COMBAT_RATING_SCALE_BOSS_GLADIATOR = 12,
    COMBAT_RATING_SCALE_BOSS_KHAN_MAYKR = 13,
    COMBAT_RATING_SCALE_BOSS_ICON_OF_SIN = 14,
    COMBAT_RATING_SCALE_BOSS_SAMUEL = 15,
    COMBAT_RATING_SCALE_BOSS_DARKLORD = 16,
    COMBAT_RATING_SCALE_GOLD_BOSS = 17,
    COMBAT_RATING_SCALE_NEEDS_ASSIGNMENT = 18
};
