enum eEncounterEventFlags_t : int
{
    ENCOUNTER_EVENT_FLAG_PRE_COMBAT = 0,
    ENCOUNTER_EVENT_FLAG_COMMIT = 1,
    ENCOUNTER_EVENT_FLAG_EXIT = 2,
    ENCOUNTER_EVENT_FLAG_AI_AWARE_OF_PLAYER = 3,
    ENCOUNTER_EVENT_FLAG_USER_EVENT = 4,
    ENCOUNTER_EVENT_FLAG_COUNT = 5
};
