enum eEncounterEventLifecycle_t : int
{
    ENCOUNTER_EVENT_LIFECYCLE_ENCOUNTER_START = 0,
    ENCOUNTER_EVENT_LIFECYCLE_ENCOUNTER_PRE_COMBAT_START = 1,
    ENCOUNTER_EVENT_LIFECYCLE_ENCOUNTER_PAUSED = 2,
    ENCOUNTER_EVENT_LIFECYCLE_ENCOUNTER_ENDED = 3,
    ENCOUNTER_EVENT_LIFECYCLE_COUNT = 4
};
