enum eGameMutatorType : int
{
    GAME_MUTATOR_INVALID = -1,
    GAME_MUTATOR_NONE = 0,
    GAME_MUTATOR_DASH = 1,
    GAME_MUTATOR_CLASSIC = 2,
    GAME_MUTATOR_USE_OR_LOSE = 3,
    GAME_MUTATOR_TUG_OF_WAR = 4,
    GAME_MUTATOR_HEALTH_GUNS = 5,
    GAME_MUTATOR_TIME_ATTACK = 6,
    GAME_MUTATOR_MAX = 7
};
