enum endOfLevelRewardsScreens_t : int
{
    END_OF_LEVEL_REWARDS_SCREEN_SEASON = 0,
    END_OF_LEVEL_REWARDS_SCREEN_STATS = 1,
    END_OF_LEVEL_REWARDS_SCREEN_REWARDS = 2,
    NUM_END_OF_LEVEL_REWARDS_SCREENS = 3
};
