enum enum_D101 : int
{
    AAS_PATHTYPE_WALK = 0,
    AAS_PATHTYPE_WALKOFFLEDGE = 1,
    AAS_PATHTYPE_WALKOFFBARRIER = 2,
    AAS_PATHTYPE_BARRIERJUMP = 3,
    AAS_PATHTYPE_JUMP = 4,
    AAS_PATHTYPE_LADDER = 5,
    AAS_PATHTYPE_TELEPORT = 6,
    AAS_PATHTYPE_LEDGE_GRAB = 7,
    AAS_PATHTYPE_BREAKABLE_OBSTACLE = 8,
    AAS_PATHTYPE_ELEVATOR = 9,
    AAS_PATHTYPE_FLIGHT = 10,
    AAS_PATHTYPE_TRAVERSALANIM = 11,
    AAS_PATHTYPE_BOUNCE_PAD = 12,
    AAS_PATHTYPE_MAX = 13
};
