enum enum_1F200 : int
{
    GAME_SYSTEM_EVENT_MAP_REQUEST_MAP_CHANGE = 0,
    GAME_SYSTEM_EVENT_MAP_LOADED = 1,
    GAME_SYSTEM_EVENT_MAP_LOAD_FAILED = 2,
    GAME_SYSTEM_EVENT_MAP_UNLOADED = 3,
    GAME_SYSTEM_EVENT_HUD_INITIALIZED = 4,
    GAME_SYSTEM_EVENT_OFFLINE_MODE_STATE_CHANGE = 5,
    GAME_SYSTEM_EVENT_OFFLINE_MODE_STATE_REAFFIRMED = 6,
    GAME_SYSTEM_EVENT_OFFLINE_MODE_STATE_FORCED = 7,
    GAME_SYSTEM_EVENT_NEXTGEN_RAYTRACE_CHANGE = 8
};
