enum environmentalDamageType_t : int
{
    ENVIRONMENTAL_DAMAGE_NONE = -1,
    ENVIRONMENTAL_DAMAGE_FIRE = 0,
    ENVIRONMENTAL_DAMAGE_RADIATION = 1,
    ENVIRONMENTAL_DAMAGE_LAVA = 2,
    ENVIRONMENTAL_DAMAGE_BIO = 3,
    ENVIRONMENTAL_DAMAGE_XENON = 4,
    ENVIRONMENTAL_DAMAGE_SLIME = 5,
    ENVIRONMENTAL_DAMAGE_DEEP_WATER = 6,
    ENVIRONMENTAL_DAMAGE_NUM = 7
};
