enum eolCombatCategoryType_t : int
{
    EOL_COMBAT_CATEGORY_COMBAT = 0,
    EOL_COMBAT_CATEGORY_SLAYER_GATE = 1,
    EOL_COMBAT_CATEGORY_SECRET = 2,
    EOL_COMBAT_CATEGORY_BOSS = 3,
    NUM_EOL_COMBAT_CATEGORIES = 4
};
