enum eolChallengesSoundId_t : int
{
    EOL_CHALLENGES_SOUND_CHALLENGE_SHOW = 101,
    EOL_CHALLENGES_SOUND_CHALLENGE_PROGRESS_BAR_SHOW = 102,
    EOL_CHALLENGES_SOUND_CHALLENGE_PROGRESS_BAR_FILL = 103,
    EOL_CHALLENGES_SOUND_CHALLENGE_COMPLETE = 104,
    EOL_CHALLENGES_SOUND_ALL_COMPLETE = 105
};
