enum eolCombatSoundId_t : int
{
    EOL_COMBAT_SOUND_CATEGORY_PIP_FILL = 101,
    EOL_COMBAT_SOUND_CATEGORY_PIP_COMPLETE = 102,
    EOL_COMBAT_SOUND_CATEGORY_SECTION_COMPLETE = 103,
    EOL_COMBAT_SOUND_CATEGORY_ALL_COMPLETE = 104
};
