enum eolRewardsSoundId_t : int
{
    EOL_REWARDS_SOUND_XP_COUNTER_FILL = 0,
    EOL_REWARDS_SOUND_XP_COUNTER_COMPLETE = 0,
    EOL_REWARDS_SOUND_PLAYER_BADGE_SHOW_OUT = 0,
    EOL_REWARDS_SOUND_PLAYER_BADGE_SHOW_IN = 0,
    EOL_REWARDS_SOUND_SEASONS_SHOW = 0,
    EOL_REWARDS_SOUND_SEASONS_PROGRESS_FILL = 0,
    EOL_REWARDS_SOUND_SEASONS_LEVEL_COMPLETE = 0,
    EOL_REWARDS_SOUND_REWARDS_LIST_SHOW = 0,
    EOL_REWARDS_SOUND_REWARDS_LIST_ITEM_UNLOCK = 0,
    EOL_REWARDS_SOUND_REWARDS_LIST_COMPLETE = 0
};
