enum eolSummarySoundId_t : int
{
    EOL_SUMMARY_SOUND_CATEGORY_SHOW = 101,
    EOL_SUMMARY_SOUND_CATEGORY_PROGRESS_BAR_SHOW = 102,
    EOL_SUMMARY_SOUND_CATEGORY_PROGRESS_BAR_FILL = 103,
    EOL_SUMMARY_SOUND_CATEGORY_COMPLETE = 104
};
