enum eolSummaryCategory_t : int
{
    EOL_SUMMARY_CATEGORY_INVALID = -1,
    EOL_SUMMARY_CATEGORY_COMBAT = 0,
    EOL_SUMMARY_CATEGORY_CHALLENGES = 1,
    EOL_SUMMARY_CATEGORY_EXPLORATION = 2,
    MAX_EOL_SUMMARY_CATEGORIES = 3
};
