enum eolScreenID_t : int
{
    EOL_SCREEN_INVALID = -1,
    EOL_SCREEN_SUMMARY = 0,
    EOL_SCREEN_COMBAT = 1,
    EOL_SCREEN_CHALLENGES = 2,
    EOL_SCREEN_ITEMS = 3,
    EOL_SCREEN_REWARDS = 4,
    EOL_SCREEN_CREDITS = 5,
    EOL_SCREEN_EXTRA_LIVES = 6,
    EOL_SCREEN_MASTER_LEVEL = 7,
    EOL_THANKS_FOR_PLAYING = 8,
    EOL_SCREEN_HORDE = 9,
    EOL_SCREEN_HORDE_SUMMARY = 10,
    EOL_BACKDROP = 11
};
