enum equipSlot_t : int
{
    EQUIP_NONE = 0,
    EQUIP_LEFT_HAND = 1,
    EQUIP_RIGHT_HAND = 2,
    EQUIP_HEAD = 3,
    EQUIP_TORSO = 4,
    EQUIP_LEFT_SHOULDER = 5,
    EQUIP_RIGHT_SHOULDER = 6,
    EQUIP_HOLSTER_HIP_LEFT = 7,
    EQUIP_HOLSTER_HIP_RIGHT = 8,
    EQUIP_LEFT_LAUNCHER = 9,
    EQUIP_RIGHT_LAUNCHER = 10,
    EQUIP_MAX = 11
};
