enum etherealRushTyp_t : int
{
    ETHEREAL_RUSH_STANDARD_SINGLE = 0,
    ETHEREAL_RUSH_GOLD_WAVE_1 = 1,
    ETHEREAL_RUSH_GOLD_WAVE_2 = 2,
    ETHEREAL_RUSH_DIRECT_STRIKE_1 = 3,
    ETHEREAL_RUSH_DIRECT_STRIKE_2 = 4,
    ETHEREAL_RUSH_COUNT = 5
};
