enum eventFlags_t : int
{
    EVENTFLAG_CANSKIP = 1,
    EVENTFLAG_CLIENTSAFE = 4,
    EVENTFLAG_NOSCRIPT = 8,
    EVENTFLAG_PASSIVEMARKER = 16,
    EVENTFLAG_NOHANDLER = 32,
    EVENTFLAG_SCOPED = 64
};
