enum extrapolation_t : int
{
    EXTRAPOLATION_NONE = 1,
    EXTRAPOLATION_LINEAR = 2,
    EXTRAPOLATION_ACCELLINEAR = 4,
    EXTRAPOLATION_DECELLINEAR = 8,
    EXTRAPOLATION_ACCELSINE = 16,
    EXTRAPOLATION_DECELSINE = 32,
    EXTRAPOLATION_NOSTOP = 64
};
