enum faceChannel_t : int
{
    FACECHANNEL_BODY = 0,
    FACECHANNEL_LEGS = 1,
    FACECHANNEL_TORSO = 2,
    FACECHANNEL_HEAD = 3,
    FACECHANNEL_EYES = 4,
    FACECHANNEL_EMOTE_MOUTH = 5,
    FACECHANNEL_EMOTE_BROW = 6,
    FACECHANNEL_EMOTE_FACE = 7,
    FACECHANNEL_FACE = 8,
    FACECHANNEL_BODYWEB = 9,
    FACECHANNEL_USER_CHANNEL = 10,
    FACECHANNEL_MAX = 11
};
