enum fileVerifyFailedReason_t : int
{
    FILE_VERIFY_FAILED_REASON_CORRUPTED = 0,
    FILE_VERIFY_FAILED_REASON_LENGTH = 1,
    FILE_VERIFY_FAILED_REASON_UNEXPECTED = 2,
    FILE_VERIFY_FAILED_REASON_MISSING = 3
};
