enum fpuExceptions_t : int
{
    FPU_EXCEPTION_INVALID_OPERATION = 1,
    FPU_EXCEPTION_DENORMALIZED_OPERAND = 2,
    FPU_EXCEPTION_DIVIDE_BY_ZERO = 4,
    FPU_EXCEPTION_NUMERIC_OVERFLOW = 8,
    FPU_EXCEPTION_NUMERIC_UNDERFLOW = 16,
    FPU_EXCEPTION_INEXACT_RESULT = 32
};
