enum fsPathSearch_t : int
{
    FSPATH_SEARCH_DEFAULT = 0,
    FSPATH_SEARCH_BASE = 1,
    FSPATH_SEARCH_SOURCE = 2,
    FSPATH_SEARCH_GENERATED = 3,
    FSPATH_SEARCH_CACHE = 4,
    FSPATH_SEARCH_SAVE = 5,
    FSPATH_SEARCH_INSTALL = 6
};
