enum fxExtraCondition_t : int
{
    FX_EXTRA_COND_NONE = 0,
    FX_EXTRA_COND_WEAP_LEFT = 4,
    FX_EXTRA_COND_WEAP_RIGHT = 8,
    FX_EXTRA_COND_PRIMARY_FIRE = 16,
    FX_EXTRA_COND_SECONDARY_FIRE = 32,
    FX_EXTRA_COND_ALLIED = 64,
    FX_EXTRA_COND_ENEMY = 128,
    FX_EXTRA_COND_DAMAGE_LIGHT = 256,
    FX_EXTRA_COND_DAMAGE_MEDIUM = 512,
    FX_EXTRA_COND_DAMAGE_HEAVY = 1024,
    FX_EXTRA_COND_QUAD = 2048,
    FX_EXTRA_COND_HELL = 4096,
    FX_EXTRA_COND_TECH = 8192,
    FX_EXTRA_COND_IMPACT_METAL = 16384,
    FX_EXTRA_COND_IMPACT_STONE = 32768,
    FX_EXTRA_COND_IMPACT_WOOD = 65536,
    FX_EXTRA_COND_IMPACT_FLESH = 131072,
    FX_EXTRA_COND_IMPACT_LIQUID = 262144,
    FX_EXTRA_COND_MAX = 524288
};
