enum fxRotationType_t : int
{
    FX_ROT_START_AXIS = 0,
    FX_ROT_START_AXIS_PARENT = 1,
    FX_ROT_TRACK_AXIS = 2,
    FX_ROT_TRACK_AXIS_PARENT = 3,
    FX_ROT_EXPLICIT_ANGLES = 4,
    FX_ROT_EXPLICIT_TABLES = 5,
    FX_ROT_EXPLICIT_TABLES_LOCAL = 6,
    FX_ROT_EXPLICIT_CODE = 7,
    FX_ROT_TRACK_AXIS_RENDERMODEL = 8
};
