enum gameDifficulty_t : int
{
    DIFFICULTY_NONE = -2,
    DIFFICULTY_ALL = -1,
    DIFFICULTY_EASY = 0,
    DIFFICULTY_MEDIUM = 1,
    DIFFICULTY_HARD = 2,
    DIFFICULTY_NIGHTMARE = 3,
    DIFFICULTY_ULTRA_NIGHTMARE = 4,
    DIFFICULTY_MAX = 5
};
