enum gameType_t : int
{
    GAME_TYPE_NONE = 0,
    GAME_TYPE_CAMPAIGN = 1,
    GAME_TYPE_BATTLEARENA = 2,
    GAME_TYPE_BATTLEARENA_TUTORIAL = 3,
    GAME_TYPE_INVASION = 4,
    GAME_TYPE_HORDE = 5
};
