enum gameFrameFlags_t : int
{
    GAMEFRAME_FLAGS_NONE = 0,
    GAMEFRAME_FLAG_ADVANCE_TIME = 1,
    GAMEFRAME_FLAG_HANDLE_PENDING_INPUT_EVENTS = 2,
    GAMEFRAME_FLAG_ENABLE_ASYNC_FRAME_JOBS = 4,
    GAMEFRAME_FLAG_RENDER = 8,
    GAMEFRAME_FLAG_PLAYBACK = 16
};
