enum graphicsVendor_t : int
{
    VENDOR_UNKNOWN = 0,
    VENDOR_NVIDIA = 1,
    VENDOR_AMD = 2,
    VENDOR_INTEL = 3,
    VENDOR_IMAGINATION = 4,
    VENDOR_QUALCOMM = 5,
    VENDOR_ARM = 6,
    VENDOR_GGP = 7,
    VENDOR_BROADCOM = 8,
    VENDOR_MOLTENVK = 9
};
