enum handAimType_t : int
{
    HANDAIMTYPE_INVALID = -1,
    HANDAIMTYPE_NONE = 0,
    HANDAIMTYPE_KEEP_CAMERA_RELATION = 1,
    HANDAIMTYPE_GROUNDCONTACT = 2,
    HANDAIMTYPE_KEEP_ORIGIN_RELATION = 3
};
