enum handsItemTypes_t : int
{
    HANDS_ITEM_TYPE_NONE = 0,
    HANDS_ITEM_TYPE_RIGHT = 1,
    HANDS_ITEM_TYPE_LEFT = 2,
    HANDS_ITEM_TYPE_HEAD = 4,
    HANDS_ITEM_TYPE_RIGHT_SHOULDER = 8,
    HANDS_ITEM_TYPE_LEFT_SHOULDER = 16
};
