enum hapticTriggerPercent_t : int
{
    HTP_ZERO = 0,
    HTP_TEN_PERCENT = 1,
    HTP_TWENTY_PERCENT = 2,
    HTP_THIRTY_PERCENT = 3,
    HTP_FORTY_PERCENT = 4,
    HTP_FIFTY_PERCENT = 5,
    HTP_SIXTY_PERCENT = 6,
    HTP_SEVENTY_PERCENT = 7,
    HTP_EIGHTY_PERCENT = 8,
    HTP_NINETY_PERCENT = 9,
    HTP_MAX = 10
};
