enum highlightColor_t : int
{
    HIGHLIGHT_COLOR_NONE = 0,
    HIGHLIGHT_COLOR_USE = 1,
    HIGHLIGHT_COLOR_ITEM = 2,
    HIGHLIGHT_COLOR_LOOT = 3,
    HIGHLIGHT_COLOR_EXPLODE = 4,
    HIGHLIGHT_COLOR_MAX = 5
};
