enum hordeCheckpointKey_t : int
{
    HORDE_CHECKPOINT_UNASSIGNED = -1,
    HORDE_CHECKPOINT_ARENA_1 = 0,
    HORDE_CHECKPOINT_ARENA_2 = 1,
    HORDE_CHECKPOINT_ARENA_3 = 2,
    HORDE_CHECKPOINT_BLITZ = 3,
    HORDE_CHECKPOINT_BONUS_COIN = 4,
    HORDE_CHECKPOINT_TRAVERSAL = 5,
    HORDE_CHECKPOINT_BONUS_BLITZ = 6,
    HORDE_CHECKPOINT_TEMP_1 = 7,
    HORDE_CHECKPOINT_TEMP_2 = 8,
    HORDE_CHECKPOINT_COUNT = 9
};
