enum hudEndOfLevelMenuActions_t : int
{
    CMD_EOL_NEXT_MAP = 0,
    CMD_EOL_SAVE_AND_EXIT = 1,
    CMD_EOL_EXIT = 2,
    CMD_EOL_BACK_TO_LEVEL = 3,
    CMD_EOL_RESUME_CAMPAIGN = 4,
    CMD_EOL_MAP_NOT_INSTALLED = 5,
    CMD_EOL_SKIP_CREDITS = 6,
    CMD_EOL_DISMISS_EXTRA_LIFE_SCREEN = 7,
    CMD_EOL_REWARDS_NEXT_PAGE = 8,
    CMD_EOL_REWARDS_PREV_PAGE = 9,
    CMD_EOL_REWARDS_TOGGLE_PREVIEW = 10
};
