enum hudExtraLifeExchangeSoundId_t : int
{
    HUD_EXTRA_LIFE_EXCHANGE_SOUND_DEPOSIT_LIFE_SUCCESS = 101,
    HUD_EXTRA_LIFE_EXCHANGE_SOUND_DEPOSIT_LIFE_FAIL = 102,
    HUD_EXTRA_LIFE_EXCHANGE_SOUND_UNLOCK_REWARD = 103,
    HUD_EXTRA_LIFE_EXCHANGE_SOUND_UNLOCK_FINAL_REWARD = 104
};
