enum hudMenu_CollectibleViewerSoundId_t : int
{
    HUD_MENU_COLLECTIBLE_VIEWER_SOUND_ENTER_VIEWER = 101,
    HUD_MENU_COLLECTIBLE_VIEWER_SOUND_EXIT_VIEWER = 102,
    HUD_MENU_COLLECTIBLE_VIEWER_SOUND_SCENE_CHANGE = 103,
    HUD_MENU_COLLECTIBLE_VIEWER_SOUND_SELECTION_CHANGE = 104,
    HUD_MENU_COLLECTIBLE_VIEWER_SOUND_WEAPON_SPAWN = 105,
    HUD_MENU_COLLECTIBLE_VIEWER_SOUND_WEAPON_MOD_SWAP = 106,
    HUD_MENU_COLLECTIBLE_VIEWER_SOUND_REAL_AI_SPAWN = 107,
    HUD_MENU_COLLECTIBLE_VIEWER_SOUND_ALBUM_PLAY = 108,
    HUD_MENU_COLLECTIBLE_VIEWER_SOUND_ALBUM_PAUSE = 109
};
