enum idAIFSMTransitionDebugFlags : unsigned int
{
    DEBUGFLAG_NONE = 0,
    DEBUGFLAG_BREAK_ON_TRANSITION_EVALUATED = 1,
    DEBUGFLAG_BREAK_ON_TRANSITION_TAKEN = 2,
    DEBUGFLAG_BREAK_ON_TRANSITION_NOT_TAKEN = 4,
    DEBUGFLAG_INVALID_TRANSITION = 8,
    DEBUGFLAG_FSM_LOG_TRANSITION = 16,
    DEBUGFLAG_DISABLED_TRANSITION = 32,
    DEBUGFLAG_SHOW_AS_ACTIVE = 64,
    DEBUGFLAG_BREAK_ON_INIT = 128
};
