enum idAIFSMStateDebugFlags : unsigned int
{
    DEBUGFLAG_NONE = 0,
    DEBUGFLAG_BREAK_ON_ANY_TRANSITION_TO_STATE = 1,
    DEBUGFLAG_BREAK_ON_ANY_TRANSITION_FROM_STATE = 2,
    DEBUGFLAG_INVALID_STATE = 4,
    DEBUGFLAG_FSM_LOG_STATE = 8,
    DEBUGFLAG_BREAK_ON_INIT = 16,
    DEBUGFLAG_BREAK_ON_EVALUATE_TRANSITIONS = 32,
    DEBUGFLAG_BREAK_ON_ENTER_STATE = 64,
    DEBUGFLAG_BREAK_ON_EXIT_STATE = 128,
    DEBUGFLAG_SHOW_AS_ACTIVE = 256,
    DEBUGFLAG_DISABLED_STATE = 512,
    DEBUGFLAG_NO_FSM_LOG = 1024
};
