enum idAIFSMFSMDebugFlags : unsigned int
{
    DEBUGFLAG_NONE = 0,
    DEBUGFLAG_BREAK_ON_RESTART = 1,
    DEBUGFLAG_BREAK_ON_DONE = 2,
    DEBUGFLAG_BREAK_ON_INIT = 4,
    DEBUGFLAG_BREAK_ON_UPDATE = 8,
    DEBUGFLAG_BREAK_ON_UPDATE_NEW = 16
};
