enum idHandsFlourishAnimSelect : int
{
    HANDS_FLOURISH_ANIM_NONE = 0,
    HANDS_FLOURISH_ANIM_1 = 1,
    HANDS_FLOURISH_ANIM_FIRST = 1,
    HANDS_FLOURISH_ANIM_2 = 2,
    HANDS_FLOURISH_ANIM_3 = 3,
    HANDS_FLOURISH_ANIM_LAST = 3
};
