enum idHandsHitReactionType_t : int
{
    HANDSHITREACTION_NONE = 0,
    HANDSHITREACTION_GENERIC = 1,
    HANDSHITREACTION_MELEE = 2,
    HANDSHITREACTION_EXPLOSIVE = 3,
    HANDSHITREACTION_FIRE = 4,
    HANDSHITREACTION_PUSHED = 5,
    HANDSHITREACTION_LUNGE = 6,
    HANDSHITREACTION_SHOTGUNNER_KNOCKBACK = 7
};
