enum idHandsFailedChainsawSelect : int
{
    HANDS_CHAINSAW_FAILED_NONE = -1,
    HANDS_CHAINSAW_FAILED_SWIPE_LEFT = 0,
    HANDS_CHAINSAW_FAILED_SWIPE_RIGHT = 1,
    HANDS_CHAINSAW_FAILED_PULL_CORD = 2,
    HANDS_CHAINSAW_FAILED_DEFLECT = 3
};
