enum idHandsBFGShootStateSelect : int
{
    HANDS_BFG_SHOOT_STATE_SPHERE = 0,
    HANDS_BFG_SHOOT_STATE_SPHERE_ARC = 1,
    HANDS_BFG_SHOOT_STATE_SPHERE_BURN = 2,
    HANDS_BFG_SHOOT_STATE_BEAM = 3,
    HANDS_BFG_SHOOT_STATE_BEAM_ARC = 4,
    HANDS_BFG_SHOOT_STATE_BEAM_BURN = 5
};
