enum idHandsCustomWeaponAnimSelect : int
{
    HANDS_CUSTOM_WEAPON_ANIM_DEFAULT = 0,
    HANDS_CUSTOM_WEAPON_ANIM_COLLECTIBLE_FIRST_PICKUP = 0,
    HANDS_CUSTOM_WEAPON_ANIM_COLLECTIBLE_STANDARD = 1,
    HANDS_CUSTOM_WEAPON_ANIM_COLLECTIBLE_FIST_BUMP = 2,
    HANDS_CUSTOM_WEAPON_ANIM_MAX = 3
};
