enum idHandsMeleeD5Select : int
{
    HANDS_MELEE_D5_SELECT_FORWARD = 0,
    HANDS_MELEE_D5_SELECT_SWEEP_LEFT = 1,
    HANDS_MELEE_D5_SELECT_SWEEP_RIGHT = 2,
    HANDS_MELEE_D5_SELECT_UPPERCUT = 3
};
