enum idHordeSummarySubscreenID_t : int
{
    HORDE_SUMMARY_SUBSCREEN_INVALID = -1,
    HORDE_SUMMARY_SUBSCREEN_SUMMARY = 0,
    HORDE_SUMMARY_SUBSCREEN_MAP_STATS = 1,
    HORDE_SUMMARY_SUBSCREEN_MAP_PATH = 2,
    HORDE_SUMMARY_SUBSCREEN_TOTAL = 3,
    NUM_HORDE_SUMMARY_SUBSCREENS = 4
};
