enum idHordeScoreItemType_t : int
{
    HORDE_SCORE_TYPE_INVALID = -1,
    HORDE_SCORE_TYPE_COMBAT = 0,
    HORDE_SCORE_TYPE_BOUNTY = 1,
    HORDE_SCORE_TYPE_BLITZ = 2,
    HORDE_SCORE_TYPE_POWER_UP = 3,
    HORDE_SCORE_TYPE_COINS = 4,
    HORDE_SCORE_TYPE_EXTRA_LIVES = 5,
    HORDE_SCORE_TYPE_DIFFICULTY = 6,
    HORDE_SCORE_TYPE_BFG_AMMO = 7,
    HORDE_SCORE_TYPE_COUNT = 8
};
