enum idImportanceBucket_t : unsigned int
{
    IMPORTANCE_BUCKET_VERYHIGH = 0,
    IMPORTANCE_BUCKET_HIGH = 1,
    IMPORTANCE_BUCKET_MEDIUM = 2,
    IMPORTANCE_BUCKET_LOW = 3,
    IMPORTANCE_BUCKET_CULL = 4,
    IMPORTANCE_BUCKET_MAX = 5
};
