enum idMidnightPVPPodiumEventType_t : int
{
    PVP_PODIUM_INTRO_ANIM_SLOT = 0,
    PVP_PODIUM_INTRO_START = 1,
    PVP_PODIUM_INTRO_END = 2,
    PVP_PODIUM_INTRO_PLAYER_CARD_SLOT = 3,
    PVP_PODIUM_INTRO_HIDE_PLAYER_CARDS = 4,
    PVP_PODIUM_INTRO_PLAY_VIDEO = 5,
    PVP_PODIUM_INTRO_SOUND_EVENT = 6,
    PVP_PODIUM_OUTRO_SLAYER_ANIM = 7,
    PVP_PODIUM_OUTRO_DEMONS_ANIM = 8,
    PVP_PODIUM_OUTRO_SHOW_ALL_PODIUMS = 9,
    PVP_PODIUM_OUTRO_SHOW_END_OF_MATCH = 10,
    PVP_PODIUM_OUTRO_FINAL_POSITION = 11,
    PVP_PODIUM_FADE_SCREEN = 12,
    PVP_PODIUM_EXIT_MATCH = 13,
    PVP_PODIUM_NONE = 14
};
