enum idMidnightAnimClipFlags_t : int
{
    ARK_MDNT_ANIMFLAG_NONE = 0,
    ARK_MDNT_ANIMFLAG_REVERSEONEXIT = 1,
    ARK_MDNT_ANIMFLAG_ADDITIVE = 2,
    ARK_MDNT_ANIMFLAG_STOPVOONSHUTDOWN = 4,
    ARK_MDNT_ANIMFLAG_USEDEFERREDORIGIN = 8,
    ARK_MDNT_ANIMFLAG_ALPHAONEFORUSERMASK = 32,
    ARK_MDNT_ANIMFLAG_CONTINUE_ANIM_ON_SHUTDOWN = 64
};
