enum idMidnightSever_t : int
{
    MDNT_SEVER_HEAD = 0,
    MDNT_SEVER_LEFT_ELBOW = 1,
    MDNT_SEVER_RIGHT_ELBOW = 2,
    MDNT_SEVER_LEFT_FRONT_ARM = 3,
    MDNT_SEVER_LEFT_BACK_ARM = 4,
    MDNT_SEVER_RIGHT_FRONT_ARM = 5,
    MDNT_SEVER_RIGHT_BACK_ARM = 6
};
