enum idPhotoModeCamera_States_t : int
{
    PMC_INVALID_STATE = -1,
    PMC_FINDING_VALID_SPAWN_LOCATION = 0,
    PMC_FOUND_VALID_SPAWN_LOCATION = 1,
    PMC_NO_VALID_SPAWN_LOCATIONS_FOUND = 2,
    PMC_UNDER_PLAYER_COMMAND = 3,
    PMC_FROZEN_WHILE_CURSOR_ACTIVE = 4,
    PMC_BECAME_UNFROZEN = 5
};
