enum idPlayerMechanicWallGrabState_t : int
{
    PMEC_WALL_GRAB_STATE_NONE = 0,
    PMEC_WALL_GRAB_STATE_LEFT_MOUNT = 1,
    PMEC_WALL_GRAB_STATE_LEFT_IDLE = 2,
    PMEC_WALL_GRAB_STATE_LEFT_IDLE_TO_RIGHT_IDLE = 3,
    PMEC_WALL_GRAB_STATE_LEFT_MOVE_LEFT = 4,
    PMEC_WALL_GRAB_STATE_LEFT_MOVE_RIGHT = 5,
    PMEC_WALL_GRAB_STATE_LEFT_DISMOUNT = 6,
    PMEC_WALL_GRAB_STATE_RIGHT_MOUNT = 7,
    PMEC_WALL_GRAB_STATE_RIGHT_IDLE = 8,
    PMEC_WALL_GRAB_STATE_RIGHT_IDLE_TO_LEFT_IDLE = 9,
    PMEC_WALL_GRAB_STATE_RIGHT_MOVE_LEFT = 10,
    PMEC_WALL_GRAB_STATE_RIGHT_MOVE_RIGHT = 11,
    PMEC_WALL_GRAB_STATE_RIGHT_DISMOUNT = 12,
    PMEC_WALL_GRAB_STATE_SHUTDOWN = 13,
    PMEC_WALL_GRAB_STATE_MAX = 14
};
