enum idPlayerMechanicLedgeGrabState_t : int
{
    PMEC_LEDGE_GRAB_STATE_NONE = -1,
    PMEC_LEDGE_GRAB_STATE_LEDGE_PULL_UP = 0,
    PMEC_LEDGE_GRAB_STATE_LEDGE_PULL_UP_MANTLE = 1,
    PMEC_LEDGE_GRAB_STATE_LEDGE_PULL_UP_FOOT = 2,
    PMEC_LEDGE_GRAB_STATE_LEDGE_PULL_UP_ROUNDED = 3,
    PMEC_LEDGE_GRAB_STATE_LEDGE_PULL_UP_MANTLE_ROUNDED = 4,
    PMEC_LEDGE_GRAB_STATE_LEDGE_PULL_UP_ANGLED = 5,
    PMEC_LEDGE_GRAB_STATE_LEDGE_PULL_UP_MANTLE_ANGLED = 6,
    PMEC_LEDGE_GRAB_STATE_LEDGE_CLIMB_UP = 7,
    PMEC_LEDGE_GRAB_STATE_LEDGE_CLIMB_UP_MANTLE = 8,
    PMEC_LEDGE_GRAB_STATE_LEDGE_CLIMB_UP_FOOT = 9,
    PMEC_LEDGE_GRAB_STATE_RAILING_PULL_UP = 10,
    PMEC_LEDGE_GRAB_STATE_RAILING_PULL_UP_MANTLE = 11,
    PMEC_LEDGE_GRAB_STATE_RAILING_PULL_UP_FOOT = 12,
    PMEC_LEDGE_GRAB_STATE_CUSTOM_PULL_UP = 13,
    PMEC_LEDGE_GRAB_STATE_CUSTOM_MANTLE = 14,
    PMEC_LEDGE_GRAB_STATE_CUSTOM_FOOT = 15,
    PMEC_LEDGE_GRAB_STATE_MAX = 16
};
