enum idPositionRetargetingAxis_t : int
{
    POSITION_RETARGETING_AXIS_NONE = 0,
    POSITION_RETARGETING_AXIS_X = 1,
    POSITION_RETARGETING_AXIS_Y = 2,
    POSITION_RETARGETING_AXIS_Z = 4,
    POSITION_RETARGETING_AXIS_ALL = 7
};
