enum idResourceCVarSubType : int
{
    RES_CVAR_SUB_TYPE_STRING = 0,
    RES_CVAR_SUB_TYPE_BOOL = 1,
    RES_CVAR_SUB_TYPE_INTEGER = 2,
    RES_CVAR_SUB_TYPE_FLOAT = 3,
    RES_CVAR_SUB_TYPE_INTEGER_LE = 4,
    RES_CVAR_SUB_TYPE_INTEGER_GE = 5
};
