enum idRequirementType_t : int
{
    RT_USER_INVENTORY = 0,
    RT_OWNER_INVENTORY = 1,
    RT_USER_NOT_IN_INVENTORY = 2,
    RT_OWNER_NOT_IN_INVENTORY = 3,
    RT_ENTITY_IN_WORLD = 4,
    RT_USER_HEALTH_ABOVE = 5,
    RT_USER_HEALTH_BELOW = 6,
    RT_HANDS_NOT_DISABLED = 7,
    RT_USER_CURRENCY = 8,
    RT_USER_NOT_IN_CURRENCY = 9,
    RT_MAX_NUM = 10
};
