enum idSWFWidgetState_t : int
{
    SWF_WIDGET_STATE_HIDDEN = 0,
    SWF_WIDGET_STATE_NORMAL = 1,
    SWF_WIDGET_STATE_SELECTING = 2,
    SWF_WIDGET_STATE_SELECTED = 3,
    SWF_WIDGET_STATE_UNSELECTING = 4,
    SWF_WIDGET_STATE_DISABLED = 5,
    SWF_WIDGET_STATE_NONSELECTABLE = 6,
    SWF_WIDGET_STATE_EXPANDED = 7,
    SWF_WIDGET_STATE_MAX = 8
};
