enum idViolenceFrameFlags_t : int
{
    VIOLENCE_FRAME_FLAG_NONE = 0,
    VIOLENCE_FRAME_FLAG_FOCUS = 1,
    VIOLENCE_FRAME_FLAG_POWERUP_BERSERK = 2,
    VIOLENCE_FRAME_FLAG_POWERUP_QUAD_DAMAGE = 4,
    VIOLENCE_FRAME_FLAG_POWERUP_INVISIBLE = 8,
    VIOLENCE_FRAME_FLAG_POWERUP_INVULNERABLE = 16,
    VIOLENCE_FRAME_FLAG_POWERUP_HASTE = 32,
    VIOLENCE_FRAME_FLAG_PLAYER_ADS = 64,
    VIOLENCE_FRAME_FLAG_POWERUP_REGENERATION = 128,
    VIOLENCE_FRAME_FLAG_ALL = 2147483647
};
