enum idViolenceFilterFlags_t : int
{
    VIOLENCE_FILTER_FLAG_NONE = 0,
    VIOLENCE_FILTER_FLAG_ON_GROUND = 1,
    VIOLENCE_FILTER_FLAG_IN_PLAYER_VIEW = 2,
    VIOLENCE_FILTER_FLAG_IS_FROZEN = 4,
    VIOLENCE_FILTER_FLAG_IS_MANUAL_USE = 8,
    VIOLENCE_FILTER_FLAG_IS_SPECIAL_WEAPON = 16,
    VIOLENCE_FILTER_FLAG_IS_ONFIRE = 32
};
