enum initCommandType_t : int
{
    COMMAND_INIT_END = 0,
    COMMAND_INIT_BOX = 1,
    COMMAND_INIT_BOX_SURFACE = 2,
    COMMAND_INIT_SPHERE = 3,
    COMMAND_INIT_SPHERE_SURFACE = 4,
    COMMAND_INIT_CYLINDER = 5,
    COMMAND_INIT_CYLINDER_SURFACE = 6,
    COMMAND_INIT_GRID = 7,
    COMMAND_INIT_VEL_CONE = 8,
    COMMAND_INIT_VEL_INHERIT = 9,
    COMMAND_INIT_VEL_SPHERE = 10,
    COMMAND_INIT_OFFSET = 11,
    COMMAND_INIT_VEL_OFFSET = 12,
    COMMAND_INIT_BEAM = 13,
    COMMAND_INIT_SQUEEZENORMAL = 14,
    COMMAND_INIT_ANGULARVEL = 15,
    COMMAND_INIT_MAX = 16
};
