enum inlineConstantType_t : int
{
    INLINE_CONSTANT_TYPE_GEOMETRY_INDEX = 0,
    INLINE_CONSTANT_TYPE_LOD_INDEX = 1,
    INLINE_CONSTANT_TYPE_MODEL_INDEX = 2,
    INLINE_CONSTANT_TYPE_SKINNING_MODE = 3,
    INLINE_CONSTANT_TYPE_GEO_DECAL_PROJ_OFFSET = 4,
    INLINE_CONSTANT_TYPE_WORLD_GUI_OFFSCREEN = 5,
    INLINE_CONSTANT_TYPE_NUM = 6
};
