enum inputWindow_t : int
{
    INPUT_WINDOW_NONE = -1,
    INPUT_WINDOW_WIN1 = 0,
    INPUT_WINDOW_LOSE1 = 1,
    INPUT_WINDOW_WIN2 = 2,
    INPUT_WINDOW_LOSE2 = 3,
    INPUT_WINDOW_ANY = 4,
    INPUT_WINDOW_MAX = 5,
    INPUT_WINDOW_FORCE_ON_LOSE = 6,
    INPUT_WINDOW_FORCE_ON_DAMAGE = 7,
    INPUT_WINDOW_FORCE_ON_DEATH = 8
};
