enum interestType_t : int
{
    INTEREST_PATH_OBSTACLE = 0,
    INTEREST_PATH_CORNER = 1,
    INTEREST_PATH_GOAL = 2,
    INTEREST_PATH_MAX = 3,
    INTEREST_LOOK_TARGET = 4,
    INTEREST_ACTOR = 5,
    INTEREST_SPECIAL_ATTACK = 6,
    INTEREST_ATTACK = 7,
    INTEREST_TAUNT = 8,
    INTEREST_PAIN = 9,
    INTEREST_DEATH = 10,
    INTEREST_OVERKILL = 11,
    INTEREST_EXPLOSION = 12,
    INTEREST_DOOR = 13,
    INTEREST_MAX = 14
};
