enum invasionMenuElementID_t : int
{
    INVASION_MENU_SCREEN_INVALID = -1,
    INVASION_MENU_SCREEN_VERSUS = 0,
    INVASION_MENU_SCREEN_DEMON_SELECT = 1,
    INVASION_MENU_SCREEN_OUTRO = 2,
    INVASION_MENU_SCREEN_SETTINGS = 3,
    INVASION_MENU_OVERLAY = 4
};
