enum iosTestLocs_t : int
{
    IOS_TEST_LOC_FLAMELEFT = 0,
    IOS_TEST_LOC_FLAMERIGHT = 1,
    IOS_TEST_LOC_GROUND_POUND_LEFT = 2,
    IOS_TEST_LOC_GROUND_POUND_RIGHT = 3,
    IOS_TEST_LOC_PUNCH_LEFT = 4,
    IOS_TEST_LOC_PUNCH_RIGHT = 5,
    IOS_TEST_LOC_PUNCH_LEFT_1 = 6,
    IOS_TEST_LOC_PUNCH_LEFT_2 = 7,
    IOS_TEST_LOC_PUNCH_LEFT_3 = 8,
    IOS_TEST_LOC_PUNCH_LEFT_4 = 9,
    IOS_TEST_LOC_PUNCH_RIGHT_1 = 10,
    IOS_TEST_LOC_PUNCH_RIGHT_2 = 11,
    IOS_TEST_LOC_PUNCH_RIGHT_3 = 12,
    IOS_TEST_LOC_PUNCH_RIGHT_4 = 13,
    IOS_TEST_LOC_COUNT = 14
};
