enum jobClass_t : int
{
    JOB_CLASS_MISC = 0,
    JOB_CLASS_GAME = 1,
    JOB_CLASS_RENDER = 2,
    JOB_CLASS_STREAMING = 3,
    JOB_CLASS_SOUND = 4,
    JOB_CLASS_PHYSICS = 5,
    JOB_CLASS_AI = 6,
    JOB_CLASS_ANIMATION = 7,
    JOB_CLASS_NETWORK = 8,
    JOB_CLASS_TOOLS = 9,
    JOB_CLASS_MAINTHREAD = 10,
    JOB_CLASS_ASYNCIO = 11,
    JOB_CLASS_NUM = 12
};
