enum jobPriority_t : int
{
    JOB_PRIORITY_TIME_CRITICAL = 0,
    JOB_PRIORITY_HIGHEST = 1,
    JOB_PRIORITY_HIGH = 2,
    JOB_PRIORITY_NORMAL = 3,
    JOB_PRIORITY_LOW = 4,
    JOB_PRIORITY_PLATFORM = 4,
    JOB_PRIORITY_COUNT = 5,
    JOB_PRIORITY_FIRST = 0,
    JOB_PRIORITY_LAST = 4
};
