enum jointModTransform_t : int
{
    JOINTMOD_SPACE_LOCAL = 1,
    JOINTMOD_SPACE_MODEL = 2,
    JOINTMOD_MODE_OFFSET = 4,
    JOINTMOD_MODE_OVERRIDE = 8,
    JOINTMOD_GROUP_INLINE = 16,
    JOINTMOD_GROUP_POST = 32
};
