enum liveTileArticleBodyAlignment_t : int
{
    LIVE_TILE_ARTICLE_BODY_ALIGNMENT_INVALID = -1,
    LIVE_TILE_ARTICLE_BODY_ALIGNMENT_DEFAULT = 0,
    LIVE_TILE_ARTICLE_BODY_ALIGNMENT_CENTER = 0,
    LIVE_TILE_ARTICLE_BODY_ALIGNMENT_LEFT = 1,
    LIVE_TILE_ARTICLE_BODY_ALIGNMENT_RIGHT = 2,
    NUM_LIVE_TILE_ARTICLE_BODY_ALIGNMENTS = 3
};
