enum liveTileArticleLayout_t : int
{
    LIVE_TILE_ARTICLE_LAYOUT_INVALID = -1,
    LIVE_TILE_ARTICLE_LAYOUT_BASIC = 0,
    LIVE_TILE_ARTICLE_LAYOUT_DOUBLE = 1,
    LIVE_TILE_ARTICLE_LAYOUT_TEXT = 2,
    LIVE_TILE_ARTICLE_LAYOUT_VIDEO = 3,
    NUM_LIVE_TILE_ARTICLE_LAYOUTS = 4
};
