enum lootDropType_t : int
{
    LOOT_DROP_TYPE_GLORYHIT = 0,
    LOOT_DROP_TYPE_FALTER_COMBO = 1,
    LOOT_DROP_TYPE_HEALTH_BREAK = 2,
    LOOT_DROP_TYPE_BLOODPUNCH = 3,
    LOOT_DROP_TYPE_PINATA_TIER1 = 4,
    LOOT_DROP_TYPE_PINATA_TIER2 = 5,
    LOOT_DROP_TYPE_PINATA_TIER3 = 6,
    LOOT_DROP_TYPE_PENALTY_HIT = 7,
    LOOT_DROP_TYPE_MAX = 8
};
