enum mapTipGameMode_t : int
{
    MAPTIP_MODE_CAMPAIGN = 0,
    MAPTIP_MODE_BATTLE = 1,
    MAPTIP_MODE_MASTERY_LEVEL = 2,
    MAPTIP_MODE_INVASION = 3,
    MAPTIP_MODE_ARCADE = 4,
    MAPTIP_MODE_HORDE = 5
};
