enum md6AnimatorInfoFlags_t : int
{
    ANIMATOR_FLAG_NONE = 0,
    ANIMATOR_FLAG_CLEAR_ORIGIN_TRANSFORM = 1,
    ANIMATOR_FLAG_DELTA_ORIGIN_LOOK_AHEAD = 2,
    ANIMATOR_FLAG_IS_USED_BY_ID_STUDIO = 4,
    ANIMATOR_FLAG_DEFERRED = 8,
    ANIMATOR_FLAG_AI = 16
};
