enum md6WeightGroup_t : int
{
    MD6_WEIGHTGROUP_ALL = 0,
    MD6_WEIGHTGROUP_LEGS = 1,
    MD6_WEIGHTGROUP_TORSO = 2,
    MD6_WEIGHTGROUP_HEAD = 3,
    MD6_WEIGHTGROUP_FACE = 4,
    MD6_WEIGHTGROUP_MOUTH = 5,
    MD6_WEIGHTGROUP_EYELIDS = 6,
    MD6_WEIGHTGROUP_USER0 = 7,
    MD6_WEIGHTGROUP_MAX = 8
};
