enum meleeDamage_t : int
{
    MELEE_NONE = -1,
    MELEE_IMPACT = 0,
    MELEE_FIRST_PLUS_ACTOR = 1,
    MELEE_FIRST_PLUS_ACTORS = 2,
    MELEE_CONTINUOUS = 3,
    MELEE_CONTINUOUS_UNTIL_ACTOR = 4,
    MELEE_MAX = 5
};
