enum memTraceHeap_t : int
{
    MEMTRACEHEAP_UNKNOWN = 0,
    MEMTRACEHEAP_SYSTEM = 1,
    MEMTRACEHEAP_SYSTEM_COMMIT = 2,
    MEMTRACEHEAP_WWISE = 3,
    MEMTRACEHEAP_WWISE_COMMIT = 4,
    MEMTRACEHEAP_WWISEDEVICE = 5,
    MEMTRACEHEAP_WWISEDEVICE_COMMIT = 6,
    MEMTRACEHEAP_PERSIST = 7,
    MEMTRACEHEAP_PERSIST_COMMIT = 8,
    MEMTRACEHEAP_MAP = 9,
    MEMTRACEHEAP_MAP_COMMIT = 10,
    MEMTRACEHEAP_IO_PAGEPOOL = 11,
    MEMTRACEHEAP_CRT = 12,
    MEMTRACEHEAP_JOINTS = 13,
    MEMTRACEHEAP_JOINTS_COMMIT = 14,
    MEMTRACEHEAP_WORLDGEOMETRYMANAGER_COMMIT = 15,
    MEMTRACEHEAP_IMAGESTREAMPOOL_COMMIT = 16,
    MEMTRACEHEAP_NUM = 17
};
