enum menuTransitionType_t : int
{
    MENU_TRANSITION_INVALID = -1,
    MENU_TRANSITION_ADVANCE = 0,
    MENU_TRANSITION_BACK = 1,
    MENU_TRANSITION_FORCE = 2,
    MENU_TRANSITION_SIMPLE = 3,
    MENU_TRANSITION_CUSTOM0 = 4,
    MENU_TRANSITION_CUSTOM1 = 5,
    MENU_TRANSITION_SKIP_HIDE = 6,
    MENU_TRANSITION_SKIP_SHOW = 7
};
