enum menuPlayerBadgePosition_t : int
{
    MENU_PLAYER_BADGE_POSITION_NONE = 0,
    MENU_PLAYER_BADGE_POSITION_BOTTOM_RIGHT = 1,
    MENU_PLAYER_BADGE_POSITION_BOTTOM_LEFT = 2,
    NUM_PLAYER_BADGE_POSITIONS = 3
};
