enum menuPopupID_t : int
{
    MENU_POPUP_SCREEN_CALIBRATION = 1100,
    MENU_POPUP_CONTROLLER_LAYOUTS = 1101,
    MENU_POPUP_KEY_BINDINGS = 1102,
    MENU_POPUP_BETHNET = 1103,
    MENU_POPUP_ACCOUNT_AGREEMENTS = 1104,
    MENU_POPUP_REPORT_PLAYER = 1105,
    MENU_POPUP_HDR_CALIBRATION = 1106,
    MENU_POPUP_NOTIFICATION = 1107,
    MENU_POPUP_ADD_FAVORITE = 1108,
    MENU_POPUP_ULTRA_NIGHTMARE_CONFIRM = 1109
};
