enum meshAnimatedStreamTypes_t : unsigned int
{
    ANIMATED_STREAM_TYPE_POSITIONS = 0,
    ANIMATED_STREAM_TYPE_TANGENTS = 1,
    ANIMATED_STREAM_TYPE_TEXCOORDS = 2,
    ANIMATED_STREAM_TYPE_COLORS = 3,
    ANIMATED_STREAM_TYPE_AUTO_SKIN_BONE_TRANSLATIONS = 4,
    ANIMATED_STREAM_TYPE_AUTO_SKIN_BONE_BASIS_VECTORS = 5,
    ANIMATED_STREAM_TYPE_NUM = 6
};
