enum meshStaticStreamTypes_t : unsigned int
{
    STATIC_STREAM_TYPE_INDICES = 0,
    STATIC_STREAM_TYPE_GEO_DECAL_INDICES = 1,
    STATIC_STREAM_TYPE_POSITIONS = 2,
    STATIC_STREAM_TYPE_TANGENTS = 3,
    STATIC_STREAM_TYPE_BITANGENT_SIGNS = 4,
    STATIC_STREAM_TYPE_TEXCOORDS = 5,
    STATIC_STREAM_TYPE_COLORS = 6,
    STATIC_STREAM_TYPE_GEO_DECAL_PROJ_INDICES = 7,
    STATIC_STREAM_TYPE_GEO_DECAL_PROJ_TO_TRI_INDICES = 8,
    STATIC_STREAM_TYPE_GEO_DECAL_PROJECTIONS = 9,
    STATIC_STREAM_TYPE_BASE_POSE = 10,
    STATIC_STREAM_TYPE_BONE_INDICES = 11,
    STATIC_STREAM_TYPE_BONE_WEIGHTS = 12,
    STATIC_STREAM_TYPE_NUM = 13
};
