enum mileStoneCategory_t : int
{
    MILESTONE_CATEGORY_INVALID = -1,
    MILESTONE_CATEGORY_CAMPAIGN = 0,
    MILESTONE_CATEGORY_BATTLE_ARENA = 1,
    MILESTONE_CATEGORY_INVASION = 2,
    MILESTONE_CATEGORY_SOCIAL = 3,
    MILESTONE_CATEGORY_AGNOSTIC = 4,
    MILESTONE_CATEGORY_DLC1 = 5,
    MILESTONE_CATEGORY_DLC2 = 6,
    MILESTONE_CATEGORY_HORDE = 7,
    MILESTONE_CATEGORY_NONE = 8,
    MILESTONE_CATEGORY_MAX = 9
};
