enum moverModifierFunction_t : int
{
    MOVERMODIFIER_NONE = 1,
    MOVERMODIFIER_SPEED = 2,
    MOVERMODIFIER_ORIENTATION = 4,
    MOVERMODIFIER_PAUSE = 32,
    MOVERMODIFIER_SPLINE = 64,
    MOVERMODIFIER_TARGET = 128,
    MOVERMODIFIER_REVERSE = 256,
    MOVERMODIFIER_OSCILLATION = 512,
    MOVERMODIFIER_SOUND = 1024,
    MOVERMODIFIER_RESET = 2048
};
