enum narrativeConditionType_t : int
{
    NARRATIVE_CONDITION_NIL = 0,
    NARRATIVE_CONDITION_TOUCH = 1,
    NARRATIVE_CONDITION_UNTOUCH = 2,
    NARRATIVE_CONDITION_ANIM_FINISHED = 3,
    NARRATIVE_CONDITION_SOUND_FINISHED = 4,
    NARRATIVE_CONDITION_WAIT_SEC = 5,
    NARRATIVE_CONDITION_HOTSPOT_1 = 6,
    NARRATIVE_CONDITION_HOTSPOT_2 = 7,
    NARRATIVE_CONDITION_HOTSPOT_3 = 8,
    NARRATIVE_CONDITION_HOTSPOT_4 = 9,
    NARRATIVE_CONDITION_SWIPE_LEFT = 10,
    NARRATIVE_CONDITION_SWIPE_RIGHT = 11,
    NARRATIVE_CONDITION_BACK_OUT = 12,
    NARRATIVE_CONDITION_INPUT = 13,
    NARRATIVE_CONDITION_VISITED = 14,
    NARRATIVE_CONDITION_IDLE_TIME = 15,
    NARRATIVE_CONDITION_PLAYER_POSITION = 16,
    NARRATIVE_CONDITION_PLAYER_FACING = 17,
    NARRATIVE_CONDITION_MAX = 18
};
