enum narrativeActionType_t : int
{
    NARRATIVE_ACTION_NIL = 0,
    NARRATIVE_ACTION_ANIM_SYNC = 1,
    NARRATIVE_ACTION_ANIM_CHANGESTATE = 2,
    NARRATIVE_ACTION_ANIM_CHANGESTATE_VIA = 3,
    NARRATIVE_ACTION_ACTIVATE = 4,
    NARRATIVE_ACTION_WAIT = 5,
    NARRATIVE_ACTION_STARTFX = 6,
    NARRATIVE_ACTION_STOPFX = 7,
    NARRATIVE_ACTION_VOICETRACK = 8,
    NARRATIVE_ACTION_SOUND = 9,
    NARRATIVE_ACTION_NARRATIVETABLE_CHANGESTATE = 10,
    NARRATIVE_ACTION_ADD_HOTSPOT = 11,
    NARRATIVE_ACTION_CLEAR_HOTSPOTS = 12,
    NARRATIVE_ACTION_SHOW_MODEL = 13,
    NARRATIVE_ACTION_HIDE_MODEL = 14,
    NARRATIVE_ACTION_MAX = 15
};
