enum navRegionFlags_t : int
{
    NAVREGION_NONE = 0,
    NAVREGION_BLOCKED = 1,
    NAVREGION_BLOCK_GROUP_1 = 2,
    NAVREGION_BLOCK_GROUP_2 = 4,
    NAVREGION_BLOCK_GROUP_3 = 8,
    NAVREGION_BLOCK_GROUP_4 = 16,
    NAVREGION_BLOCK_GROUP_5 = 32
};
