enum NetworkFailSafeState : unsigned char
{
    NETWORKFAILSAFE_NONE = 0,
    NETWORKFAILSAFE_ALIVE = 1,
    NETWORKFAILSAFE_PAIN = 2,
    NETWORKFAILSAFE_STAGGER = 4,
    NETWORKFAILSAFE_DEAD = 8,
    NETWORKFAILSAFE_REMOVED = 16,
    NETWORKFAILSAFE_MAX = 32
};
