enum obstacleAvoidanceFlags_t : int
{
    OAFLAG_ASSUME_VALID_AAS_PATH = 1,
    OAFLAG_MOVE_AROUND_SEEK_POS_OBSTACLES = 2,
    OAFLAG_CIRCLE_CORNERS = 4,
    OAFLAG_UPDATE_RADAR = 8,
    OAFLAG_REPLACE_EXISTING_QUERY = 16,
    OAFLAG_SHOW_PATH_TREE = 32,
    OAFLAG_DEBUG = 64,
    OAFLAG_DEBUG_BREAK = 128,
    OAFLAG_CIRCLE_CURRENT = 256,
    OAFLAG_NON_OPTIMAL = 512,
    OAFLAG_DEBUG_ANIMS = 1024,
    OAFLAG_IGNORE_LEDGES_ON_PATH = 2048,
    OAFLAG_COPY_ROUTE_VERBATIM = 4096,
    OAFLAG_INPUT_CORNER_LIST = 8192,
    OAFLAG_KEEP_PREVIOUS_CORNERS = 16384
};
