enum ogComboAttackType_t : int
{
    OG_COMBO_ATTACK_TYPE_RADIAL = 0,
    OG_COMBO_ATTACK_TYPE_SPIN = 1,
    OG_COMBO_ATTACK_TYPE_WALLS = 2,
    OG_COMBO_ATTACK_TYPE_SMASH = 3,
    OG_COMBO_ATTACK_TYPE_ROCKS = 4,
    OG_COMBO_ATTACK_TYPE_SMASH_AND_SWIPE = 5,
    OG_COMBO_ATTACK_TYPE_BOOMERANG = 6,
    OG_COMBO_ATTACK_TYPE_COUNT = 7
};
