enum ogWeaponType_t : int
{
    OG_WEAPON_TYPE_ABADDON = 0,
    OG_WEAPON_TYPE_APOLLYON = 1,
    OG_WEAPON_TYPE_APOLLYON_BEAM = 2,
    OG_WEAPON_TYPE_APOLLYON_COMBO = 3,
    OG_WEAPON_TYPE_ABADDON_COMBO = 4,
    OG_WEAPON_TYPE_APOLLYON_COMBO_BEAM = 5,
    OG_WEAPON_TYPE_NONE = 6
};
