enum outlineColorId_t : int
{
    PVP_SLAYER_OUTLINE_COLOR_ID = 0,
    PVP_DEMON_OUTLINE_COLOR_ID = 1,
    PVP_DEMON_ALLY_OUTLINE_COLOR_ID = 2,
    SP_FRIENDLY_TEAM_OUTLINE_COLOR_ID = 0,
    SP_HOSTILE_TEAM_OUTLINE_COLOR_ID = 1,
    SP_POSSESSION_TARGET_POSSIBLE_COLOR_ID = 2,
    SP_POSSESSION_TARGET_CONFIRM_COLOR_ID = 3,
    HORDE_DYNAMIC_OUTLINE_COLOR_ID = 0,
    HORDE_GENERIC_OUTLINE_COLOR_ID = 1,
    HORDE_PLACEHOLDER_A_OUTLINE_COLOR_ID = 2,
    HORDE_PLACEHOLDER_B_OUTLINE_COLOR_ID = 3
};
