enum particleQualityLevel_t : int
{
    PARTICLE_QUALITY_LEVEL_UNSPECIFIED = -1,
    PARTICLE_QUALITY_LEVEL_LOW = 0,
    PARTICLE_QUALITY_LEVEL_MEDIUM = 1,
    PARTICLE_QUALITY_LEVEL_HIGH = 2,
    PARTICLE_QUALITY_LEVEL_ULTRA = 3,
    NUM_PARTICLE_QUALITY_LEVELS = 4
};
