enum particleEditCalcType_t : int
{
    PARTICLE_EDIT_CALC_NONE = 0,
    PARTICLE_EDIT_CALC_CONSTANT = 1,
    PARTICLE_EDIT_CALC_MINMAX = 2,
    PARTICLE_EDIT_CALC_CURVE = 3,
    PARTICLE_EDIT_CALC_PARAMETRIC_EVAL = 4,
    PARTICLE_EDIT_CALC_PARAMETRIC_INTEGRATE = 5,
    PARTICLE_EDIT_CALC_PARAMETRIC_INTEGRATE_MINMAX = 6,
    NUM_PARTICLE_EDIT_CALC_TYPES = 7
};
