enum particleCalcType_t : int
{
    PARTICLE_CALC_NONE = 0,
    PARTICLE_CALC_CURVE_GENERIC = 1,
    PARTICLE_CALC_GENERIC = 2,
    PARTICLE_CALC_PARAMETRIC_EVAL = 3,
    PARTICLE_CALC_PARAMETRIC_INTEGRATE = 4,
    PARTICLE_CALC_PARAMETRIC_INTEGRATE_MINMAX = 5,
    NUM_PARTICLE_CALC_TYPES = 6
};
