enum particleRenderMode_t : int
{
    PARTICLE_RENDER_MODE_LIT = 0,
    PARTICLE_RENDER_MODE_UNLIT = 1,
    PARTICLE_RENDER_MODE_LIQUID = 2,
    PARTICLE_RENDER_MODE_UNLIT_LIQUID = 3,
    PARTICLE_RENDER_MODE_EXPLOSION = 4,
    PARTICLE_RENDER_MODE_MAX = 5
};
