enum particleFunctionOf_t : int
{
    FUNCTION_OF_PARTICLE_AGE = 0,
    FUNCTION_OF_CYCLE_AGE = 1,
    FUNCTION_OF_EMITTER_AGE = 2,
    FUNCTION_OF_PARTICLE_SEED = 3,
    FUNCTION_OF_RIBBON_SEED = 4,
    FUNCTION_OF_RIBBON_AGE = 5,
    FUNCTION_OF_SPAWN_FRACTION = 6,
    FUNCTION_OF_RIBBON_FRACTION = 7,
    FUNCTION_OF_EMITTER_VELOCITY = 8
};
