enum pathManagerFlag_t : int
{
    PATHMANAGERFLAG_NONE = 0,
    PATHMANAGERFLAG_PLAYER = 1,
    PATHMANAGERFLAG_AI = 2,
    PATHMANAGERFLAG_ZOMBIE = 4,
    PATHMANAGERFLAG_LOSTSOUL = 8,
    PATHMANAGERFLAG_ALL = 65535
};
