enum pauseMenuElementID_t : int
{
    PAUSE_MENU_SCREEN_INVALID = -1,
    PAUSE_MENU_SCREEN_ROOT = 0,
    PAUSE_MENU_SCREEN_SETTINGS = 1,
    PAUSE_MENU_SCREEN_DEMO_SETTINGS = 2,
    PAUSE_MENU_SCREEN_MILESTONES = 3,
    PAUSE_MENU_SCREEN_DEV = 4,
    PAUSE_MENU_SCREEN_SOCIAL = 5,
    PAUSE_MENU_OVERLAY = 6
};
