enum perchStanceAnimIndex_t : int
{
    PERCHSTANCEANIMINDEX_GROUND = 0,
    PERCHSTANCEANIMINDEX_PERCHED_HANG = 1,
    PERCHSTANCEANIMINDEX_PERCHED_WALL_FORWARD = 2,
    PERCHSTANCEANIMINDEX_PERCHED_WALL_LEFT = 3,
    PERCHSTANCEANIMINDEX_PERCHED_WALL_RIGHT = 4
};
