enum perkDescriptionFlags_t : int
{
    PKF_NONE = 0,
    PKF_GENERIC = 1,
    PKF_PLAYER_HEALTH = 2,
    PKF_PLAYER_ARMOR = 4,
    PKF_PLAYER_AMMO = 8,
    PKF_SUIT_UPGRADE = 16,
    PKF_EQUIPMENT_MOD = 32,
    PKF_WEAPON_MOD = 64,
    PKF_WEAPON_UPGRADE = 128,
    PKF_BFG_HOTNESS = 256,
    PKF_RUNE = 512,
    PKF_BLOOD_PUNCH = 1024,
    PKF_DISABLED_DURING_EXTRA_LIFE = 2048,
    PKF_ARGENT_UPGRADE = 14
};
