enum photoModeActions_t : int
{
    PHOTOMODE_ACTION_INVALID = -1,
    PHOTOMODE_ACTION_TOGGLE_UI = 0,
    PHOTOMODE_ACTION_TOGGLE_FREECAM = 1,
    PHOTOMODE_ACTION_NEXT_FRAME = 2,
    PHOTOMODE_ACTION_RESET_SETTINGS = 3,
    PHOTOMODE_ACTION_RESET_CAMERA = 4,
    PHOTOMODE_ACTION_TOGGLE_CAMERA_MODE = 5,
    PHOTOMODE_ACTION_SCREENSHOT = 6,
    PHOTOMODE_ACTION_EXIT = 7
};
