enum photoModeSettingType_t : int
{
    PM_SETTING_TYPE_INVALID = -1,
    PM_SETTING_TYPE_BUTTON = 0,
    PM_SETTING_TYPE_SLIDER = 1,
    PM_SETTING_TYPE_TOGGLE = 2,
    PM_SETTING_TYPE_DROP_DOWN_LIST = 3,
    PM_SETTING_TYPE_HORIZONTAL_LIST = 4,
    NUM_PM_SETTING_TYPES = 5
};
