enum physicsForceType_t : int
{
    PHYS_FORCE_PUSH = 0,
    PHYS_FORCE_NONE = 1,
    PHYS_FORCE_DEFAULT = 2,
    PHYS_FORCE_EXPLOSION = 3,
    PHYS_FORCE_WEAPON_DEFAULT = 4,
    PHYS_FORCE_WEAPON_SHOTGUN = 5,
    PHYS_FORCE_WEAPON_PLASMA = 6,
    PHYS_FORCE_WEAPON_ROCKET = 7,
    PHYS_FORCE_WEAPON_GAUSS = 8,
    PHYS_FORCE_MAX = 9
};
