enum physicsType_t : int
{
    PHYSICS_INVALID = 0,
    PHYSICS_BASE = 1,
    PHYSICS_STATIC = 2,
    PHYSICS_STATICMULTI = 3,
    PHYSICS_AI = 4,
    PHYSICS_PLAYER = 5,
    PHYSICS_PARAMETRIC = 6,
    PHYSICS_PARAMETRIC_MM = 7,
    PHYSICS_RIGIDBODY = 8,
    PHYSICS_RIGIDBODY3DOF = 9,
    PHYSICS_RIGIDCAST = 10,
    PHYSICS_AF = 11,
    PHYSICS_SPHERETREE = 12,
    PHYSICS_VIRTUAL = 13,
    PHYSICS_ACTOR = 14
};
