enum planeType_t : int
{
    PLANETYPE_X = 0,
    PLANETYPE_Y = 1,
    PLANETYPE_Z = 2,
    PLANETYPE_NEGX = 3,
    PLANETYPE_NEGY = 4,
    PLANETYPE_NEGZ = 5,
    PLANETYPE_TRUEAXIAL = 6,
    PLANETYPE_ZEROX = 6,
    PLANETYPE_ZEROY = 7,
    PLANETYPE_ZEROZ = 8,
    PLANETYPE_NONAXIAL = 9
};
