enum playerMechanicInteractType_t : int
{
    PLAYER_MECHANIC_THIRD_PERSON_INTERACT_TYPE_NONE = 0,
    PLAYER_MECHANIC_THIRD_PERSON_INTERACT_TYPE_GENERIC = 1,
    PLAYER_MECHANIC_THIRD_PERSON_INTERACT_TYPE_SENTINEL_CRYSTAL = 2,
    PLAYER_MECHANIC_THIRD_PERSON_INTERACT_TYPE_BUTTON = 3,
    NUM_PLAYER_MECHANIC_THIRD_PERSON_INTERACT_TYPES = 4
};
