enum playerBodyReactionDir_t : int
{
    PLAYER_BODY_REACTION_DIR_1_N = 0,
    PLAYER_BODY_REACTION_DIR_4_N = 0,
    PLAYER_BODY_REACTION_DIR_4_E = 1,
    PLAYER_BODY_REACTION_DIR_4_S = 2,
    PLAYER_BODY_REACTION_DIR_4_W = 3,
    PLAYER_BODY_REACTION_DIR_8_N = 0,
    PLAYER_BODY_REACTION_DIR_8_NE = 1,
    PLAYER_BODY_REACTION_DIR_8_E = 2,
    PLAYER_BODY_REACTION_DIR_8_SE = 3,
    PLAYER_BODY_REACTION_DIR_8_S = 4,
    PLAYER_BODY_REACTION_DIR_8_SW = 5,
    PLAYER_BODY_REACTION_DIR_8_W = 6,
    PLAYER_BODY_REACTION_DIR_8_NW = 7
};
