enum playerBadgeDisplayState_t : int
{
    PLAYER_BADGE_DISPLAY_STATE_CURRENT = 0,
    PLAYER_BADGE_DISPLAY_STATE_PREVIOUS = 1,
    PLAYER_BADGE_DISPLAY_STATE_ANIMATE_XP_GAIN = 2,
    NUM_PLAYER_BADGE_DISPLAY_STATES = 3
};
