enum playerArmorType_t : int
{
    PLAYER_ARMOR_NONE = -1,
    PLAYER_ARMOR_ADVENTURER = 0,
    PLAYER_ARMOR_ROGUE = 1,
    PLAYER_ARMOR_ROUGHNECK = 2,
    PLAYER_ARMOR_WASTELANDER = 3,
    PLAYER_ARMOR_MAX = 4
};
