enum playerBadgeRankType_t : int
{
    PLAYER_BADGE_RANK_TYPE_NONE = 0,
    PLAYER_BADGE_RANK_TYPE_BATTLEMODE_SLAYER = 1,
    PLAYER_BADGE_RANK_TYPE_BATTLEMODE_DEMON = 2,
    NUM_PLAYER_BADGE_RANK_TYPES = 3
};
