enum playerWeaponAnimSet_t : int
{
    WEAPONANIM_RIFLE = 0,
    WEAPONANIM_SHOTGUN = 1,
    WEAPONANIM_ROCKET_LAUNCHER = 2,
    WEAPONANIM_CHAINGUN = 3,
    WEAPONANIM_CHAINSAW = 4,
    WEAPONANIM_PISTOL = 5,
    WEAPONANIM_FISTS = 6,
    WEAPONANIM_CHARGEBALL = 7,
    WEAPONANIM_CRUCIBLE = 8,
    WEAPONANIM_CLIMBING = 9,
    WEAPONANIM_SWIMMING = 10,
    WEAPONANIM_MAX = 11
};
