enum playerAbilities_t : int
{
    PLAYER_ABILITY_NONE = 0,
    PLAYER_ABILITY_CHANGE_WEAPON = 1,
    PLAYER_ABILITY_CHANGE_AMMO = 2,
    PLAYER_ABILITY_RELOAD = 4,
    PLAYER_ABILITY_ZOOM = 8,
    PLAYER_ABILITY_THROW = 16,
    PLAYER_ABILITY_QUICK_USE = 32,
    PLAYER_ABILITY_COVER_LEAN = 64,
    PLAYER_ABILITY_MELEE = 128,
    PLAYER_ABILITY_SHOOT = 256,
    PLAYER_ABILITY_JUMP = 512,
    PLAYER_ABILITY_CROUCH = 1024,
    PLAYER_ABILITY_DASH = 2048
};
