enum playerBadgeDisplayStyle_t : int
{
    PLAYER_BADGE_DISPLAY_STYLE_INVALID = -1,
    PLAYER_BADGE_DISPLAY_STYLE_FULL = 0,
    PLAYER_BADGE_DISPLAY_STYLE_MINI = 1,
    PLAYER_BADGE_DISPLAY_STYLE_SIMPLE_DEMON = 2,
    PLAYER_BADGE_DISPLAY_STYLE_SIMPLE_SLAYER = 3,
    PLAYER_BADGE_DISPLAY_STYLE_BATTLEMODE_DEMON = 4,
    PLAYER_BADGE_DISPLAY_STYLE_BATTLEMODE_SLAYER = 5,
    NUM_PLAYER_BADGE_DISPLAY_STYLES = 6
};
