enum playerUpgradeCurrency_t : int
{
    CURRENCY_WEAPON_UPGRADE = 0,
    CURRENCY_PRAETOR_UPGRADE = 1,
    CURRENCY_WEAPON_MASTERY = 2,
    CURRENCY_RUNE_MASTERY = 3,
    CURRENCY_SENTINEL_BATTERY = 4,
    CURRENCY_SLAYER_BATTERY = 5,
    CURRENCY_HAMMER_UPGRADE = 6,
    CURRENCY_LIFE_GATES = 7,
    CURRENCY_RUNE_CRYSTALS = 8,
    NUM_UPGRADE_CURRENCY = 9
};
