enum playerTorsoAnims_t : int
{
    PT_ANIM_WEAPON_DOWN = 0,
    PT_ANIM_WEAPON_UP = 1,
    PT_ANIM_MELEE = 2,
    PT_ANIM_MELEE_LEFT = 3,
    PT_ANIM_MELEE_RIGHT = 4,
    PT_ANIM_GRENADE_ATTACH = 5,
    PT_ANIM_GRENADE_THROW = 6,
    PT_ANIM_POSE_ADS = 7,
    PT_ANIM_ATTACK = 8,
    PT_ANIM_ATTACK_2 = 9,
    PT_ANIM_CHAINSAW_SWIPE = 10,
    PT_ANIM_CHAINSAW_SWIPE_AGAIN = 11,
    PT_ANIM_MAX = 12
};
