enum posePositionDirection_t : int
{
    DIRECTION_NONE = 0,
    DIRECTION_NONE_TARGET_RELATIVE = 1,
    DIRECTION_FORWARD = 2,
    DIRECTION_BACKWARD = 3,
    DIRECTION_LEFT = 4,
    DIRECTION_RIGHT = 5,
    DIRECTION_EVADE = 6
};
