enum powerCoreColor_t : int
{
    POWER_CORE_COLOR_WHITE = 0,
    POWER_CORE_COLOR_RED = 1,
    POWER_CORE_COLOR_BLUE = 2,
    POWER_CORE_COLOR_GREEN = 3,
    POWER_CORE_COLOR_YELLOW = 4,
    POWER_CORE_COLOR_COUNT = 5
};
