enum profileFlag_t : int
{
    PROFILE_FLAG_NONE = 0,
    PROFILE_FLAG_SEVERITY_LOG = 1,
    PROFILE_FLAG_SEVERITY_WARNING = 2,
    PROFILE_FLAG_SEVERITY_ERROR = 4,
    PROFILE_FLAG_SEVERITY_RESERVED = 8,
    PROFILE_FLAG_ZONE_LABEL = 16,
    PROFILE_FLAG_ZONE_SUBLABEL = 32,
    PROFILE_FLAG_ZONE_SHOW_IN_PARENTS = 64,
    PROFILE_FLAG_ZONE_RESERVED01 = 128,
    PROFILE_FLAG_ICON_EXCLAMATION = 4096,
    PROFILE_FLAG_ICON_NOTE = 8192,
    PROFILE_FLAG_ICON_QUESTION_MARK = 12288,
    PROFILE_FLAG_ICON_EXTRA00 = 16384,
    PROFILE_FLAG_ICON_EXTRA01 = 20480,
    PROFILE_FLAG_ICON_EXTRA02 = 24576,
    PROFILE_FLAG_ICON_EXTRA03 = 28672,
    PROFILE_FLAG_ICON_EXTRA04 = 32768,
    PROFILE_FLAG_CALLSTACK = 65536
};
