enum profileState_t : int
{
    PROFILE_STATE_IDLE = 0,
    PROFILE_STATE_SAVING = 1,
    PROFILE_STATE_LOADING = 2,
    PROFILE_STATE_SAVE_REQUESTED = 3,
    PROFILE_STATE_LOAD_REQUESTED = 4,
    PROFILE_STATE_ERR = 5
};
