enum profileUnit_t : int
{
    PROFILE_UNIT_REAL = 0,
    PROFILE_UNIT_MEMORY = 1,
    PROFILE_UNIT_HEX = 2,
    PROFILE_UNIT_INTEGER = 3,
    PROFILE_UNIT_PERCENT_COMPUTED = 4,
    PROFILE_UNIT_PERCENT_DIRECT = 5,
    PROFILE_UNIT_TIME = 6,
    PROFILE_UNIT_TIME_MS = 7,
    PROFILE_UNIT_TIME_US = 8,
    PROFILE_UNIT_TIME_CLOCKS = 9,
    PROFILE_UNIT_TIME_INTERVAL = 10
};
