enum profileZone_t : int
{
    PROFILE_ZONE_NONE = 0,
    PROFILE_ZONE_STALL = 2,
    PROFILE_ZONE_IDLE = 4,
    PROFILE_ZONE_CONTEXT_SWITCH = 8,
    PROFILE_ZONE_PLOT_TIME = 16,
    PROFILE_ZONE_HAS_ACCUMULATION = 32,
    PROFILE_ZONE_ACCUMULATION = 64,
    PROFILE_ZONE_LOCK_HOLD = 128,
    PROFILE_ZONE_LOCK_WAIT = 256
};
