enum profilePriority_t : int
{
    PROFILE_PRIORITY_NEVER = -1,
    PROFILE_PRIORITY_LOWEST = 0,
    PROFILE_PRIORITY_LOW = 63,
    PROFILE_PRIORITY_MEDIUM = 127,
    PROFILE_PRIORITY_HIGH = 191,
    PROFILE_PRIORITY_HIGHEST = 255
};
