enum progressionCategory_t : int
{
    PROGRESSION_CATEGORY_INVALID = -1,
    PROGRESSION_CATEGORY_MODBOT = 0,
    PROGRESSION_CATEGORY_ARGENT = 1,
    PROGRESSION_CATEGORY_ELITE = 2,
    PROGRESSION_CATEGORY_RUNE = 3,
    PROGRESSION_CATEGORY_SECRETS = 4,
    PROGRESSION_CATEGORY_WEAPON = 5,
    PROGRESSION_CATEGORY_COLLECTIBLE = 6,
    PROGRESSION_CATEGORY_COLLECTIBLE_ALBUM = 7,
    PROGRESSION_CATEGORY_CODEX = 8,
    PROGRESSION_CATEGORY_BATTERY = 9,
    PROGRESSION_CATEGORY_CHEAT = 10,
    PROGRESSION_CATEGORY_EMPYREON_SHARD = 11,
    PROGRESSION_CATEGORY_SUPPORT_RUNE = 12,
    PROGRESSION_CATEGORY_COLLECTIBLE_COSMETIC = 13,
    PROGRESSION_CATEGORY_SECRET_ENCOUNTER_ZERO_WEAPON_POINTS = 14,
    PROGRESSION_CATEGORY_ESCALATION_ENCOUNTER = 15,
    PROGRESSION_CATEGORY_MAX = 16
};
