enum programParmScope_t : int
{
    PROGRAM_PARM_SCOPE_COMPUTE_RASTER = 0,
    PROGRAM_PARM_SCOPE_RAY_GEN = 1,
    PROGRAM_PARM_SCOPE_HIT = 2,
    PROGRAM_PARM_SCOPE_MISS = 3,
    PROGRAM_PARM_SCOPE_NUM = 4
};
