enum programType_t : int
{
    PROGRAM_TYPE_VERTEX = 0,
    PROGRAM_TYPE_FRAGMENT = 1,
    PROGRAM_TYPE_COMPUTE = 2,
    PROGRAM_TYPE_GEOMETRY = 3,
    PROGRAM_TYPE_RAY_GEN = 4,
    PROGRAM_TYPE_ANY_HIT = 5,
    PROGRAM_TYPE_CLOSEST_HIT = 6,
    PROGRAM_TYPE_MISS = 7,
    PROGRAM_TYPE_NUM = 8
};
