enum progressionEventID_t : int
{
    INTERACTABLE_EVENT_INVALID = -1,
    INTERACTABLE_EVENT_SPAWN = 0,
    INTERACTABLE_EVENT_HIDE = 1,
    INTERACTABLE_EVENT_SHOW = 2,
    INTERACTABLE_EVENT_USED = 3,
    SECRET_EVENT_SPAWN = 4,
    SECRET_EVENT_FOUND = 5,
    COLLECTIBLE_EVENT_PICKUP = 6,
    CODEX_EVENT_ACQUIRED = 7,
    ENCOUNTER_EVENT_SPAWN = 8,
    ENCOUNTER_EVENT_END = 9
};
