enum prohibitionEnforcementType_t : int
{
    PROHIBITION_ENFORCEMENT_TYPE_INVALID = 0,
    PROHIBITION_ENFORCEMENT_TYPE_NONE = 1,
    PROHIBITION_ENFORCEMENT_TYPE_PROBATION = 2,
    PROHIBITION_ENFORCEMENT_TYPE_BANNED = 3
};
