enum prowlerCalculationState_t : int
{
    PROWLERCALCSTATE_PENDING = 0,
    PROWLERCALCSTATE_STARTING = 1,
    PROWLERCALCSTATE_SOLID_TRACE = 2,
    PROWLERCALCSTATE_ATTACH_CHECK = 3,
    PROWLERCALCSTATE_ALT_SOLID_TRACE = 4,
    PROWLERCALCSTATE_ALT_ATTACH_CHECK = 5,
    PROWLERCALCSTATE_HEAD_SMASH_CHECK = 6,
    PROWLERCALCSTATE_DONE = 7,
    PROWLERCALCSTATE_NUM_STATES = 8
};
