enum prowlerTeleportType_t : int
{
    PROWLERTELEPORTTYPE_NONE = 0,
    PROWLERTELEPORTTYPE_PERCHWALL = 1,
    PROWLERTELEPORTTYPE_PERCHHANG = 2,
    PROWLERTELEPORTTYPE_GROUND = 3,
    PROWLERTELEPORTTYPE_TELEPORTER = 4,
    PROWLERTELEPORTTYPE_MAX = 5
};
