enum prtAnimationType_t : int
{
    PANIM_TYPE_CYLE_RATE = 0,
    PANIM_TYPE_SINGLE_CYCLE_RATE = 1,
    PANIM_TYPE_SINGLE_CYCLE = 2,
    PANIM_TYPE_ABSOLUTE = 3,
    PANIM_TYPE_SINGLE_CYCLE_ABSOLTE = 4,
    NUM_PANIM_TYPES = 5
};
