enum prtAlignmentType_t : int
{
    PALIGN_TYPE_VIEW = 0,
    PALIGN_TYPE_CAMERA = 1,
    PALIGN_TYPE_VELOCITY_STRETCH = 2,
    PALIGN_TYPE_VELOCITY = 3,
    PALIGN_TYPE_RIBBON = 4,
    PALIGN_TYPE_WORLD = 5,
    PALIGN_TYPE_EMITTER = 6,
    PALIGN_TYPE_VIEW_WORLD_Z = 7,
    PALIGN_TYPE_VIEW_EMITTER_Z = 8,
    NUM_PALIGN_TYPES = 9
};
