enum prtDistributionType_t : int
{
    PDIST_RECT = 0,
    PDIST_CYLINDER = 1,
    PDIST_SPHERE = 2,
    PDIST_RECT_SURFACE = 3,
    PDIST_CYLINDER_SURFACE = 4,
    PDIST_SPHERE_SURFACE = 5,
    PDIST_CORNERS = 6,
    PDIST_GRID = 7,
    NUM_PDIST_TYPES = 8
};
