enum prtRenderModeOld_t : int
{
    PRENDER_MODE_OLD_UNLIT = 0,
    PRENDER_MODE_OLD_LIT = 1,
    PRENDER_MODE_OLD_LIQUID = 2,
    PRENDER_MODE_OLD_LAVA = 3,
    PRENDER_MODE_OLD_EXPLOSION = 4,
    PRENDER_MODE_OLD_MATERIAL = 5,
    NUM_PRENDER_MODES_OLD = 6
};
