enum prtSpawnCondition_t : int
{
    PSPAWN_CONDITION_NONE = 0,
    PSPAWN_CONDITION_IN_TIMESPAN = 1,
    PSPAWN_CONDITION_ON_DEATH = 2,
    PSPAWN_CONDITION_ON_BIRTH = 3,
    PSPAWN_CONDITION_ON_COLLISION = 4,
    NUM_PSPAWN_CONDITION = 5
};
