enum pushFlags_t : int
{
    PUSHFL_CLIP = 1,
    PUSHFL_NOPUSH = 2,
    PUSHFL_RIGIDBODYONLY = 4,
    PUSHFL_NOGROUNDENTITIES = 8,
    PUSHFL_CRUSH = 16,
    PUSHFL_APPLYIMPULSE = 32,
    PUSHFL_PUSH_PROP = 64,
    PUSHFL_PUSH_AI = 128
};
