enum rayTracingInstanceMask_t : int
{
    RT_INSTANCE_MASK_GROUP_0 = 1,
    RT_INSTANCE_MASK_GROUP_1 = 2,
    RT_INSTANCE_MASK_GROUP_2 = 4,
    RT_INSTANCE_MASK_GROUP_3 = 16,
    RT_INSTANCE_MASK_NONE = 0,
    RT_INSTANCE_MASK_ALL = 255
};
