enum rejectReason_t : int
{
    REJ_INVALID = 0,
    REJ_NONE = 1,
    REJ_UNALIGNED_SOURCE = 2,
    REJ_UNALIGNED_MOVE = 3,
    REJ_UNALIGNED_APEX = 4,
    REJ_OUTOFRANGE = 5,
    REJ_NEEDMORETURN = 6,
    REJ_NAVPROBEFAIL = 7,
    REJ_REQUIRED_FLAG_MISMATCH = 8,
    REJ_ALLOWED_FLAG_MISMATCH = 9,
    REJ_NAVPROBEFAIL_APEX = 10,
    REJ_NAVPROBEFAIL_TRANS = 11,
    REJ_NAVPROBEFAIL_END_TO_PATH = 12,
    REJ_WAITING_FOR_TRACE = 13,
    REJ_ANIM_OVERSHOOT = 14,
    REJ_LONGER_PATH = 15,
    REJ_WRONG_INJURY = 16,
    REJ_MAX = 17
};
