enum renderModelType_t : int
{
    RENDERMODEL_PARTICLE = 0,
    RENDERMODEL_FLARE = 1,
    RENDERMODEL_BEAM = 2,
    RENDERMODEL_RIBBON = 3,
    RENDERMODEL_NUM_UPDATEINVIEW = 4,
    RENDERMODEL_DEFAULT = 4,
    RENDERMODEL_TRACERS = 5,
    RENDERMODEL_EFFECTS = 6,
    RENDERMODEL_DISCRETEANIMATION = 7,
    RENDERMODEL_SKINNED = 8,
    RENDERMODEL_STATIC = 9,
    RENDERMODEL_TRANSPARENCY = 10,
    RENDERMODEL_DECAL = 11,
    RENDERMODEL_GUI = 12,
    RENDERMODEL_GEOMCACHE = 13,
    RENDERMODEL_TEXT = 14,
    RENDERMODEL_STATICINSTANCE = 15,
    RENDERMODEL_BRUSH = 16,
    RENDERMODEL_MAX_TYPE = 17
};
