enum renderContexts_t : int
{
    RENDER_CONTEXT_MAIN = 0,
    RENDER_CONTEXT_VIEW_MAIN = 1,
    RENDER_CONTEXT_MVP_CULLING = 2,
    RENDER_CONTEXT_STREAMING = 3,
    RENDER_CONTEXT_CLUSTER_SETUP_SHADOWS = 4,
    RENDER_CONTEXT_DEPTH_OCCLUSION = 5,
    RENDER_CONTEXT_CLUSTER_SETUP_TILES = 6,
    RENDER_CONTEXT_OPAQUE_FOG_DEFERRED_LIGHTATLAS = 7,
    RENDER_CONTEXT_EMISSIVE_BLEND = 8,
    RENDER_CONTEXT_POST_PROCESS_GUI = 9,
    RENDER_CONTEXT_END_FRAME = 10,
    RENDER_CONTEXT_NUM = 11
};
