enum repulsorFlags_t : int
{
    REPULSOR_FLAG_NONE = 0,
    REPULSOR_TEAM_MASK = 7,
    REPULSOR_FLAG_SUM_RADII = 512,
    REPULSOR_FLAG_FRIENDLY_RADIUS = 1024,
    REPULSOR_FLAG_ENEMY_RADIUS = 2048,
    REPULSOR_FLAG_SYNC_MELEE = 4096,
    REPULSOR_FLAG_INCAPACITATED = 8192,
    REPULSOR_FLAG_NO_RADIUS_FIXUP_DELTA = 16384
};
