enum resourceError_t : int
{
    RESOURCE_ERROR_NONE = 0,
    RESOURCE_ERROR_MISC = 1,
    RESOURCE_ERROR_FILE_NOT_FOUND = 2,
    RESOURCE_ERROR_WRONG_TYPE = 3,
    RESOURCE_ERROR_INVALID_NAME = 4,
    RESOURCE_ERROR_HEADER_VERSION_MISMATCH = 5,
    RESOURCE_ERROR_RESOURCE_VERSION_MISMATCH = 6,
    RESOURCE_ERROR_INVALID_ALLOCATION_TABLE = 7,
    RESOURCE_ERROR_OUT_OF_DATE = 8,
    RESOURCE_ERROR_INVALID_DATA_BLOCK = 9,
    RESOURCE_ERROR_FAILED_TO_WRITE_BINARY = 10,
    RESOURCE_ERROR_FATAL = 11,
    RESOURCE_ERROR_TRUNCATED = 12,
    RESOURCE_ERROR_INVALID_SOURCE_VERSION = 13,
    RESOURCE_ERROR_UNKNOWN_TOKEN = 14,
    RESOURCE_ERROR_NOT_IMPLEMENTED = 15,
    RESOURCE_ERROR_MAX = 16
};
