enum ribbonShape_t : int
{
    RIBBON_SHAPE_FLAT = 0,
    RIBBON_SHAPE_CROSS = 1,
    RIBBON_SHAPE_TRIANGLE = 2,
    RIBBON_SHAPE_QUADRILATERAL = 3,
    RIBBON_SHAPE_PENTAGON = 4,
    RIBBON_SHAPE_HEXAGON = 5,
    RIBBON_SHAPE_HEPTAGON = 6,
    RIBBON_SHAPE_OCTOGON = 7
};
