enum ruleOperation_t : int
{
    RULE_OPERATION_GREATER_THAN_VALUE = 0,
    RULE_OPERATION_LESS_THAN_VALUE = 1,
    RULE_OPERATION_EQUALS = 2,
    RULE_OPERATION_DOES_NOT_EQUALS = 3,
    RULE_OPERATION_LESS_THAN_PERCENTAGE = 4,
    RULE_OPERATION_GREATER_THAN_PERCENTAGE = 5
};
