enum runeId_t : int
{
    RUNE_UNKNOWN = -1,
    RUNE_AMMO_BOOST = 0,
    RUNE_EQUIPMENT_FIEND = 1,
    RUNE_BLOOD_PUNCH = 2,
    RUNE_BLOOD_FUELED = 3,
    RUNE_TARGET_STRIKE = 4,
    RUNE_SAVING_THROW = 5,
    RUNE_AIR_CONTROL = 6,
    RUNE_PUNCH_AND_REAVE = 7,
    RUNE_DASH_DAMAGE_BOOST = 8,
    RUNE_SEEK_AND_DESTROY = 9,
    RUNE_SAVAGERY = 10,
    RUNE_DAZED_AND_CONFUSED = 11,
    RUNE_OTHER = 12,
    SUPPORT_RUNE_BLOOD_PUNCH = 13,
    SUPPORT_RUNE_DOMINATION = 14,
    SUPPORT_RUNE_WEAKPOINT = 15,
    SUPPORT_RUNE_SENTINEL_HAMMER = 16,
    SUPPORT_RUNE_HAMMER_SLAM_RADIUS = 17
};
