enum runIndexType_t : int
{
    ANIMWEBAI_RUNINDEXTYPE_NORMAL = 0,
    ANIMWEBAI_RUNINDEXTYPE_INJURED = 1,
    ANIMWEBAI_RUNINDEXTYPE_SCRAMBLE = 2,
    ANIMWEBAI_RUNINDEXTYPE_FAR = 3,
    ANIMWEBAI_RUNINDEXTYPE_GUNDOWN = 4,
    ANIMWEBAI_RUNINDEXTYPE_NARROW = 5,
    ANIMWEBAI_RUNINDEXTYPE_UP_STAIRS = 6,
    ANIMWEBAI_RUNINDEXTYPE_DOWN_STAIRS = 7,
    ANIMWEBAI_RUNINDEXTYPE_DUCK = 8,
    ANIMWEBAI_RUNINDEXTYPE_MAX = 9
};
