enum saveGameType_t : int
{
    SAVEGAMEFILE_NONE = 0,
    SAVEGAMEFILE_TEXT = 1,
    SAVEGAMEFILE_BINARY = 2,
    SAVEGAMEFILE_COMPRESSED = 4,
    SAVEGAMEFILE_UNUSED = 8,
    SAVEGAMEFILE_THUMB = 16,
    SAVEGAMEFILE_BKGRND_IMAGE = 32,
    SAVEGAMEFILE_AUTO_DELETE = 64,
    SAVEGAMEFILE_OPTIONAL = 128,
    SAVEGAMEFILE_NOT_SENSITIVE = 256
};
