enum scFileStatus_t : int
{
    SCF_UNKNOWN = 0,
    SCF_NOTMANAGED = 1,
    SCF_NOTIMPORTED = 2,
    SCF_CHECKEDOUT = 3,
    SCF_CHECKEDOUT_PLUS = 4,
    SCF_CHECKEDOUT_BYOTHER = 5,
    SCF_CHECKEDOUT_BYOTHER_EXCLUSIVE = 6,
    SCF_CHECKEDIN = 7,
    SCF_MARKEDFORADD = 8,
    SCF_MARKEDFORMOVE = 9,
    SCF_MARKEDFORDELETION = 10,
    SCF_UNRESOLVED = 11
};
