enum scModifyAction_t : int
{
    SCMA_FILE_UNKNOWN_ACTION = 0,
    SCMA_FILE_ADD = 1,
    SCMA_FILE_EDIT = 2,
    SCMA_FILE_DELETE = 3,
    SCMA_FILE_BRANCH = 4,
    SCMA_FILE_MOVE_ADD = 5,
    SCMA_FILE_MOVE_DELETE = 6,
    SCMA_FILE_INTEGRATE = 7,
    SCMA_FILE_IMPORT = 8,
    SCMA_FILE_PURGE = 9,
    SCMA_FILE_ARCHIVE = 10
};
