enum seasonsSummarySoundId_t : int
{
    SEASONS_SUMMARY_SOUND_BOOSTER_CLAIM_START = 0,
    SEASONS_SUMMARY_SOUND_BOOSTER_CLAIM_LOOP = 0,
    SEASONS_SUMMARY_SOUND_BOOSTER_CLAIM_END = 0,
    SEASONS_SUMMARY_SOUND_LEVEL_COMPLETE = 0
};
