enum settingsScreenTabID_t : int
{
    SETTINGS_TAB_INVALID = -1,
    SETTINGS_TAB_GAME = 0,
    SETTINGS_TAB_UI = 1,
    SETTINGS_TAB_CONTROLS = 2,
    SETTINGS_TAB_VIDEO = 3,
    SETTINGS_TAB_AUDIO = 4,
    SETTINGS_TAB_ACCESSIBILITY = 5,
    SETTINGS_TAB_LEGAL = 6,
    NUM_SETTINGS_TABS = 7
};
