enum shellState_t : int
{
    SHELL_STATE_INVALID = -1,
    SHELL_STATE_PRESS_START = 0,
    SHELL_STATE_INITIAL_SCREEN = 1,
    SHELL_STATE_LOADING = 2,
    SHELL_STATE_BUSY = 3,
    SHELL_STATE_IN_GAME = 4
};
