enum slayerScoringActionsPvp_t : int
{
    SSA_INVALID = -1,
    SSA_DAMAGE_INFLICTED = 0,
    SSA_AI_KILL = 1,
    SSA_AI_GK = 2,
    SSA_SPEC_WEAPON_KILL = 3,
    SSA_DEMON_PLAYER_KILL = 4,
    SSA_DIRECT_HIT_SPEC_WEAPON = 5,
    SSA_KILL_BEFORE_ARMOR_DEPLETION = 6,
    SSA_HEALTH_RECOVERY = 7,
    SSA_AMMO_RECOVERY = 8,
    SSA_NO_HEALTH_LOSS_WIN = 9,
    SSA_UNCOVER_DISGUISED_DEMON = 10,
    SSA_MAX = 11
};
