enum smmLaserSettings_t : int
{
    SMM_LASER_SETTING_NORMAL = 0,
    SMM_LASER_SETTING_SWEEP = 1,
    SMM_LASER_MELEE_TURN = 2,
    SMM_LASER_WOUNDED_MELEE = 3,
    SMM_LASER_WOUNDED_TURN = 4,
    SMM_LASER_WOUNDED_MELEE_TURN = 5,
    SMM_LASER_WOUNDED_CANNON = 6,
    SMM_LASER_SETTING_MAX = 7
};
