enum socialBarAction_t : int
{
    CMD_SOCIAL_BAR_NOOP = 0,
    CMD_SOCIAL_BAR_SOCIAL_BUTTON_PRESSED = 1,
    CMD_SOCIAL_BAR_OFFLINE_BUTTON_PRESSED = 2,
    CMD_SOCIAL_BAR_TOGGLE_CHAT = 3,
    CMD_SOCIAL_BAR_SET_CHANNEL = 4
};
