enum socialBarSoundId_t : int
{
    SOCIAL_BAR_SOUND_INVALID = 0,
    SOCIAL_BAR_SOUND_MATCHMAKING_STARTED = 0,
    SOCIAL_BAR_SOUND_MATCHMAKING_SUCCESS = 0,
    SOCIAL_BAR_SOUND_MATCHMAKING_FAILED = 0,
    SOCIAL_BAR_SOUND_MATCHMAKING_CANCELED = 0,
    SOCIAL_BAR_SOUND_SERVER_LAUNCH_FAILED = 0
};
