enum socialEmotion_t : int
{
    EMOTION_MIN = 0,
    EMOTION_TERRIFIED = 1,
    EMOTION_FEAR = 2,
    EMOTION_WARY = 3,
    EMOTION_DESTROY_AT_ALL_COSTS = 4,
    EMOTION_DESTROY_PRIORITY = 5,
    EMOTION_DESTROY = 6,
    EMOTION_HATE = 7,
    EMOTION_ANGER = 8,
    EMOTION_DISLIKE = 9,
    EMOTION_ANNOYED = 10,
    EMOTION_NEUTRAL = 11,
    EMOTION_FRIENDLY = 12,
    EMOTION_SQUADMATE = 13,
    EMOTION_PARTNER = 14,
    EMOTION_MAX = 15
};
