enum socialBarNotificationType_t : int
{
    SOCIAL_BAR_NOTIFICATION_TYPE_NONE = 0,
    SOCIAL_BAR_NOTIFICATION_TYPE_DEBUG = 1,
    SOCIAL_BAR_NOTIFICATION_TYPE_MATCHMAKING_STARTED = 2,
    SOCIAL_BAR_NOTIFICATION_TYPE_MATCHMAKING_FAILED = 3,
    SOCIAL_BAR_NOTIFICATION_TYPE_MATCHMAKING_CANCELED = 4,
    SOCIAL_BAR_NOTIFICATION_TYPE_MATCHMAKING_COMPLETE = 5,
    SOCIAL_BAR_NOTIFICATION_TYPE_RECONNECTING = 6,
    SOCIAL_BAR_NOTIFICATION_TYPE_SERVER_LAUNCH_FAILED = 7
};
