enum spawnInfluenceScoreType_t : int
{
    INFLUENCE_INVALID = -1,
    INFLUENCE_SCATTER = 0,
    INFLUENCE_ENEMY_PLAYER = 1,
    INFLUENCE_ALLY_PLAYER = 2,
    INFLUENCE_ALLY_PLAYER_FORBID = 3,
    INFLUENCE_ENEMY_LOS = 4,
    INFLUENCE_ALLY_LOS = 5,
    INFLUENCE_WEAPON = 6,
    INFLUENCE_PROJECTILES = 7,
    INFLUENCE_PLAYER_DEATH = 8,
    INFLUENCE_FLAG = 9,
    INFLUENCE_CONTROL_POINT = 10,
    INFLUENCE_MAX = 11
};
