enum spriteAlignment_t : int
{
    SPRITE_ALIGNMENT_VIEW = 0,
    SPRITE_ALIGNMENT_CAMERA = 1,
    SPRITE_ALIGNMENT_VELOCITY_STRETCH = 2,
    SPRITE_ALIGNMENT_VELOCITY = 3,
    SPRITE_ALIGNMENT_RIBBON = 4,
    SPRITE_ALIGNMENT_MAX = 5
};
