enum stateExecutionFlags_t : int
{
    FLAGS_NONE = 0,
    FLAGS_PULL_TRIGGER_ON_ENTER = 1,
    FLAGS_PREPARE_FIRING_SEQUENCE = 2,
    FLAGS_FINISH_FIRING_SEQUENCE = 4,
    FLAGS_UPDATE_EVERY_FRAME = 8,
    FLAGS_CLEAR_WEAPON_FOCUS_ON_ENTER = 16,
    FLAGS_CLEAR_WEAPON_FOCUS_ON_EXIT = 32,
    FLAGS_KEEP_NEW_WALKSTATE = 64,
    FLAGS_COMMIT_ACTION_TARGET = 128
};
