enum stateFlags_t : unsigned int
{
    STATEFL_UNINTERRUPTIBLE = 1,
    STATEFL_UPDATE_IMMEDIATELY = 2,
    STATEFL_REQUIRESWORKTRANS = 8,
    STATEFL_PASSTHROUGH = 16,
    STATEFL_KEEP_PREVIOUS_CHILD = 32,
    STATEFL_LEAVE_CHILD_WORKING = 64,
    STATEFL_BLOCKS_SCRIPT = 128,
    STATEFL_STOPS_MOVEMENT = 256,
    STATEFL_AUTO_LOCOMOTION_ANIMS = 512,
    STATEFL_AUTO_IDLE_ANIMS = 1024,
    STATEFL_SHARED = 2048,
    STATEFL_CHECK_CAN_USE = 4096,
    STATEFL_INITIALIZED = 32768
};
