enum stateFunctionFlags_t : unsigned int
{
    STATEFUNCTION_NONE = 0,
    STATEFUNCTION_TOKENS = 1,
    STATEFUNCTION_OFF_LIMITS = 2,
    STATEFUNCTION_IS_VALID = 4,
    STATEFUNCTION_WORK = 8,
    STATEFUNCTION_TIMERS_ENTER = 16,
    STATEFUNCTION_TIMERS_EXIT = 32,
    STATEFUNCTION_CONDITIONS_REQUIRED = 64,
    STATEFUNCTION_TRANSITIONS = 128,
    STATEFUNCTION_FINISHED_ONLY = 256
};
