enum statePriority_t : int
{
    STATEPRIORITY_NONE = 0,
    STATEPRIORITY_BACKGROUND = 1,
    STATEPRIORITY_ESSENTIAL = 2,
    STATEPRIORITY_IMMEDIATE = 3,
    STATEPRIORITY_FORCED = 4,
    STATEPRIORITY_UNINTERRUPTIBLE = 5,
    STATEPRIORITY_MAX = 6
};
