enum streamerCompression_t : unsigned char
{
    STREAMER_COMPRESSION_NONE_IMAGE = 0,
    STREAMER_COMPRESSION_KRAKEN_IMAGE = 1,
    STREAMER_COMPRESSION_WBP_IMAGE = 2,
    STREAMER_COMPRESSION_NONE_MODEL = 3,
    STREAMER_COMPRESSION_KRAKEN_MODEL = 4,
    STREAMER_COMPRESSION_PACKET_KRAKEN_IMAGE = 5,
    STREAMER_COMPRESSION_KRAKEN_GEOM_CACHE_STATIC_DATA = 6,
    STREAMER_COMPRESSION_KRAKEN_GEOM_CACHE_ANIMATION = 7,
    STREAMER_COMPRESSION_NONE_TRIANGLEFAN = 8,
    STREAMER_COMPRESSION_KRAKEN_TRIANGLEFAN = 9,
    STREAMER_COMPRESSION_RESOURCE_IMAGE = 10,
    STREAMER_COMPRESSION_COUNT = 11
};
