enum swfConstantType_t : int
{
    CONSTANT_Int = 3,
    CONSTANT_UInt = 4,
    CONSTANT_Double = 6,
    CONSTANT_Utf8 = 1,
    CONSTANT_True = 11,
    CONSTANT_False = 10,
    CONSTANT_Null = 12,
    CONSTANT_Undefined = 0,
    CONSTANT_Namespace = 8,
    CONSTANT_PackageNamespace = 22,
    CONSTANT_PackageInternalNs = 23,
    CONSTANT_ProtectedNs = 24,
    CONSTANT_ExplicitNamespace = 25,
    CONSTANT_StaticProtectedNs = 26,
    CONSTANT_PrivateNs = 5,
    CONSTANT_QName = 7,
    CONSTANT_QNameA = 13,
    CONSTANT_RTQName = 15,
    CONSTANT_RTQNameA = 16,
    CONSTANT_RTQNameL = 17,
    CONSTANT_RTQNameLA = 18,
    CONSTANT_Multiname = 9,
    CONSTANT_MultinameA = 14,
    CONSTANT_MultinameL = 27,
    CONSTANT_MultinameLA = 28,
    CONSTANT_MultinameType = 29
};
