enum swfFontEffects_t : int
{
    SWF_FONT_FX_INVALID = -1,
    SWF_FONT_FX_OUTLINE_THIN_BLACK = 0,
    SWF_FONT_FX_OUTLINE_NORMAL_BLACK = 1,
    SWF_FONT_FX_OUTLINE_THICK_BLACK = 2,
    SWF_FONT_FX_GLOW_THIN_ORANGE = 3,
    SWF_FONT_FX_GLOW_THIN_WHITE = 4,
    SWF_FONT_FX_GLOW_THICK_ORANGE = 5,
    SWF_FONT_FX_DROP_SHADOW_THIN_BLACK = 6,
    SWF_FONT_FX_DROP_SHADOW_NORMAL_BLACK = 7,
    SWF_FONT_FX_DROP_SHADOW_NORMAL_GLITCH = 8,
    SWF_FONT_FX_OUTLINE_NORMAL_BLUE = 9,
    SWF_FONT_FX_OUTLINE_NORMAL_GRAY = 10,
    SWF_FONT_FX_GRADIENT_SHADED = 11,
    SWF_FONT_FX_GRADIENT_SHADED_GLOW = 12,
    SWF_FONT_FX_GRADIENT_SHADED_OUTLINE = 13,
    SWF_FONT_FX_GLOW_NORMAL_RED = 14,
    SWF_MAX_FONT_FX = 15
};
