enum swfFilterType_t : int
{
    SWF_FILTER_INVALID = -1,
    SWF_FILTER_DROPSHADOW = 0,
    SWF_FILTER_BLUR = 1,
    SWF_FILTER_GLOW = 2,
    SWF_FILTER_BEVEL = 3,
    SWF_FILTER_GRADIENTGLOW = 4,
    SWF_FILTER_CONVOLUTION = 5,
    SWF_FILTER_COLORMATRIX = 6,
    SWF_FILTER_GRADIENTBEVEL = 7
};
