enum swfTextRenderMode_t : int
{
    SWF_TEXT_RENDER_NORMAL = 0,
    SWF_TEXT_RENDER_RANDOM_APPEAR = 1,
    SWF_TEXT_RENDER_RANDOM_APPEAR_CAPS = 2,
    SWF_TEXT_RENDER_PARAGRAPH = 3,
    SWF_TEXT_RENDER_AUTOSCROLL = 4,
    SWF_TEXT_RENDER_RANDOM_CAPS = 5,
    SWF_TEXT_RENDER_MODE_COUNT = 6
};
