enum swfUsedFonts_t : int
{
    SWF_FONT_INVALID = -1,
    SWF_FONT_ETERNAL_REG = 0,
    SWF_FONT_ETERNAL_BOLD = 1,
    SWF_FONT_ETERNAL_NUM = 2,
    SWF_FONT_TT_SUPERMOLOT = 3,
    SWF_FONT_ID_TACTICAL = 4,
    SWF_FONT_EUROSTILECONREG = 5,
    SWF_FONT_ETERNAL_REG_JAPANESE = 6,
    SWF_FONT_ETERNAL_BOLD_JAPANESE = 7,
    SWF_FONT_ETERNAL_REG_SCHINESE = 8,
    SWF_FONT_ETERNAL_BOLD_SCHINESE = 9,
    SWF_FONT_ETERNAL_REG_TCHINESE = 10,
    SWF_FONT_ETERNAL_BOLD_TCHINESE = 11,
    SWF_FONT_ETERNAL_REG_KOREAN = 12,
    SWF_FONT_ETERNAL_BOLD_KOREAN = 13,
    SWF_MAX_FONTS = 14
};
