enum SWFWidgetActionHandler_t : int
{
    SWF_ACTION_EVENT_SCROLL_UP_START_REPEATER = 0,
    SWF_ACTION_EVENT_SCROLL_UP_START_REPEATER_VARIABLE = 1,
    SWF_ACTION_EVENT_SCROLL_DOWN_START_REPEATER = 2,
    SWF_ACTION_EVENT_SCROLL_DOWN_START_REPEATER_VARIABLE = 3,
    SWF_ACTION_EVENT_SCROLL_LEFT_START_REPEATER = 4,
    SWF_ACTION_EVENT_SCROLL_RIGHT_START_REPEATER = 5,
    SWF_ACTION_EVENT_STOP_REPEATER = 6,
    SWF_ACTION_EVENT_TAB_NEXT = 7,
    SWF_ACTION_EVENT_TAB_PREV = 8,
    SWF_ACTION_EVENT_PAGE_NEXT = 9,
    SWF_ACTION_EVENT_PAGE_PREV = 10,
    SWF_ACTION_EVENT_DRAG_START = 11,
    SWF_ACTION_EVENT_DRAG_STOP = 12
};
