enum SWFWidgetAction_t : int
{
    SWF_ACTION_NONE = 0,
    SWF_ACTION_COMMAND = 1,
    SWF_ACTION_FUNCTION = 2,
    SWF_ACTION_SCROLL_VERTICAL = 3,
    SWF_ACTION_SCROLL_VERTICAL_VARIABLE = 4,
    SWF_ACTION_SCROLL_HORIZONTAL = 5,
    SWF_ACTION_SCROLL_TAB = 6,
    SWF_ACTION_SCROLL_PAGE = 7,
    SWF_ACTION_START_REPEATER = 8,
    SWF_ACTION_STOP_REPEATER = 9,
    SWF_ACTION_ADJUST_FIELD = 10,
    SWF_ACTION_PRESS_FOCUSED = 11,
    SWF_ACTION_BACK_FOCUSED = 12,
    SWF_ACTION_SCROLL_DRAG_START = 13,
    SWF_ACTION_SCROLL_DRAG_STOP = 14,
    SWF_ACTION_GO_BACK = 15,
    SWF_ACTION_POPUP_CLOSED = 16,
    SWF_ACTION_CHANGE_PROFILE = 17,
    MAX_SWF_ACTION = 18
};
