enum syncQuadrant_t : int
{
    SYNC_SCREEN_QUADRANT_NONE = 0,
    SYNC_SCREEN_QUADRANT_TOP_LEFT = 1,
    SYNC_SCREEN_QUADRANT_TOP_RIGHT = 2,
    SYNC_SCREEN_QUADRANT_BOTTOM_LEFT = 4,
    SYNC_SCREEN_QUADRANT_BOTTOM_RIGHT = 8,
    SYNC_SCREEN_QUADRANT_ANY = 2147483647
};
