enum syncOperator_t : int
{
    SYNC_OPERATOR_NONE = -1,
    SYNC_OPERATOR_GORED = 0,
    SYNC_OPERATOR_NOT_GORED = 1,
    SYNC_OPERATOR_LAST_IN_ENCOUNTER = 2,
    SYNC_OPERATOR_HAS_BLACKBOARD_ENTRY = 3,
    SYNC_OPERATOR_CONTEXT_FLAGS = 4
};
