enum syncParticipantStates_t : int
{
    SYNC_PARTICIPANT_INVALID = 0,
    SYNC_PARTICIPANT_ON_GROUND = 1,
    SYNC_PARTICIPANT_IN_AIR = 2,
    SYNC_PARTICIPANT_PERCHED_WALL = 4,
    SYNC_PARTICIPANT_PERCHED_CEIL = 8,
    SYNC_PARTICIPANT_IN_LEDGE_GRAB = 16
};
