enum textureOptions_t : int
{
    TO_NONE = 0,
    TO_NO_COLOR_COMPRESSION = 1,
    TO_STORAGE_IMAGE = 2,
    TO_DO_NOT_POOL = 4,
    TO_TRANSFER_SRC = 8,
    TO_TRANSFER_DST = 16,
    TO_ASYNC_COMPUTE_CONCURRENT = 32,
    TO_REQUIRES_LAYOUT = 64,
    TO_TRANSFER_QUEUE_CONCURRENT = 128,
    TO_RESOLUTION_SCALE = 256,
    TO_RESIZE_ALIAS = 512,
    TO_DEPTH16_PREFER_FAST_CLEAR = 1024
};
