enum thirdPersonModelFlags_t : int
{
    TPMODELFLAG_AUTO_ALIGN_TO_PLAYER = 1,
    TPMODELFLAG_ANIM_DELTAS_APPLY_TO_PLAYER = 2,
    TPMODELFLAG_ANIM_DELTAS_CLIP = 4,
    TPMODELFLAG_ANIM_DELTAS_SKIP_ONE_FRAME = 8,
    TPMODELFLAG_ANIM_DELTAS_ALSO_ALLOW_PHYSICS_MOVE = 16,
    TPMODELFLAG_ANIM_DELTAS_APPLY_GRAVITY = 32,
    TPMODELFLAG_ANIM_DELTAS_APPLY_FRICTION = 64
};
