enum toolsFlags_t : int
{
    TOOLSFLAG_ZERO = 0,
    TOOLSFLAG_NOCSG = 1,
    TOOLSFLAG_SOUND_CLIP = 2,
    TOOLSFLAG_SOUND_CLIP_TRANS = 4,
    TOOLSFLAG_SOUND_DOOR = 8,
    TOOLSFLAG_SOUND_PORTAL = 16,
    TOOLSFLAG_PVS_CLIP = 32,
    TOOLSFLAG_SOUND_TRIGGER = 64,
    TOOLSFLAG_MANIFOLD_HINT = 128,
    TOOLSFLAG_SOUND_CLIP_SNAP = 256,
    TOOLSFLAG_SOUND_OBSTACLE = 512
};
