enum toolsVisibilityMask_t : unsigned short
{
    ALWAYS_VISIBLE = 0,
    IDSTUDIO = 1,
    IDSTUDIO_NON_LIT = 2,
    IDSTUDIO_OUTLINE = 4,
    IDSTUDIO_OPAQUE = 8,
    IDSTUDIO_TRANSLUCENT = 16,
    IDSTUDIO_CAULK = 32,
    IDSTUDIO_CLIP = 64,
    IDSTUDIO_XY_ONLY = 128,
    IDSTUDIO_CAMERA_ONLY = 256,
    IDSTUDIO_HEIGHTMAPVOLUME_ONLY = 512
};
