enum toolFlag_t : int
{
    EDITOR_NONE = 0,
    EDITOR_IDSTUDIO = 2,
    EDITOR_RADIANT = 4,
    EDITOR_SOUND = 8,
    EDITOR_DECL = 16,
    EDITOR_AF = 32,
    EDITOR_PARTICLE = 64,
    EDITOR_MODELVIEWER = 128,
    EDITOR_TERRAIN = 256,
    EDITOR_ENVIRONMENT = 512,
    EDITOR_TEXLOD = 1024,
    EDITOR_FX = 2048,
    EDITOR_TIMELINE = 4096,
    EDITOR_ANIMWEBEDITOR = 8192,
    EDITOR_BUGREPORTER = 16384
};
