enum touchOperation_t : int
{
    TOUCH_OP_TOUCH = 0,
    TOUCH_OP_TAP = 1,
    TOUCH_OP_DOUBLE_TAP = 2,
    TOUCH_OP_FLICK = 3,
    TOUCH_OP_SWIPE = 4,
    TOUCH_OP_DRAG_X = 5,
    TOUCH_OP_DRAG_Y = 6,
    TOUCH_OP_TOUCH_AND_HOLD = 7,
    TOUCH_OP_PINCH = 8,
    TOUCH_OP_PINCH_IN = 9,
    TOUCH_OP_PINCH_OUT = 10,
    TOUCH_OP_RUB = 11,
    TOUCH_OP_ROTATE = 12,
    TOUCH_OP_CLICK = 13,
    TOUCH_OP_DOUBLE_CLICK = 14,
    TOUCH_OP_TOUCH0_POS_X = 15,
    TOUCH_OP_TOUCH0_POS_Y = 16,
    TOUCH_OP_TOUCH1_POS_X = 17,
    TOUCH_OP_TOUCH1_POS_Y = 18,
    TOUCH_OP_CLEAR = 19
};
