enum traceModelErrorCode_t : int
{
    TRM_ERROR_OK = 0,
    TRM_ERROR_MODEL_NOT_FOUND = 1,
    TRM_ERROR_MAX_VERTS = 2,
    TRM_ERROR_MIN_VERTS = 3,
    TRM_ERROR_MAX_EDGES = 4,
    TRM_ERROR_MAX_POLYS = 5,
    TRM_ERROR_MAX_POLYEDGES = 6,
    TRM_ERROR_OPEN = 7,
    TRM_ERROR_TOO_COMPLEX = 8,
    TRM_ERROR_TOO_DETAILED = 9,
    TRM_ERROR_CONCAVE = 10
};
