enum typeInfoGraphNodeShapeType_t : int
{
    TYPEINFOGRAPHNODESHAPE_RECTANGLE = 0,
    TYPEINFOGRAPHNODESHAPE_HEXAGON = 1,
    TYPEINFOGRAPHNODESHAPE_DIAMOND = 2,
    TYPEINFOGRAPHNODESHAPE_ELLIPSE = 3
};
