enum typeInfoGraphLinkRenderShape_t : int
{
    GRAPHLINK_RENDER_NORMAL = 0,
    GRAPHLINK_RENDER_GROUND = 1,
    GRAPHLINK_RENDER_CIRCLE = 2,
    GRAPHLINK_RENDER_ARROW = 3,
    GRAPHLINK_RENDER_BOX = 4,
    GRAPHLINK_RENDER_DIAMOND = 5,
    GRAPHLINK_RENDER_HEXAGON = 6
};
