enum typeInfoGraphLinkTypes_t : int
{
    TYPEINFOGRAPHLINK_DEFAULT = 0,
    TYPEINFOGRAPHLINK_BEHAVIOR_TREE = 1,
    TYPEINFOGRAPHLINK_AI_FSM_GRAPH_TRANSITION = 2,
    TYPEINFOGRAPHLINK_TEST = 3,
    TYPEINFOGRAPHLINK_TEST2 = 4,
    TYPEINFOGRAPHLINK_NARRATIVE = 5,
    TYPEINFOGRAPHLINK_INTERACTION = 6,
    TYPEINFOGRAPHLINK_GORE = 7,
    TYPEINFOGRAPHLINK_ATTACK = 8,
    TYPEINFOGRAPHLINK_FACTION = 9,
    TYPEINFOGRAPHLINK_FK = 10,
    TYPEINFOGRAPHLINK_AIPAIN = 11,
    TYPEINFOGRAPHLINK_AIMOVEMENT = 12,
    TYPEINFOGRAPHLINK_AI_DAMAGE_STATE = 13,
    TYPEINFOGRAPHLINK_AI_ANIM_STATE = 14,
    TYPEINFOGRAPHLINK_ENTITY_DAMAGE = 15,
    TYPEINFOGRAPHLINK_AI_DECISIONTREE = 16,
    TYPEINFOGRAPHLINK_AI_MASTERGRAPH = 17
};
