enum typeInfoGraphTypes_t : int
{
    TYPEINFOGRAPH_DEFAULT = 0,
    TYPEINFOGRAPH_AI_FSM = 1,
    TYPEINFOGRAPH_BOT_BEHAVIOR_TREE = 2,
    TYPEINFOGRAPH_TEST = 3,
    TYPEINFOGRAPH_SINGLETYPE_TEST = 4,
    TYPEINFOGRAPH_NARRATIVE = 5,
    TYPEINFOGRAPH_INTERACTION = 6,
    TYPEINFOGRAPH_GORE = 7,
    TYPEINFOGRAPH_ATTACK = 8,
    TYPEINFOGRAPH_FACTION = 9,
    TYPEINFOGRAPH_VIGNETTE = 10,
    TYPEINFOGRAPH_FK = 11,
    TYPEINFOGRAPH_AIPAIN = 12,
    TYPEINFOGRAPH_AIMOVEMENT = 13,
    TYPEINFOGRAPH_AI_DAMAGE_STATE = 14,
    TYPEINFOGRAPH_AI_ANIM_STATE = 15,
    TYPEINFOGRAPH_ENTITY_DAMAGE = 16,
    TYPEINFOGRAPH_AI_DECISIONTREE = 17,
    TYPEINFOGRAPH_AI_MASTERGRAPH = 18
};
