enum typeInfoGraphNodeTypes_t : int
{
    TYPEINFO_GRAPHNODE_DEFAULT = 0,
    TYPEINFO_GRAPHNODE_BEHAVIOR_TREE = 1,
    TYPEINFO_GRAPHNODE_AIFSM = 2,
    TYPEINFO_GRAPHNODE_TEST = 3,
    TYPEINFO_GRAPHNODE_TEST2 = 4,
    TYPEINFO_GRAPHNODE_NARRATIVE = 5,
    TYPEINFO_GRAPHNODE_INTERACTION = 6,
    TYPEINFO_GRAPHNODE_GORE = 7,
    TYPEINFO_GRAPHNODE_ATTACK = 8,
    TYPEINFO_GRAPHNODE_FACTION = 9,
    TYPEINFO_GRAPHNODE_FK = 10,
    TYPEINFO_GRAPHNODE_AIPAIN = 11,
    TYPEINFO_GRAPHNODE_AIMOVEMENT = 12,
    TYPEINFO_GRAPHNODE_AI_DAMAGE_STATE = 13,
    TYPEINFO_GRAPHNODE_AI_ANIM_STATE = 14,
    TYPEINFO_GRAPHNODE_ENTITY_DAMAGE = 15,
    TYPEINFO_GRAPHNODE_AI_DECISIONTREE = 16,
    TYPEINFO_GRAPHNODE_AI_MASTERGRAPH = 17
};
