enum typeInfoSubGraphTypes_t : int
{
    TYPEINFO_SUBGRAPH_DEFAULT = 0,
    TYPEINFO_SUBGRAPH_AIFSMMANAGER = 1,
    TYPEINFO_SUBGRAPH_BEHAVIOR_TREE = 2,
    TYPEINFO_SUBGRAPH_TEST = 3,
    TYPEINFO_SUBGRAPH_TEST2 = 4,
    TYPEINFO_SUBGRAPH_NARRATIVE = 5,
    TYPEINFO_SUBGRAPH_GORE = 6,
    TYPEINFO_SUBGRAPH_ATTACK = 7,
    TYPEINFO_SUBGRAPH_FACTION = 8,
    TYPEINFO_SUBGRAPH_FK = 9,
    TYPEINFO_SUBGRAPH_AIPAIN = 10,
    TYPEINFO_SUBGRAPH_AIMOVEMENT = 11,
    TYPEINFO_SUBGRAPH_AI_DAMAGE_STATE = 12,
    TYPEINFO_SUBGRAPH_AI_ANIM_STATE = 13,
    TYPEINFO_SUBGRAPH_ENTITY_DAMAGE = 14,
    TYPEINFO_SUBGRAPH_AI_DECISIONTREE = 15,
    TYPEINFO_SUBGRAPH_AI_MASTERGRAPH = 16
};
