enum umbraObjectType_t : int
{
    UMBRA_OBJECT_TYPE_GATE = 0,
    UMBRA_OBJECT_TYPE_LIGHT = 1,
    UMBRA_OBJECT_TYPE_DECAL = 2,
    UMBRA_OBJECT_TYPE_STATICINSTANCE = 3,
    UMBRA_OBJECT_TYPE_BRUSHGEOMETRY = 4,
    UMBRA_OBJECT_TYPE_WORLDAREA = 5,
    UMBRA_OBJECT_TYPE_MAX = 6
};
