enum unlockableDescriptionFlags_t : int
{
    UNLOCKABLE_FLAG_NONE = 0,
    UNLOCKABLE_FLAG_GENERIC = 1,
    UNLOCKABLE_FLAG_MISSION_CHALLENGE = 2,
    UNLOCKABLE_FLAG_QUEST = 4,
    UNLOCKABLE_FLAG_WEAPON_MASTERY = 8,
    UNLOCKABLE_FLAG_PODIUM_CHALLENGE = 16,
    UNLOCKABLE_FLAG_RUNE_TRIAL = 32,
    UNLOCKABLE_FLAG_SUIT_CATEGORY = 64,
    UNLOCKABLE_FLAG_SEASON = 128,
    UNLOCKABLE_FLAG_DLC1_MISSION_CHALLENGE = 256,
    UNLOCKABLE_FLAG_HORDE_CHALLENGE = 512,
    UNLOCKABLE_FLAG_SKIP_LOAD = 806
};
