enum upgradeModOperator_t : int
{
    MOD_OPERATOR_NONE = -1,
    MOD_OPERATOR_TOGGLE_BOOL = 0,
    MOD_OPERATOR_ADD = 1,
    MOD_OPERATOR_SUBTRACT = 2,
    MOD_OPERATOR_MULTIPLY = 3,
    MOD_OPERATOR_SET = 4,
    MOD_OPERATOR_BASE_PCT = 5,
    MOD_OPERATOR_ABSOLUTE_PCT = 6,
    MOD_OPERATOR_ADD_PCT = 7,
    MOD_OPERATOR_TOTAL = 8
};
