enum viewFilterFailReason_t : int
{
    VIEWFILTERFAIL_DISTANCE = 0,
    VIEWFILTERFAIL_INVALIDSTATE = 1,
    VIEWFILTERFAIL_LINEOFSIGHT = 2,
    VIEWFILTERFAIL_INVALIDTYPE = 3,
    VIEWFILTERFAIL_NUMERRORS = 4
};
