enum violenceEvents_t : int
{
    EVENT_INVALID = -1,
    EVENT_BARREL_KILL = 0,
    EVENT_HEADSHOT = 1,
    EVENT_GLORY_KILL = 2,
    EVENT_POWER_STRIKE = 3,
    EVENT_CRUCIBLE_ACTIVATED = 4,
    EVENT_CRUCIBLE_DEACTIVATED = 5,
    EVENT_DEATH_FROM_ABOVE = 6,
    EVENT_DIRECT_HIT = 7,
    EVENT_KILL_STUNNED_ENEMY = 8,
    EVENT_KILL_MIDAIR_ENEMY = 9,
    EVENT_MULTI_KILL = 10,
    EVENT_MULTI_KILL_2 = 11
};
