enum voiceEvent_t : int
{
    VOICEEVENT_VISEME_SIMPLE = 0,
    VOICEEVENT_VISEME_FRAME = 1,
    VOICEEVENT_GAMEEVENT = 2,
    VOICEEVENT_TEXT = 3,
    VOICEEVENT_PUNCTUATION = 4,
    VOICEEVENT_ANIM = 5,
    VOICEEVENT_MOOD = 6,
    VOICEEVENT_MAX = 7
};
