enum voiceMessageType_t : int
{
    VOICEMSG_SIGHTED_ENEMY = 0,
    VOICEMSG_HEARD_SOMETHING = 1,
    VOICEMSG_SAW_SOMETHING = 2,
    VOICEMSG_TOOK_DAMAGE = 3,
    VOICEMSG_GOT_KILLED = 4,
    VOICEMSG_FOUND_DEAD_BODY = 5,
    VOICEMSG_MEMBER_KILLED = 6,
    VOICEMSG_MAX = 7
};
