enum vrControllerDeviceType_t : int
{
    VR_CONTROLLER_DEVICE_TYPE_VIVE = 0,
    VR_CONTROLLER_DEVICE_TYPE_WMR = 1,
    VR_CONTROLLER_DEVICE_TYPE_STEAMVR_GENERIC = 2,
    VR_CONTROLLER_DEVICE_TYPE_PLAYSTATION_MOVE = 3,
    VR_CONTROLLER_DEVICE_TYPE_PLAYSTATION_AIM = 4,
    VR_CONTROLLER_DEVICE_TYPE_UNKNOWN = 5,
    VR_CONTROLLER_DEVICE_TYPE_COUNT = 6
};
