enum vrInputAxis_t : int
{
    VR_INPUT_AXIS_TOUCHPAD = 0,
    VR_INPUT_AXIS_TRIGGER_0 = 1,
    VR_INPUT_AXIS_TRIGGER_1 = 2,
    VR_INPUT_AXIS_THUMBSTICK_0 = 3,
    VR_INPUT_AXIS_THUMBSTICK_1 = 4,
    VR_INPUT_AXIS_COUNT = 5
};
