enum vrTrackedDeviceType_t : int
{
    VR_TRACKED_DEVICE_TYPE_HMD = 0,
    VR_TRACKED_DEVICE_TYPE_CONTROLLER = 1,
    VR_TRACKED_DEVICE_TYPE_GENERIC_TRACKER = 2,
    VR_TRACKED_DEVICE_TYPE_TRACKING_REFERENCE = 3,
    VR_TRACKED_DEVICE_TYPE_COUNT = 4
};
