enum warningCategory_t : int
{
    WARNINGCATEGORY_unskippable = 0,
    WARNINGCATEGORY_general = 1,
    WARNINGCATEGORY_clip = 2,
    WARNINGCATEGORY_ai = 3,
    WARNINGCATEGORY_inventory = 4,
    WARNINGCATEGORY_ui = 5,
    WARNINGCATEGORY_anim = 6,
    WARNINGCATEGORY_render = 7,
    WARNINGCATEGORY_resource = 8,
    WARNINGCATEGORY_jailed = 9,
    WARNINGCATEGORY_skippable = 10,
    WARNINGCATEGORY_weapon = 11,
    WARNINGCATEGORY_script = 12,
    WARNINGCATEGORY_sound = 13,
    WARNINGCATEGORY_syncmelee = 14,
    WARNINGCATEGORY_fx = 15,
    WARNINGCATEGORY_game = 16,
    WARNINGCATEGORY_backend = 17,
    WARNINGCATEGORY_physics = 18,
    WARNINGCATEGORY_player = 19,
    WARNINGCATEGORY_jobs = 20,
    WARNINGCATEGORY_cvar = 21,
    WARNINGCATEGORY_events = 22,
    WARNINGCATEGORY_typeinfo = 23,
    WARNINGCATEGORY_gore = 24,
    WARNINGCATEGORY_umbra = 25,
    WARNINGCATEGORY_logic = 26
};
