enum weaponTriggerMode_t : int
{
    WEAPONTRIGGERMODE_NONE = 0,
    WEAPONTRIGGERMODE_PRIMARY_PRESS = 1,
    WEAPONTRIGGERMODE_PRIMARY_RELEASE = 2,
    WEAPONTRIGGERMODE_SECONDARY_PRESS = 3,
    WEAPONTRIGGERMODE_SECONDARY_TAP = 4,
    WEAPONTRIGGERMODE_SECONDARY_PRESS_DOES_NOT_INTERRUPT_PRIMARY = 5,
    WEAPONTRIGGERMODE_SECONDARY_PRESS_INTERRUPTS_PRIMARY = 6,
    WEAPONTRIGGERMODE_SECONDARY_HOLD_PRIMARY_PRESS = 7,
    WEAPONTRIGGERMODE_SECONDARY_HOLD_PRIMARY_RELEASE = 8,
    WEAPONTRIGGERMODE_SECONDARY_HOLD_PRIMARY_NONE = 9,
    WEAPONTRIGGERMODE_SECONDARY_RELEASE = 10,
    WEAPONTRIGGERMODE_SECONDARY_RELEASE_PRIMARY_NONE = 11,
    WEAPONTRIGGERMODE_SECONDARY_TOGGLE = 12,
    WEAPONTRIGGERMODE_PRIMARY_PRESS_OR_SECONDARY_PRESS = 13
};
