enum weaponGuiDisplay_t : int
{
    WEAPON_GUIDISPLAY_NONE = -1,
    WEAPON_GUIDISPLAY_ARSHOTS = 0,
    WEAPON_GUIDISPLAY_REPEATER = 1,
    WEAPON_GUIDISPLAY_PLASMA = 2,
    WEAPON_GUIDISPLAY_PLASMA_MOD = 3,
    WEAPON_GUIDISPLAY_ROCKET = 4,
    WEAPON_GUIDISPLAY_MP_ROCKET = 5,
    WEAPON_GUIDISPLAY_GAUSS_AMMO = 6
};
