enum weaponSpecificGoreType_t : int
{
    WSGT_INVALID = 0,
    WSGT_TYPE_LINE = 1,
    WSGT_TYPE_GOTO_THRU_SQUARE = 2,
    WSGT_TYPE_CRUM_THRU_SQUARE = 3,
    WSGT_TYPE_ANGEL_WINGS = 4,
    WSGT_TYPE_CONE = 5,
    WSGT_TYPE_SPHERE = 6,
    WSGT_TYPE_ORANGE_SLICE = 7,
    WSGT_MAX = 8
};
