enum whipState_t : int
{
    WHIP_STATE_IDLE = 0,
    WHIP_STATE_GENERIC_ACTION = 1,
    WHIP_STATE_DIRECTSTRIKE = 2,
    WHIP_STATE_TRAVERSAL = 3,
    WHIP_STATE_LEAP = 4,
    WHIP_STATE_CLEAROUT = 5,
    WHIP_STATE_LASH = 6,
    WHIP_STATE_ATTACHED_TO_WORLD = 7,
    WHIP_STATE_RETRACTING = 8,
    WHIP_STATE_MAX = 9
};
