enum widgetSettingType_t : int
{
    WIDGET_SETTING_TYPE_INVALID = -1,
    WIDGET_SETTING_TYPE_BUTTON = 0,
    WIDGET_SETTING_TYPE_SLIDER = 1,
    WIDGET_SETTING_TYPE_TOGGLE = 2,
    WIDGET_SETTING_TYPE_DROP_DOWN_LIST = 3,
    WIDGET_SETTING_TYPE_HORIZONTAL_LIST = 4,
    NUM_WIDGET_SETTING_TYPES = 5
};
