enum worldGeometryVertexStream_t : int
{
    WGVS_POSITION_SHORT = 0,
    WGVS_POSITION = 1,
    WGVS_NORMAL_TANGENT = 2,
    WGVS_LIGHTMAP_UV_SHORT = 3,
    WGVS_LIGHTMAP_UV = 4,
    WGVS_MATERIAL_UV_SHORT = 5,
    WGVS_MATERIAL_UV = 6,
    WGVS_COLOR = 7,
    WGVS_MATERIALS = 8,
    WGVS_NUM = 9
};
