typedef unsigned char byte;
typedef char int8;
typedef unsigned char uint8;
typedef short int16;
typedef unsigned short uint16;
typedef int int32;
typedef unsigned int uint32;
typedef float float32;
typedef long long int64;
typedef unsigned long long uint64;
typedef double float64;
typedef unsigned short triIndex_t;
typedef unsigned int triIndexLong_t;
typedef _processorInfo_t processorInfo_t;
typedef unsigned int (*xthread_t)(void *);
typedef idTypesafeNumber < float , RadiansUnique_t > radians_t;
typedef idTypesafeNumber < float , DegreesUnique_t > degrees_t;
typedef idTypestrictNumber < int , typestrictScalarUnique > scalarI32_t;
typedef idTypestrictNumber < unsigned int , typestrictScalarUnique > scalarU32_t;
typedef idTypestrictNumber < long long , typestrictScalarUnique > scalarI64_t;
typedef idTypestrictNumber < unsigned long long , typestrictScalarUnique > scalarU64_t;
typedef idTypestrictNumber < float , typestrictScalarUnique > scalarF32_t;
typedef idTypestrictNumber < double , typestrictScalarUnique > scalarF64_t;
typedef idCompileTimeRatio < 1 , 1000000000 > nanosecondsPeriod_t;
typedef idCompileTimeRatio < 1 , 1000000 > microsecondsPeriod_t;
typedef idCompileTimeRatio < 1 , 1000 > millisecondsPeriod_t;
typedef idCompileTimeRatio < 1 > secondsPeriod_t;
typedef idCompileTimeRatio < 60 > minutesPeriod_t;
typedef idCompileTimeRatio < 3600 > hoursPeriod_t;
typedef idCompileTimeRatio < 86400 > daysPeriod_t;
typedef idCompileTimeRatio < 604800 > weeksPeriod_t;
typedef idTypestrictTimeSpan < long long , idCompileTimeRatio < 1 , 1000000 > > microsecondsI64_t;
typedef idTypestrictTimeSpan < unsigned long long , idCompileTimeRatio < 1 , 1000000 > > microsecondsU64_t;
typedef idTypestrictTimeSpan < int , idCompileTimeRatio < 1 , 1000000 > > microsecondsI32_t;
typedef idTypestrictTimeSpan < unsigned int , idCompileTimeRatio < 1 , 1000000 > > microsecondsU32_t;
typedef idTypestrictTimeSpan < short , idCompileTimeRatio < 1 , 1000000 > > microsecondsI16_t;
typedef idTypestrictTimeSpan < unsigned short , idCompileTimeRatio < 1 , 1000000 > > microsecondsU16_t;
typedef idTypestrictTimeSpan < double , idCompileTimeRatio < 1 , 1000000 > > microsecondsF64_t;
typedef idTypestrictTimeSpan < float , idCompileTimeRatio < 1 , 1000000 > > microsecondsF32_t;
typedef idTypestrictTimeSpan < long long , idCompileTimeRatio < 1 , 1000 > > millisecondsI64_t;
typedef idTypestrictTimeSpan < unsigned long long , idCompileTimeRatio < 1 , 1000 > > millisecondsU64_t;
typedef idTypestrictTimeSpan < int , idCompileTimeRatio < 1 , 1000 > > millisecondsI32_t;
typedef idTypestrictTimeSpan < unsigned int , idCompileTimeRatio < 1 , 1000 > > millisecondsU32_t;
typedef idTypestrictTimeSpan < short , idCompileTimeRatio < 1 , 1000 > > millisecondsI16_t;
typedef idTypestrictTimeSpan < unsigned short , idCompileTimeRatio < 1 , 1000 > > millisecondsU16_t;
typedef idTypestrictTimeSpan < double , idCompileTimeRatio < 1 , 1000 > > millisecondsF64_t;
typedef idTypestrictTimeSpan < float , idCompileTimeRatio < 1 , 1000 > > millisecondsF32_t;
typedef idTypestrictTimeSpan < long long , idCompileTimeRatio < 1 > > secondsI64_t;
typedef idTypestrictTimeSpan < unsigned long long , idCompileTimeRatio < 1 > > secondsU64_t;
typedef idTypestrictTimeSpan < int , idCompileTimeRatio < 1 > > secondsI32_t;
typedef idTypestrictTimeSpan < unsigned int , idCompileTimeRatio < 1 > > secondsU32_t;
typedef idTypestrictTimeSpan < short , idCompileTimeRatio < 1 > > secondsI16_t;
typedef idTypestrictTimeSpan < unsigned short , idCompileTimeRatio < 1 > > secondsU16_t;
typedef idTypestrictTimeSpan < double , idCompileTimeRatio < 1 > > secondsF64_t;
typedef idTypestrictTimeSpan < float , idCompileTimeRatio < 1 > > secondsF32_t;
typedef idTypestrictTimeSpan < long long , idCompileTimeRatio < 60 > > minutesI64_t;
typedef idTypestrictTimeSpan < unsigned long long , idCompileTimeRatio < 60 > > minutesU64_t;
typedef idTypestrictTimeSpan < int , idCompileTimeRatio < 60 > > minutesI32_t;
typedef idTypestrictTimeSpan < unsigned int , idCompileTimeRatio < 60 > > minutesU32_t;
typedef idTypestrictTimeSpan < short , idCompileTimeRatio < 60 > > minutesI16_t;
typedef idTypestrictTimeSpan < unsigned short , idCompileTimeRatio < 60 > > minutesU16_t;
typedef idTypestrictTimeSpan < double , idCompileTimeRatio < 60 > > minutesF64_t;
typedef idTypestrictTimeSpan < float , idCompileTimeRatio < 60 > > minutesF32_t;
typedef idTypestrictTimeSpan < long long , idCompileTimeRatio < 3600 > > hoursI64_t;
typedef idTypestrictTimeSpan < unsigned long long , idCompileTimeRatio < 3600 > > hoursU64_t;
typedef idTypestrictTimeSpan < int , idCompileTimeRatio < 3600 > > hoursI32_t;
typedef idTypestrictTimeSpan < unsigned int , idCompileTimeRatio < 3600 > > hoursU32_t;
typedef idTypestrictTimeSpan < short , idCompileTimeRatio < 3600 > > hoursI16_t;
typedef idTypestrictTimeSpan < unsigned short , idCompileTimeRatio < 3600 > > hoursU16_t;
typedef idTypestrictTimeSpan < double , idCompileTimeRatio < 3600 > > hoursF64_t;
typedef idTypestrictTimeSpan < float , idCompileTimeRatio < 3600 > > hoursF32_t;
typedef idTypestrictTimeSpan < long long , idCompileTimeRatio < 86400 > > daysI64_t;
typedef idTypestrictTimeSpan < unsigned long long , idCompileTimeRatio < 86400 > > daysU64_t;
typedef idTypestrictTimeSpan < int , idCompileTimeRatio < 86400 > > daysI32_t;
typedef idTypestrictTimeSpan < unsigned int , idCompileTimeRatio < 86400 > > daysU32_t;
typedef idTypestrictTimeSpan < short , idCompileTimeRatio < 86400 > > daysI16_t;
typedef idTypestrictTimeSpan < unsigned short , idCompileTimeRatio < 86400 > > daysU16_t;
typedef idTypestrictTimeSpan < double , idCompileTimeRatio < 86400 > > daysF64_t;
typedef idTypestrictTimeSpan < float , idCompileTimeRatio < 86400 > > daysF32_t;
typedef idTypestrictTimeSpan < long long , idCompileTimeRatio < 604800 > > weeksI64_t;
typedef idTypestrictTimeSpan < unsigned long long , idCompileTimeRatio < 604800 > > weeksU64_t;
typedef idTypestrictTimeSpan < int , idCompileTimeRatio < 604800 > > weeksI32_t;
typedef idTypestrictTimeSpan < unsigned int , idCompileTimeRatio < 604800 > > weeksU32_t;
typedef idTypestrictTimeSpan < short , idCompileTimeRatio < 604800 > > weeksI16_t;
typedef idTypestrictTimeSpan < unsigned short , idCompileTimeRatio < 604800 > > weeksU16_t;
typedef idTypestrictTimeSpan < double , idCompileTimeRatio < 604800 > > weeksF64_t;
typedef idTypestrictTimeSpan < float , idCompileTimeRatio < 604800 > > weeksF32_t;
typedef idTypestrictTimePoint < typestrictWallClockTimestampUnique > wallClockTimestamp_t;
typedef idTypestrictTimePoint < typestrictMonotonicTimestampUnique > monotonicTimestamp_t;
typedef idTypestrictTimePoint < typestrictProcessTimestampUnique > processTimestamp_t;
typedef unsigned long long unixTimestamp_t;
typedef IntegralConstant < bool , true > TrueType;
typedef IntegralConstant < bool , false > FalseType;
typedef idPair < idStr , idStr > idStrPair;
typedef idTypesafeTime < long long , gameTimeUnique_t , 999960 > gameTime_t;
typedef idTypesafeTime < long long , serverGameTimeUnique_t , 999960 > serverGameTime_t;
typedef idTypesafeTime < long long , localGameTimeUnique_t , 999960 > localGameTime_t;
typedef idTypesafeTime < int , millisecondUnique_t , 1000 > milliseconds_t;
typedef idTypesafeTime < long long , microsecondUnique_t , 1000000 > microseconds_t;
typedef idTypesafeTime < float , secondUnique_t , 1 > seconds_t;
typedef idSpring < idVec1 > idSpring1;
typedef idSpring < idVec2 > idSpring2;
typedef idSpring < idVec3 > idSpring3;
typedef void (*fourierTransform_t)(const idComplex * data_in , const int32 num , idComplex * data_out);
typedef bool (*extendedCollisionTestCallback_t)(const int index , const idBounds & bounds , void * const userParam);
typedef idList < idAtomicString > idAtomicStrList;
typedef void (*libErrorHandler_t)(const char * msg);
typedef idList < idStr > idStrList;
typedef idPair < unsigned long long , unsigned long long > uint128;
typedef unsigned short trmVertIndex_t;
typedef unsigned char trmEdgeIndex_t;
typedef unsigned int ID_COLORREF;
typedef unsigned int stringID_t;
typedef void (*remoOnConnectCallback_t)(idRemoteMonitor * const remo , void * const param);
typedef unsigned long long profileCategory_t;
typedef int (*getFunc_t)(void * ptr);
typedef void (*setFunc_t)(void * ptr , int value);
typedef idClass* (*createInstanceFunc)();
typedef idRenderModel* (*createRenderModelFunc)(const class idDeclModelAsset * modelAsset , const uint32 createFlags);
typedef idScopedMutex idScopedCriticalSection;
typedef void (*cmdFunction_t)(const idCmdArgs & args);
typedef void (*argCompletion_t)(idAutoComplete & autoComplete);
typedef commandDef_s commandDef_t;
typedef idFile* (*filePreCallback_t)(const char * fileName);
typedef idFile* (*filePatchCallback_t)(const char * fileName);
typedef void (*filePostCallback_t)(const char * fileName , idFile * file);
typedef void (*fileVerifyFailedCallback_t)(const char * fileName , fileVerifyFailedReason_t reason);
typedef long long seek_t;
typedef void (idClass::*classSpawnFunc_t)();
typedef idSpawnId spawnId_t;
typedef idMidnightObjectUID < idMidnightSceneUIDType , idMidnight::EMUI_SCENE_MAX > idMidnightSceneUID;
typedef idMidnightObjectUID < idMidnightGroupUIDType , idMidnight::EMUI_GROUP_MAX > idMidnightGroupUID;
typedef idMidnightObjectUID < idMidnightTrackUIDType , idMidnight::EMUI_TRACK_MAX > idMidnightTrackUID;
typedef idMidnightObjectUID < idMidnightKeyUIDType , idMidnight::EMUI_KEY_MAX > idMidnightKeyUID;
typedef idMidnightObjectUID < idMidnightNodeUIDType , idMidnight::EMUI32_NODE_MAX > idMidnightNodeUID;
typedef idMidnightObjectUID < idMidnightPointUIDType , idMidnight::EMUI32_POINT_MAX > idMidnightPointUID;
typedef idMidnightObjectUID < idMidnightEntryUIDType , 1 > idMidnightEntryUID;
typedef idMidnightObjectUID < idMidnightOutUIDType , idMidnight::EMUI32_OUT_MAX > idMidnightOutUID;
typedef unsigned short aliasHandleType_t;
typedef unsigned short aliasHandleHandsFirstPersonType_t;
typedef unsigned short aliasHandleHandsThirdPersonType_t;
typedef unsigned short aliasHandleLegsType_t;
typedef unsigned short aliasHandleBodyType_t;
typedef unsigned short jointHandleType_t;
typedef unsigned short userChannelHandleType_t;
typedef unsigned short modelHandleType_t;
typedef short jointIndexType_t;
typedef unsigned char jointIndexRemapType_t;
typedef short userChannelIndexType_t;
typedef unsigned short crcType_t;
typedef idHandle < unsigned short , invalidAliasHandle_t , INVALID_ALIAS_HANDLE > aliasHandle_t;
typedef idHandle < unsigned short , invalidJointHandle_t , INVALID_JOINT_HANDLE > jointHandle_t;
typedef idHandle < unsigned short , invalidUserChannelHandle_t , INVALID_USER_CHANNEL_HANDLE > userChannelHandle_t;
typedef idIndex < short , invalidJointIndex_t , - 1 > jointIndex_t;
typedef idIndex < short , invalidUserChannelIndex_t > userChannelIndex_t;
typedef idHandle < unsigned short , invalidCrc_t , INVALID_CRC > crc_t;
typedef idStaticList < const idCachedJoint * , MAX_CACHED_JOINTS > cachedJointList_t;
typedef idHandle < unsigned int , invalidAnimEventId_t , INVALID_ANIMEVENT_ID > animEventId_t;
typedef unsigned long long (*resourceDependencyCallback_t)(const idResource * const resource , const uint32 payloadLength , const byte * const payload);
typedef unsigned long long resourceID_t;
typedef bool (*resourceGeneratorCallback_t)(const char * const resourceName , idFile * const file , resourceStorageGenerator_t * const generator , idStr & errorMsg);
typedef void (*resourceGeneratedNameCallback_t)(const char * const resourceName , const char * const resourceTypeName , const char * const binaryExtension , idStr & generatedName);
typedef bool (*resourceIsProgrammaticallyDefinedCallback_t)(const char * const resourceName);
typedef void (*resourceBuildGameVariationsCallback_t)(idList < idResourceVariation > & var , const resourceBuildSpec_t & buildSpec);
typedef idResource* (*resourceGetResourceByIDCallback_t)(void * const param , const resourceID_t id);
typedef idResource* (*resourceAllocCallback_t)(const char * const name);
typedef int (*resourceAllocSizeCallback_t)();
typedef void (*resourcePlacementNewCallback_t)(void * const dest);
typedef void (*resourceStaleCallback_t)(const char * const reason , const resourceDepot_t depot , const char * const resourceTypeName , const char * const resourceName , const idResourceVariation variation);
typedef void (*resourceConnectResourceTrackingCallback_t)(idResource * const resource , const char * const filename);
typedef void (*resourceDisconnectResourceTrackingCallback_t)(idResource * const resource);
typedef void (*resourceLoadCallback_t)(void * const param , const idResource * const resource , resourceLoadCallbackKind_t kind);
typedef unsigned short eyeInfoHandleType;
typedef idHandle < unsigned short , invalidEyeInfo_t , INVALID_EYE_GROUP > eyeInfoHandle_t;
typedef unsigned int worldGeometryAllocHdl_t;
typedef unsigned int permutationFlag_t;
typedef uintptr_t bufferDeviceAddress_t;
typedef unsigned char mergedPipelineIndex_t;
typedef int geomCacheUploadHdl_t;
typedef unsigned char directionalLightmapFmt_t;
typedef idArray < idTriangles * , MAX_GEOMETRY_LOD_LEVELS > geometryLods_t;
typedef idArray < const idTriangles * , MAX_GEOMETRY_LOD_LEVELS > constGeometryLods_t;
typedef void* descriptorSetDeviceHdl_t;
typedef idAtomicHandleT < aliasRefType_t > aliasRef_t;
typedef idPair < idStr , idList < int , TAG_MD6 > > idMeshKit;
typedef idList < const idDeclTable * , TAG_PARTICLE > idParticleTableList;
typedef idRandom idRandomType;
typedef idGraphItemFactory < idTypeInfoSubGraph > idSubGraphFactory;
typedef idGraphItemFactory < idTypeInfoGraphNode > idGraphNodeFactory;
typedef idGraphItemFactory < idTypeInfoGraphLink > idGraphLinkFactory;
typedef idBitset < 256 > meshVisibilityMask_t;
typedef unsigned char geomCacheQuantizedGeomCacheProjIndex_t;
typedef unsigned int geomCacheQuantizedGeomCacheProjToTriIndex_t;
typedef unsigned int streamIoRequestPriority_t;
typedef void (*streamIoEventCb_t)(const streamIoEvent_t * evs , int num);
typedef void (*streamDecodeSourceBlockDoneCb_t)(void * , const void * sourceBlock);
typedef idGrowableList < geomCacheReadBlock_t , 2 > geomCacheReadBlockList_t;
typedef idList < umbraObjectHashIdPair_t , TAG_UMBRA > umbraObjectHashIdPairList_t;
typedef bool (*execProcessWorkFunction_t)();
typedef void (*execOutputFunction_t)(const char * text);
typedef uint16 broadcastSystemId_t;
typedef idStaticList < idFile_SaveGame * , MAX_SAVE_FILES > idGameSaveFiles;
typedef unsigned short objectSize_t;
typedef uint16 peerMask_t;
typedef idTypesafeNumber < float , RadiusUnique_t > radius_t;
typedef idTypesafeNumber < float , SphereUnique_t > sphere_t;
typedef unsigned short (*GetProfileTagCallback_t)(void *);
typedef unsigned char (*GetVersionMajorCallback_t)(void *);
typedef unsigned char (*GetVersionMinorCallback_t)(void *);
typedef void (*InternalSetDefaultCallback_t)(void *);
typedef void (*InternalPrepareForNewUserCallback_t)(void *);
typedef bool (*InternalSerializeCallback_t)(idJsonSerializer & , int8 , void *);
typedef int idPositionRetargetingFlags_t;
typedef idHandle < int , invalidAttachment_t , INVALID_ATTACHMENT > attachmentHandle_t;
typedef unsigned short logicIndex_t;
typedef unsigned int logicId_t;
typedef idTypeInfoObjectPtr < idLogicVariableModel > idLogicVariableModelPtr;
typedef idTypeInfoObjectPtr < idLogicNodeModel > idLogicNodeModelPtr;
typedef void (*logicTypeCreateFunction_t)(void * placement , const void * value);
typedef void (*logicTypeDestroyFunction_t)(void * pointer);
typedef void (*logicTypeCopyFunction_t)(void * lhs , const void * rhs);
typedef void (*logicTypeSerializeFunction_t)(idJsonSerializer & jsonSer , const char * key , void * pointer);
typedef void (*logicTypeToStringFunction_t)(idStr & output , const void * pointer);
typedef idLogicVariableModel* (*logicCreateVariableModelDefaultFunction_t)();
typedef int (*logicListLengthFunction_t)(const void * pointer);
typedef void (*logicListAddFunction_t)(void * pointer , const void * element);
typedef void (*logicListAppendFunction_t)(void * lhs , const void * rhs);
typedef bool (*logicListRemoveByIndexFunction_t)(void * pointer , int index , void * value);
typedef bool (*logicListRemoveByValueFunction_t)(void * pointer , const void * value);
typedef bool (*logicListGetFunction_t)(const void * pointer , int index , void * value);
typedef bool (*logicListSetFunction_t)(void * pointer , int index , const void * value);
typedef void (*logicListClearFunction_t)(void * pointer);
typedef void (*logicTypeConversionFunction_t)(const void * input , void * output);
typedef idTypeInfoObjectPtr < idLogicGUIItem > idLogicGUIItemPtr;
typedef int viseme_t;
typedef int phoneme_t;
typedef unsigned short matchFlagsMask_t;
typedef unsigned short idSoundVolumeID;
typedef idStaticList < idStrStatic < 128 > , 512 > idLayerList;
typedef int physicsId_t;
typedef bool (*resourceStaleCheckCallback_t)(void * const param , const resourceStorage_t * const resourceStorage , const idResourceDependency * const , const idResourceDepPayload * const payload , const idResourceDepCachedData & cachedData , const idResourceEntry * const , idStr & outStaleReason);
typedef void (*resourceStreamFileCallback_t)(void * const param , resourceStorage_t * const resourceStorage);
typedef idList < unsigned long long > resourceContainerEntryMask_t;
typedef idHandle < int , invalidMapPrimitiveHandle_t , INVALID_MAP_PRIMITIVE_HANDLE > mapPrimitiveHandle_t;
typedef bool (*shouldWriteEntity_t)(const idMapFileLocal * mapFile , idMapEntityLocal * mapEnt , idMapInstance * mapInstance);
typedef bool (*shouldWritePrimitive_t)(const idMapPrimitive * mapPrim , idMapInstance * mapInstance);
typedef idIndex < int , invalidReachability_t > reachIndex_t;
typedef idIndex < short , areaIndexUnique_t , INVALID_AREA > areaIndex_t;
typedef idIndex < short , invalidAASAnimIndex_t > aasAnimIndex_t;
typedef idIndex < int , invalidAASTree_t > aasTree_t;
typedef idIndex < short , invalidAASDependencyIndex_t > aasDependencyIndex_t;
typedef idIndex < short , invalidAASInteractionEntIndex_t > aasInteractionEntIndex_t;
typedef idIndex < short , invalidAASTraversalIndex_t , INVALID_AAS_TRAVERSAL_INDEX > traversalIndex_t;
typedef int aas2Index_t;
typedef idPlane aas2Plane_t;
typedef idVec3 aas2Vertex_t;
typedef idHandle < unsigned short , invalidAASUserHandle_t , AAS_USER_HANDLE_INVALID > aasUserHandle_t;
typedef unsigned char aas2ObstaclePVS_t;
typedef int interfaceHandle_t;
typedef unsigned short broadcastEventId_t;
typedef void (*broadcastCallback_t)(broadcastEventId_t evId , void * const param , const void * const eventData);
typedef bool (*getJointTransform_t)(void * model , const idJointMat * frame , const char * jointName , idVec3 & origin , idMat3 & axis);
typedef idHandle < int , traceModelHandleType_t , INVALID_TRACE_MODEL_HANDLE > traceModelHandle_t;
typedef unsigned short cm_polygonEdge_t;
typedef idPlane cm_polytopePlane_t;
typedef unsigned short cm_primitiveIndex_t;
typedef int bodyId_t;
typedef int contactId_t;
typedef idStaticList < idRepulsor , idRepulsor::MAX_REPULSORS > repulsorList_t;
typedef unsigned int physicsGroup_t;
typedef bool (*playerPhysicsCallback_t)(spawnId_t spawnId);
typedef bool (*playerPhysicsCallbackBool_t)(spawnId_t spawnId , bool val , bool val2);
typedef bool (*playerPhysicsCallbackFloat_t)(spawnId_t spawnId , float val);
typedef bool (*playerPhysicsCallbackFull_t)(spawnId_t spawnId , const idVec3 & pos , const idVec3 & forward , const idVec3 & right , const idVec3 & up , const idUserCmd & userCmd);
typedef void (*translatedCallback_t)(spawnId_t spawnId , const idVec3 & translation);
typedef void (*rotatedCallback_t)(spawnId_t spawnId , const idRotation & rotation);
typedef void (*pusherInfoCallback_t)(spawnId_t spawnId , spawnId_t pusherId);
typedef void (*crusherInfoCallback_t)(spawnId_t spawnId , spawnId_t crusherId);
typedef int aasHandle_t;
typedef idList < queuedImpact_t > impactQueueThread_t;
typedef idHandle < unsigned long long , unsigned long long , UINT64_MAX > fxActionGroupHandle_t;
typedef idList < idHandle < unsigned long long , unsigned long long , UINT64_MAX > , TAG_FX > fxActionGroupBatch_t;
typedef int animString_t;
typedef short animWebHandleType_t;
typedef idHandle < short , invalidAnimWebHandle_t , INVALID_ANIM_WEB > animWebHandle_t;
typedef short animWebEventIdType_t;
typedef idHandle < short , invalidAnimWebEventId_t , INVALID_ANIM_WEB_EVENT_ID > animWebEventId_t;
typedef idAnimRecorder* (*idAnimRecorderAlloc_t)();
typedef idAnimator_TurretNxN < 3 > idAnimator_Turret3x3;
typedef idAnimator_TurretNxN < 5 > idAnimator_Turret5x5;
typedef idAnimator_TurretNxN < 3 > idAnimator_Turret;
typedef idManagedClassPtr < idEntity > idManagedEntityPtr;
typedef void (*onScreenChangedCallback_t)(void * const param , const int oldScreen , const int newScreen , const menuTransitionType_t transitionType);
typedef idArray < profileStatValue_t , STAT_MAX > idStatContainer;
typedef idList < UnlockableTable_t > UnlockableList;
typedef idList < idSWFWidget * , TAG_MENU > idSWFWidgetList;
typedef idList < idSWFWidgetAction , TAG_MENU > idSWFWidgetActionList;
typedef void (*observerCallback_t)(void * const param , const idSWFWidget * widget , const idSWFWidgetEvent & event);
typedef bool (*actionCallback_t)(void * const param , idSWFWidgetAction & action , const idSWFWidgetEvent & event , idSWFWidget * targetWidget);
typedef void (*logicWidgetCallback_t)(void * const param , const char * eventName , const void * const eventData);
typedef idList < idMenu_GridData * > idMenu_GridCatalog;
typedef idHandle < int , chatChannelId_type , chatChannelId_type::CCI_INVALID > chatChannelId_t;
typedef idHandle < int , chatLocalTalkerId_type , chatLocalTalkerId_type::CLTI_INVALID > chatLocalTalkerId_t;
typedef idHandle < int , chatTalkerId_type , chatTalkerId_type::CTI_INVALID > chatTalkerId_t;
typedef idHandle < int , socialInviteId_type , socialInviteId_type::SII_INVALID > socialInviteId_t;
typedef idNetEvent < 15 > netBoolEvent_t;
typedef idInstantNetEvent < 15 > instantNetBoolEvent_t;
typedef unsigned char peerTimeoutScale_t;
typedef unsigned long long resourceId_t;
typedef idArray < idPlayerNightmareProgress , 5 > nightmareProgressContainer_t;
typedef idList < const idPlayerNightmareProgress * > nightmareProgressEntryContainer_t;
typedef void (*DeathMarkersCallback)(int errorCode , const idList < idPlayerNightmareProgress > & markers);
typedef idList < idAtomicString > spritePath_t;
typedef idHandle < int , invalidAIEvent_t , INVALID_AIEVENT > aiEventHandle_t;
typedef unsigned long long netRelFrameLastChecked;
typedef idNetRelevance::netRelevanceFlags_t idNetRelevanceFlags;
typedef int idHighlightHandle;
typedef idList < idManagedClassPtr < idEntity > > idEntityPtrList;
typedef idList < idManagedClassPtr < idEntity > > triggerTouchList_t;
typedef idStaticList < idManagedClassPtr < idEntity > , 16 > staticTriggerTouchList_t;
typedef idList < codexEntry_t > codexTree_t;
typedef idList < playableDemonOption_t > demonOptionList_t;
typedef idList < idAtomicString > LoadoutOverrideKeys;
typedef idArray < float , INFLUENCE_MAX > spawnInfluenceScoreArray_t;
typedef idUniquePtr < idAccessControlProvider > idAccessControlProviderPtr;
typedef idSmartTimer < GAMETIME_SCALED > idScaledSmartTimer;
typedef idSmartTimer < GAMETIME_NORMAL > idNormalSmartTimer;
typedef idSmartTimer < GAMETIME_SERVER > idServerSmartTimer;
typedef idPair < gameStat_t , const idStatBase * > idSortableStat;
typedef idGrowableList < idHUDElement * , HUD_ELEMENTS_RECOMMENDED_SIZE > idHudElementList;
typedef idStaticList < idHUDElement * , HUD_MENU_MAX > idHudMenuList;
typedef idStaticList < weaponStats_t , 20 > idWeaponStatsList;
typedef idHandle < short , invalidEncounterGroup_t , INVALID_ENCOUNTER_GROUP > encounterGroupHandle_t;
typedef idList < encounterGroupRole_t > rolePriorityList_t;
typedef idIndex < int , invalidAIDataID_t > aiDataID_t;
typedef idStaticList < const idDeclFactionNode * , 8 > factionTree_t;
typedef idHandle < short , invalidEvent_t , INVALID_EVENT_HANDLE > eventHandle_t;
typedef idInterpolateRelay < float , idTypesafeTime < long long , gameTimeUnique_t , 999960 > > timedBlend_t;
typedef playerWeaponAnimSet_t weaponAnimSet_t;
typedef idHandle < int , invalidSpawnInfluencer_t , INVALID_INFLUENCER > spawnInfluencerHandle_t;
typedef idList < gameViewEntInfo_t > idViewEntityInfoList;
typedef idList < gameView_t > idGameViewList;
typedef tm date_t;
typedef void (*printFunction_t)(const char * msg);
typedef scExport_t* (*GetSourceControlAPI_t)(scImport_t * import);
typedef bool (*meleeTraceHitCallback_t)(const trace_t & trace , idMeleeTrace & meleeTrace , idAnimatedEntity * const owner , const idVec3 & startPos , const idVec3 & curPos , const idVec3 & curPos2 , const bool pastUpdate);
typedef bool (*meleeTraceMultiHitCallback_t)(const multiHitTrace_t & trace , idMeleeTrace & meleeTrace , idAnimatedEntity * const owner , const idVec3 & startPos , const idVec3 & curPos , const idVec3 & curPos2 , const bool pastUpdate);
typedef idList < hudNotification_t > notificationList_t;
typedef idList < dataDrivenOption_t > dataOptionsList_t;
typedef idList < resultHistory_t > historyList_t;
typedef idSharedPtr < idPlatformExternalIdentity > idPlatformExternalIdentityPtr;
typedef idHandle < int , socialPlayerInfoId_type , socialPlayerInfoId_type::SPII_INVALID > socialPlayerInfoId_t;
typedef idList < damageScaleTable_t > idDamageScaleTableList;
typedef idStaticList < threatEntity_t , 4 > threatList_t;
typedef idStaticList < trackedInjuredPlayer_t , MAX_PLAYERS - 1 > trackerList_t;
typedef idHandle < unsigned short , invalidNavUserHandle_t , NAV_USER_HANDLE_INVALID > navUserHandle_t;
typedef idIndex < int , invalidNavVolumeCell_t > navVolumeCellIndex_t;
typedef idIndex < int , invalidArea_t > navAreaIndex_t;
typedef idNavIndex < invalidEdge_t > navEdgeIndex_t;
typedef idIndex < int , invalidObstacleEdge_t > navObstacleEdgeIndex_t;
typedef idNavIndex < invalidReach_t > navReachIndex_t;
typedef idIndex < int , invalidTraversal_t > navTraversalIndex_t;
typedef idTypestrictTimePoint < typestrictRelativeSystemTimestampUnique > relativeSystemTimestamp_t;
typedef idTypestrictTimePoint < typestrictRuntimeTimestampUnique > runtimeTimestamp_t;
typedef idTypestrictTimePoint < typestrictSessionTimestampUnique > sessionTimestamp_t;
typedef idList < idDestructibleInstance * > idDestructibleInstancePool;
typedef idList < int > idDestructibleReservePool;
typedef idList < aiBountyData_t > timedBountyData_t;
typedef idAIBlackboard < 64 > fsmBlackboard_t;
typedef idAIBlackboard < 256 > aiBlackboard_t;
typedef idHandle < int , invalidFSMState_t , INVALID_FSMSTATE > fsmStateHandle_t;
typedef idHavokQueryId idAIClipQuery;
typedef idStaticList < const actionAnim_t * , 64 > actionAnimList_t;
typedef idStaticList < jointMatrixIndex_t , 16 > aiFKJointChain_t;
typedef idList < moveCycleAnim_t > moveCycleAnims_t;
typedef idStaticList < idCornerInfo , MAX_CACHED_CORNERS > idCachedCornerList;
typedef idList < idEncounterGroup > encounterGroupList_t;
typedef idDeclAutomap::idAutomapPointLight_t idAutomapPointLight;
typedef void (*onSettingChangedCallback_t)(void * const param , const int settingIndex);
typedef void (*settingsFocusChangedCallback_t)(void * const param , const int settingID);
typedef idVector < idPlatformExternalIdentityContainer > idExternalIdentityContainerList;
typedef idSharedPtr < seasonDefinition_t > idSeasonDefinitionPtr;
typedef idSharedPtr < seasonProgress_t > idSeasonProgressPtr;
typedef idSharedPtr < idBnetMasterIdentity > idBnetMasterIdentityPtr;
typedef void (*timerCallback_t)(void * const param);
typedef idSharedPtr < battleArenaChallengeDefinition_t > idBattleArenaChallengeDefinitionPtr;
typedef idSharedPtr < battleArenaChallengeCharacterDefinition_t > idBattleArenaChallengeCharacterDefinitionPtr;
typedef idSharedPtr < battleArenaChallengeGroupDefinition_t > idBattleArenaChallengeGroupDefinitionPtr;
typedef idSharedPtr < battleArenaChallengeProgress_t > idBattleArenaChallengeProgressPtr;
typedef idSharedPtr < battleArenaChallengeCharacterProgress_t > idBattleArenaChallengeCharacterProgressPtr;
typedef idSharedPtr < battleArenaChallengeGroupProgress_t > idBattleArenaChallengeGroupProgressPtr;
typedef idList < idHUDEvent_DiagnosticsUpdate::diagnosticsInfo_t::entityInfo_t > idDiagnosticsEntityList;
typedef idHUDEvent_DiagnosticsOnlineUpdate::diagnosticsInfo_t::entityInfo_t idEntityDiagnosticInfo;
typedef idList < idHUDEvent_DiagnosticsOnlineUpdate::diagnosticsInfo_t::entityInfo_t > idDiagnosticsOnlineEntityList;
typedef idList < idHUD_HealthBarInfo , TAG_MENU > idHealthBarWidgetList;
typedef idHUDEvent_OpenEndOfLevelScreen::openEOLData_t::itemInfo_t eolItemInfo;
typedef idTypeInfoObjectPtr < idLogicDebugGeometry > idLogicDebugGeometryPtr;
typedef idList < idManagedClassPtr < class idProjectile_Destroyer > > idDestroyerSplinterList;
