struct idGameSettings
{
    enum gameSettingFields_t : int
    {
        GAME_FIELD_WEAPON_AUTOSWITCHONEMPTY = 0,
        GAME_FIELD_WEAPON_AUTOSWITCHONNEW = 1,
        GAME_FIELD_WEAPON_DOOM_CLASSIC_POSE = 2,
        GAME_FIELD_CROSSHAIR_MODE = 3,
        GAME_FIELD_COMPASS = 4,
        GAME_FIELD_HUD_SHOW = 5,
        GAME_FIELD_INTERACTION_PROMPT = 6,
        GAME_FIELD_GK_HIGHLIGHT = 7,
        GAME_FIELD_BOSS_HEALTH = 8,
        GAME_FIELD_OBJECTIVE_MARKERS = 9,
        GAME_FIELD_NOTIFICATIONS = 10,
        GAME_FIELD_COMBATSCORING = 11,
        GAME_FIELD_TUTORIALS_2 = 12,
        GAME_FIELD_AIM_ASSIST = 13,
        GAME_FIELD_PHOTO_MODE = 14,
        GAME_FIELD_DASH_STYLE = 15,
        MAX_GAME_FIELDS = 16
    };

}; // Size: 0x1
