struct idSettingsDataSource_Game : idSettingsDataSource
{
    enum gameSettingFields_t : int
    {
        GAME_SETTING_DIFFICULTY = 0,
        GAME_SETTING_GK_HIGHLIGHT = 1,
        GAME_SETTING_LOOT_DROP_BRIGHTNESS = 2,
        GAME_SETTING_SHOW_TUTORIALS = 3,
        GAME_SETTING_GAME_HINTS = 4,
        GAME_SETTING_SENTINEL_ARMOR = 5,
        GAME_SETTING_DEMON_BOUNTY = 6,
        GAME_SETTING_PHOTOMODE = 7,
        GAME_SETTING_INVASION_FREQUENCY = 8,
        GAME_SETTING_SHOW_DAMAGE_NUMBERS = 9,
        GAME_SETTING_DASH_STYLE = 10,
        GAME_SETTING_WEAPON_AUTOSWITCH_EMPTY = 11,
        GAME_SETTING_WEAPON_AUTOSWITCH_NEW = 12,
        GAME_SETTING_WEAPON_DOOM_CLASSIC_POSE = 13,
        GAME_SETTING_WEAPON_BOB = 14,
        GAME_SETTING_MATCH_WITH_ACCESSIBILITY = 15,
        GAME_SETTING_SCREEN_SHAKE = 16,
        GAME_SETTING_AUTO_WALL_CLIMB = 17,
        GAME_SETTING_AUTO_WALL_BREAK = 18,
        GAME_SETTING_AUTO_GK_WHEN_DASHING = 19,
        GAME_SETTING_AUTO_SKIP_CUTSCENE = 20,
        GAME_SETTING_AUTO_ATTACK = 21,
        GAME_SETTING_AUTO_COMPLETE_PUZZLES = 22,
        GAME_SETTING_PUZZLE_TIMING = 23,
        GAME_SETTING_GAME_SPEED = 24,
        GAME_SETTING_SHOW_AI_TYPE_ICONS = 25,
        MAX_GAME_SETTINGS = 26
    };

    int currentDifficulty; // Offset: 0x38

    idSWFWidget_GameSettings* owner; // Offset: 0x40

}; // Size: 0x48
