struct idSettingsDataSource_Controls : idSettingsDataSource
{
    enum controlsSettingFields_t : int
    {
        CONTROLS_SETTING_MOUSE_SENS = 0,
        CONTROLS_SETTING_X_MOUSE_SENS = 1,
        CONTROLS_SETTING_Y_MOUSE_SENS = 2,
        CONTROLS_SETTING_INVERT_MOUSE = 3,
        CONTROLS_SETTING_RAZER_CHROMA = 4,
        CONTROLS_SETTING_ENABLE_CONTROLLER = 5,
        CONTROLS_SETTING_HOR_SENS = 6,
        CONTROLS_SETTING_VERT_SENS = 7,
        CONTROLS_SETTING_INVERT_CONTROLLER = 8,
        CONTROLS_SETTING_VIBRATE = 9,
        CONTROLS_SETTING_VIBRATION_SCALE = 10,
        CONTROLS_SETTING_HAPTICS_ENABLED = 11,
        CONTROLS_SETTING_HAPTIC_VIBRATION = 12,
        CONTROLS_SETTING_HAPTIC_RESISTANCE = 13,
        CONTROLS_SETTING_LOOK_SMOOTHING = 14,
        CONTROLS_SETTING_AIMASSIST = 15,
        CONTROLS_SETTING_WEAPONWHEEL_TIME = 16,
        CONTROLS_SETTING_AIMASSIST_SCALE = 17,
        CONTROLS_SETTING_AIMASSIST_TARGET_SNAP = 18,
        CONTROLS_SETTING_GYRO_AIMING = 19,
        CONTROLS_SETTING_GYRO_X_SENS = 20,
        CONTROLS_SETTING_GYRO_Y_SENS = 21,
        CONTROLS_SETTING_MULTIPLE_CONTROL_DEVICES = 22,
        CONTROLS_SETTING_HOLD_TOGGLE_MODS = 23,
        MAX_CONTROLS_SETTINGS = 24
    };

    idSWFWidget* owner; // Offset: 0x38

}; // Size: 0x40
