struct idSettingsDataSource_Accessibility : idSettingsDataSource
{
    enum accessibilitySettingFields_t : int
    {
        ACCESSIBILITY_SETTING_GAME_HINTS = 0,
        ACCESSIBILITY_SETTING_SHOW_TUTORIALS = 1,
        ACCESSIBILITY_SETTING_SENTINEL_ARMOR = 2,
        ACCESSIBILITY_SETTING_WEAPON_BOB = 3,
        ACCESSIBILITY_SETTING_MATCH_WITH_ACCESSIBILITY = 4,
        ACCESSIBILITY_SETTING_SCREEN_SHAKE = 5,
        ACCESSIBILITY_SETTING_AUTO_WALL_CLIMB = 6,
        ACCESSIBILITY_SETTING_AUTO_WALL_BREAK = 7,
        ACCESSIBILITY_SETTING_AUTO_GK_WHEN_DASHING = 8,
        ACCESSIBILITY_SETTING_AUTO_SKIP_CUTSCENE = 9,
        ACCESSIBILITY_SETTING_AUTO_ATTACK = 10,
        ACCESSIBILITY_SETTING_AUTO_COMPLETE_PUZZLES = 11,
        ACCESSIBILITY_SETTING_PUZZLE_TIMING = 12,
        ACCESSIBILITY_SETTING_GAME_SPEED = 13,
        ACCESSIBILITY_SETTING_SHOW_AI_TYPE_ICONS = 14,
        ACCESSIBILITY_SETTING_UI_COLORBLIND_MODE = 15,
        ACCESSIBILITY_SETTING_HUD_COLOR = 16,
        ACCESSIBILITY_SETTING_AIMASSIST = 17,
        ACCESSIBILITY_SETTING_AIMASSIST_SCALE = 18,
        ACCESSIBILITY_SETTING_AIMASSIST_TARGET_SNAP = 19,
        ACCESSIBILITY_SETTING_MULTIPLE_CONTROL_DEVICES = 20,
        ACCESSIBILITY_SETTING_HOLD_TOGGLE_MODS = 21,
        ACCESSIBILITY_SETTING_PSE_FILTER = 22,
        ACCESSIBILITY_SETTING_PSE_LUM_THRESHOLD = 23,
        ACCESSIBILITY_SETTING_PSE_FULLSCREEN_THRESHOLD = 24,
        ACCESSIBILITY_SETTING_MOTION_BLUR = 25,
        ACCESSIBILITY_SETTING_REDUCED_BG_MODE = 26,
        ACCESSIBILITY_SETTING_VIDEO_COLORBLIND_MODE = 27,
        ACCESSIBILITY_SETTING_COLORBLIND_BRIGHTNESS = 28,
        ACCESSIBILITY_SETTING_COLORBLIND_CONTRAST = 29,
        ACCESSIBILITY_SETTING_COLORBLIND_INTENSITY = 30,
        ACCESSIBILITY_SETTING_COLORBLIND_CORRECTIONSTRENGTH = 31,
        ACCESSIBILITY_SETTING_SUBTITLE_ENABLED = 32,
        ACCESSIBILITY_SETTING_CLOSED_CAPTIONING = 33,
        ACCESSIBILITY_SETTING_SUBTITLE_SIZE = 34,
        ACCESSIBILITY_SETTING_SUBTITLE_SHOW_SPEAKER = 35,
        ACCESSIBILITY_SETTING_SUBTITLE_SHOW_BACKING = 36,
        ACCESSIBILITY_SETTING_CHAT_INCOMING_TEXT_TO_SPEECH_ENABLED = 37,
        ACCESSIBILITY_SETTING_CHAT_OUTGOING_TEXT_TO_SPEECH_ENABLED = 38,
        ACCESSIBILITY_SETTING_CHAT_SPEECH_TO_TEXT_ENABLED = 39,
        ACCESSIBILITY_SETTING_CHAT_TRANSLATION_ENABLED = 40,
        ACCESSIBILITY_SETTING_CHAT_SPEECH_PROFILE = 41,
        MAX_ACCESSIBILITY_SETTINGS = 42
    };

    idSettingsDataSource_UI::idProfileToIndexMap masterProfileMap; // Offset: 0x38

    idList < idSettingsDataSource_UI::colorProfileData_t , TAG_IDLIST , false > colorBlindProfiles; // Offset: 0x50

    bool colorBlindProfileActive; // Offset: 0x68

    idSWFWidget* owner; // Offset: 0x70

}; // Size: 0x78
