struct idSettingsDataSource_Video : idSettingsDataSource
{
    enum videoSettingFields_t : int
    {
        VIDEO_SETTING_PSE_FILTER = 0,
        VIDEO_SETTING_PSE_LUM_THRESHOLD = 1,
        VIDEO_SETTING_PSE_FULLSCREEN_THRESHOLD = 2,
        VIDEO_SETTING_FOV = 3,
        VIDEO_SETTING_COLORBLIND_MODE = 4,
        VIDEO_SETTING_BRIGHTNESS = 5,
        VIDEO_SETTING_CONTRAST = 6,
        VIDEO_SETTING_MOTION_BLUR = 7,
        VIDEO_SETTING_LOOT_DROP_BRIGHTNESS = 8,
        VIDEO_SETTING_RESOLUTION_SCALING_MODE = 9,
        VIDEO_SETTING_RESOLUTION_SCALING_TARGET_FRAMERATE = 10,
        VIDEO_SETTING_STATIC_RESOLUTION_SCALE = 11,
        VIDEO_SETTING_DOF = 12,
        VIDEO_SETTING_DOF_AA = 13,
        VIDEO_SETTING_SHARPENING = 14,
        VIDEO_SETTING_HDR_BLOOM = 15,
        VIDEO_SETTING_FILM_GRAIN = 16,
        VIDEO_SETTING_PERFORMANCE_METRICS = 17,
        VIDEO_SETTINGS_ASYNC_PRESENT = 18,
        VIDEO_SETTING_CHROMATIC_ABERRATION = 19,
        VIDEO_SETTING_OVERALL_QUALITY = 20,
        VIDEO_SETTING_TEXTURE_POOL_SIZE = 21,
        VIDEO_SETTING_LIGHTS_QUALITY = 22,
        VIDEO_SETTING_SHADING_QUALITY = 23,
        VIDEO_SETTING_SHADOWS_QUALITY = 24,
        VIDEO_SETTING_PARTICLES_QUALITY = 25,
        VIDEO_SETTING_DECAL_QUALITY = 26,
        VIDEO_SETTING_EFFECTS_QUALITY = 27,
        VIDEO_SETTING_DIRECTIONAL_OCCLUSION_QUALITY = 28,
        VIDEO_SETTING_REFLECTIONS_QUALITY = 29,
        VIDEO_SETTING_DECAL_FILTERING = 30,
        VIDEO_SETTING_MOTION_BLUR_QUALITY = 31,
        VIDEO_SETTING_RENDER_MODE = 32,
        VIDEO_SETTING_WATER_QUALITY = 33,
        VIDEO_SETTING_VOLUMETRICS_QUALITY = 34,
        VIDEO_SETTING_TEXTURE_FILTERING_QUALITY = 35,
        VIDEO_SETTING_GEOMETRIC_QUALITY = 36,
        VIDEO_SETTING_COLORBLIND_BRIGHTNESS = 37,
        VIDEO_SETTING_COLORBLIND_CONTRAST = 38,
        VIDEO_SETTING_COLORBLIND_INTENSITY = 39,
        VIDEO_SETTING_COLORBLIND_CORRECTIONSTRENGTH = 40,
        VIDEO_SETTING_HDR_RENDERING = 41,
        VIDEO_SETTING_120HZ = 42,
        VIDEO_SETTING_RAYTRACING = 43,
        VIDEO_SETTING_DLSS = 44,
        VIDEO_SETTING_DLSS_SHARPNESS = 45,
        VIDEO_SETTING_NEXT_GEN_FEATURE = 46,
        MAX_VIDEO_SETTINGS = 47
    };

    struct videoSettingsMenuData_t
    {
        int value; // Offset: 0x0

        char* label; // Offset: 0x8

    }; // Size: 0x10

    bool restoringDefaults; // Offset: 0x88

    idSWFWidget* owner; // Offset: 0x90

}; // Size: 0x98
